Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml

Adds feet slots for AGhosts
Neptune wants to add socks for AGhosts so they need this
I went into the afterlife and broke the ghosts legs so they can fit into them
Theres no whitelist for what can go on AGhosts feet, i might get around to it at somepoint but since its an admin only thing its not that big
**Changelog**
Added: Admin Ghost Feet!

Gives AGhosts feet for ghost socks

---

Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml

Vox and slimes dont have nitrogen round start.
addding it as a trinket item gives them some more life time.
Emergency Nitrogen Tank, not a full size tank

Adding Nitrogen tank to Trinket

---

Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/Maps/cluster.yml
Resources/Prototypes/Maps/core.yml
Resources/Prototypes/Maps/fland.yml
Resources/Prototypes/Maps/meta.yml
Resources/Prototypes/Maps/oasis.yml
Resources/Prototypes/Maps/origin.yml
Resources/Prototypes/Maps/packed.yml
Resources/Prototypes/Maps/train.yml

Train is back in selection temporarily for now.
Certain stations should be available again even when there's a low amount of players on the server.
Spacepens are back in the Emergency Box.
It was here before the refactor but didn't come out with it being done, so I'm redoing it back again. Plus, Train is just going to exist for a singular day until then since it's atmos is being redone.
Changes the minimum and maximum number of players that will allow the map to be available in the map rotation.
The flare has instead been replaced with the Spacepen due to storage limitation.
Train was readded to the Map rotation but still requires it's atmos redone.
No media.
None?
**Changelog**
Added back Train, the Spacepen in the Emergency Box, and certain Space Stations to the rotation.

Readding stuff. (Train, Spacepen in Emergency Box, and Maps to the rotation.)

---

Resources/Prototypes/Roles/Antags/revolutionary.yml
Resources/Prototypes/secret_weights.yml

Literally just an unfucked, scaled down version of the rev changes PR- by that, VERY scaled down. Might add the midround revs later or some of the other changes when i'm less shitty at PRs. Reopened to not be master branch.
**Changelog**
:cl:
- add: Headrevs now have syndicate encryption keys. Coordinate and plan a strategy!
- tweak: Revs and survival chances have been swapped. Revs at a 10%, and survival at 5%.

 Headrevs now have syndicate encryption keys, Revs and survival chances swapped

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Goobstation/Entities/Clothing/OuterClothing/armour.yml
Resources/Prototypes/Goobstation/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/Goobstation/Recipes/Lathes/clothing.yml

Nerfed durathread armour to be more expensive, take longer to print, no longer be in sec fab, etc.
It was extremely broken.
**Changelog**
:cl:
- tweak: Durathread armour is no longer extremely overpowered.

Nerf durathread armour

---

Resources/Prototypes/Datasets/Names/ninja.yml
Resources/Prototypes/Datasets/Names/ninja_title.yml
Resources/Prototypes/Datasets/Names/skeleton_first.yml

Removed a Ninja name and title along with a Skeleton first name. (Boner, Throat, Deep.)
There's no way in hell you don't know where I'm going with this. "Boner" come on. I'm not staring at my monitor watching a Ninja named "Deep Throat" bro.
Removed "Boner" from the Skeleton first name file. I also remove the "Deep" name along with "Throat" from the Ninja Titles file.
None?
**Changelog**
Removed certain Skeleton and Ninja names.
:cl:
- removed: Inappropriate names.

Remove inappropriate names from skeletons and ninjas.

---

Content.Server/Atmos/EntitySystems/PipeRestrictOverlapSystem.cs
Content.Shared/CCVar/CCVars.cs

Readded pipe stacking, but good.  
Pipes only anchor if they add a new pipe direction to the tile. This means not only are we limited to 4 (for now, pipe layers/multiZ just a week away) devices per tile, but they also MUST necessarily provide value to the Atmos Tech at hand. Not to mention the immense readability increase since now you can just rightclick and mouse over pipes, though a future PR (i.e. making context-menu-highlighted pipe outlines overlay green over all entities) might alleviate this issue.
It has become increasingly harder to make clean and readable Atmos and SM setups for anything complicated, such as a hybrid SM+TEG setup on Oasis - let alone running a frezon setup in parallel. Modern atmos setups are in some ways more spaghetti than pre-stacking change setups; although …

Introduce balanced pipe stacking

---

Content.Server/Administration/Commands/PlayTimeCommands.cs

Changed the playtime commands to allow the minutes argument to take a time string instead of just a number of minutes. This can be done like this: 1y1mo1w1d1h1m, but the order and the number you put in **does not matter whatsoever.** If an invalid time unit is specified, it is counted as 0 minutes. This is a fully optional change; you can still do the number of minutes without issue, but this is here to automate hour-to-minute or any other time unit translation with 0 effort on an admins' part.
Here's the list of all possible units:
- 1y - translates to 1 year in minutes
- 1mo - translates to 1 month in minutes
- 1w - translates to 1 week in minutes
- 1d - translates to 1 day in minutes
- 1h - translates to 1 hour in minutes
- 1m - translates to 1 minute in... minutes?
An issue was …

Add optional time strings to playtime commands

---

Content.Server/Audio/Jukebox/JukeboxSystem.cs

Jukeboxes can now activate artifacts when a song is played through an ActiveInstrument component.
I raged about it in LOOC once that Jukeboxes don't activate artifacts.
An ActiveInstrument component is added when the jukebox is playing music. The component is then removed when power is cutoff to the jukebox, when the jukebox is paused, or the jukebox is stopped. Players can't join a band with jukeboxes either.
None from what I can see.
**Changelog**
:cl:
- add: Jukeboxes now activate artifacts

Jukeboxes now activate artifacts

---

Content.Server/Goobstation/Ghostbar/GhostBarSystem.cs

People can't roll midround antags in the ghostbar anymore.
We don't need people in ghostbar rolling syndie.
Just gives the players the antagimmune and mindshield components.
**Changelog**
:cl:
- fix: Ghost bar goers can no longer roll midround antag.

No more antag ghostbar people:)

---

Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml

Changes roleplay rule 4 to remove the MRP amendments and to explicitly prevent metagaming information while crit/unconscious.
Constant confusion from this rule due to the MRP amendments have made it a rule which commonly creates problems. This should fix that. Not to mention that we were already handling this rule in this way.
Just changes some lines in the XML file.
**Changelog**
:cl:
- tweak: Updated roleplay rule 4 to explicitly deny metagaming while crit/unconscious.

Slightly Updates Roleplay Rule #4

---

Content.Client/UserInterface/Systems/Actions/Widgets/ActionsBar.xaml

It looks better
https://discord.com/channels/1202734573247795300/1202734573247795303/1272097080617340989
**Changelog**
:cl:
- tweak: The button for pages has been moved to the top of the UI.

action bar PageButtons relocation

---

Content.Shared/Goobstation/Changeling/ChangelingComponent.cs

Quick fix for the ling status icon, didn't realize i had to update it inside of the changeling component when upstream changed statusicons to factionicons, oops!
:cl:
- fix: Changeling hivemind status icon fixed

Ling Status Fix

---

Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
Resources/Changelog/GoobChangelog.yml

Simple fix to change the revolutionary gamemode so that it immediately ends when all of command dies
https://github.com/Goob-Station/Goob-Station/issues/372
Saw this issue easy fix
Very simple rewrites the existing logic so instead of calling the shuttle when command dies, it ends the game
:cl:
- tweak: Rev victory ends game instead of calling shuttle

Rev gamemode tweak

---

Resources/Maps/Goobstation/Nonstations/nukieplanet.yml
Resources/Maps/Goobstation/Shuttles/infiltrator.yml

- Added hotplate, electolyzer and centrifuge to nukie med.
- Added directional sighs for easier navigating.
- Removed RCD.
- Added intellicard and intercom electronics for interactions with AI.
- Shuttle turrets not disposable anymore, Their amount inside the shuttle decreased and they don't block the passage. Moved outside turrets from shuttle walls. Added two more turrets near north entrance.
- Axe moved from inaccessible air chamber to fireaxe case with nukeops access (You can find it near atmos).
- Two papers of codes replaced with nuke codes folder on shuttle.
:cl:
- tweak: Nukie planet medbay now has more tools
- tweak: The nukie planet now has signs for easier navigation
- tweak: The nuke code papers now come in a folder
- tweak: Nukies now get an intellicard and intercom …

Nukie planet update

---

Resources/Prototypes/Entities/Structures/Wallmounts/intercom.yml

Secure intercoms no longer destroy their encryption keys when the secure panel is removed. Allowing Command and Security keys to be extracted.
Saw it listed as an open issue / minor-bug
https://github.com/Goob-Station/Goob-Station/issues/705
Added key_slots and board container names to BaseIntercom ConstructionComponent prototype. So that ConstructionSystem::ChangeEntity tracks and transfers the inventory of BaseIntercomSecure (intercomReinforced construction node) prototypes when deconstructed into IntercomConstructed (intercom construction node). 
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an …

Add BaseIntercom ConstructionComponent containers

---

Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
Resources/Prototypes/Roles/Antags/nukeops.yml
Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/syndicate.yml
Resources/Prototypes/_Goobstation/Roles/Antags/nukeops.yml
Resources/Prototypes/_Goobstation/tags.yml

Now nukeops reinforcement has nukeops tagged uplink so no buying bows as nukies.
Only nukie commander uplink has commander hardsuit and it has a limit of one purchase, same thing with medic.
War min nukies decreased to 2.
Now tc amount for declaring war scales with server population and missing nukies.
3 nukies couldn't declare a war on 85 pop server, even if they could, they would stand no chance against the crew.
**Changelog**
:cl: Aviu
- add: Nukie reinforcement has nukeops uplink.
- tweak: Only nukie commander has commander hardsuit for sale in has uplink and it has limited stock of 1. Same thing with medic.
- tweak: Minimum number of operatives for war declaration is reduced to 2.
- add: Now the amount of tc for war declaration scales with amount of players on server and missing …

Uplink stuff & war tweaks

---

Content.Shared/Damage/Systems/StaminaSystem.cs

Fixed a bug when you could get stunlocked if you are being hit by stamina damage while in critical state.
**Changelog**
:cl: Aviu
- fix: Now you can't get stunlocked while in critical state.

Fix stunlock

---

Resources/Prototypes/Roles/Jobs/Science/borg.yml

lowers station ai playtime requirement
15 hours as borg is dumb
changes ai playtime requirement from 15 hours to 5 hours as it originally was
**Changelog**
:cl:
tweak: lower AI playtime req

lower ai playtime requirement

---

Content.Server/Administration/ServerApi.cs
Content.Server/Administration/Systems/BwoinkSystem.cs
Content.Server/Discord/WebhookPayload.cs

Ported https://github.com/new-frontiers-14/frontier-station-14/pull/2283
No longer do admins need to be ingame for every AHelp.
This PR requires:
1. Something that can handle the discord side, see original PR for details. You can also use my [RedBot cog](https://github.com/sleepyyapril/april-cogs), if you use RedBot.
2. A set admin.api_token CVar value to use on the discord side.
3. CVar status.enabled being true
This PR changes the way the BwoinkSystem works to allow for custom URLs instead of just an id and a token for webhooks, as well as adding an admin API HTTP POST method under ``/admin/actions/send_bwoink``.
**Changelog**
:cl:
ADMIN:
- add: Added the ability to reply to AHelps while exclusively on discord.

Discord Ahelp Reply System (#2283)

---

Resources/Prototypes/_Goobstation/Entities/Objects/Materials/materials.yml

Bluespace Crystals now get sucked into ore bags. Both regular and holding.
All other raw ores do, it was annoying to have to pick up mined crystals and put them in a regular inventory. Now they get sucked up by ore bags and can actually go inside them now.
Added the missing `ore` tag to the Bluespace Crystal ore prototype.
n/a
**Changelog**
:cl:
- fix: Bluespace Crystals now properly get picked up by ore bags!

Fix Bluespace Crystals not being picked up/allowed inside ore bags

---

Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_arrows.yml

Changed the following damages for hardlight bow:
Base - 30 Heat -> 50 Heat
Disabler - 60 Stam -> 45 Stam
Fire - Damage unchanged, deals 3 fire stacks rather than 1.5
Ice - 20 cold -> 5 cold. Cools target down by around double previous amount.
X-ray - 24 heat -> 35 heat.
Bees - Summons 8 bees rather than 4.
As discussed in Discord with other players, the hard light bow is extremely weak for an 80TC purchase, so we tested and played with numbers to make it a bit better. Before going further, keep in mind that the bow is extremely difficult to land hits with and extremely punishing for missing them. Before this change, it was out DPS'd by the viper, a 14TC purchase. 
- The base arrow was made to two hit unarmored targets, with a kill time of around 3 seconds if one has perfect accuracy. If …

Hardlight bow buff

---

Content.Shared/Ensnaring/SharedEnsnareableSystem.cs
Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml

Bolas now knockdown but do not force to drop items. This makes sense I think. Removed stamina damage from bolas.
Also fixed an exception when trying to remove ebola from a person.
Bolas shouldn't have stamina damage to prevent dirty combos with mansus grasp and similar stuff.
**Changelog**
:cl: Aviu
- add: Bolas now knock people down, items are not dropped from their hands.
- remove: Bolas no longer deal stamina damage.

Bola knockdown

---

Content.Server/_White/FootPrint/PuddleFootPrintsSystem.cs

Fixed server side assert caused by puddle EndCollideEvent while puddle component was being deleted.
Because I kept seeing errors in my log while explosively gibbing corpses.
OnStepTrigger would get triggered via 
- RecursiveDeleteEntity(...) / RemoveComponentImmediate(...)
- LifeShutdown(...)
- CompShutdownInstance event
- SharedPhysicsSystem::OnChangeShutdown(...)
- SharedPhysicsSystem::DestroyFixture(...)
- SharedPhysicsSystem::DestroyContact(...)
- EndCollideEvent event
At this point the container state relevant to the solution is potentially already invalidated (up to hashset order) causing ResolveSolution to assert.
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guideline …

Fix EndCollide puddle error

---

Content.Server/DeviceNetwork/Systems/DeviceListSystem.cs
Content.Server/DeviceNetwork/Systems/NetworkConfiguratorSystem.cs

Fix tracking of active network cofigurators. Add validation of tracked configurators and devices.
This was the second of the sources of Can't resolve ```Robust.Shared.GameObjects.MetaDataComponent```
errors in the logs that I was given.
Improper checking and clearing of ActiveDeviceList caused references DeviceLists configurator lists to become stale. This breaks the updater function into a controlled region and fixes these issues. There are two ways to desync the list I found:
1. Mixed UI
1. open a list view
3. open a config view (sets ActiveDeviceList)
4. close the list view (clears ActiveDeviceList)
5. close the config view (ActiveDeviceList is null, DeviceList is not updated)
2. Device Switching
1. open a config view (sets ActiveDeviceList)
2. open a config view for a different …

Fix tracking of ActiveDeviceList

---

Content.Server/Administration/ServerApi.cs
Content.Server/Administration/Systems/BwoinkSystem.cs
Content.Shared/CCVar/CCVars.cs

Added a CVar to use an admin's OOC color, if it exists.
Added several CVars for discord ahelp replies, including the ability to use role name and color.
This does require you to update the april-cogs/ahelp_replies cog.
Mostly cosmetic, configuration is set to use the defaults.

AHelps: The Configuration Update

---

Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml

**Changelog**
:cl:
- fix: The burner rifle is now nukeops whitelisted instead of nukeops blacklisted

fix burner uplink whitelist

---

Content.Server/_Goobstation/Changeling/ChangelingSystem.cs

John Station refuses to learn body/damageable code, and I refuse to learn changeling/heretic code to fix his shitcode, so @ARMOKS came up with a simple suggestion for now, disable limb severing on lings. This prevents a huge chunk of the shitmed issues with them, just leaving disabling as their main problem. At some point this all needs to be refactored & fixed.
**Changelog**
:cl:
- tweak: Changeling limbs cannot be severed now. Definitely not-permanent.

Sorta hotfix? Ling limbs are no longer severable

---

Resources/Prototypes/_Goobstation/Recipes/Reactions/chemicals.yml

Title
More explosive options for chemists. Plus, potassium is important, sodium is used only a handful of places
**Changelog**
:cl:
- add: sodium now explodes in water, just like potassium

Add sodium-water reaction

---

Resources/Prototypes/Entities/Mobs/base.yml

husking just a week away
SM is unaffected
if someone has 5000 burn at least you can brain transplant them
its also horrifically buggy with shitmed so no more torsoless gamers
commented it all out
no
**Changelog**
:cl:
- remove: Extreme heat no longer turns people to ash.

disable ashing until husking is added

---

Resources/Prototypes/_Goobstation/Catalog/Fills/Belt/belts.yml

cmo chest rig now gets medicated suture regenerative mesh and brute/burn autoinjector instead of the dogshit topicals
its also actually medical restricted contra now and has the filled suffix
**Changelog**
:cl:
- tweak: cmo chest rig gets better topical stuff now
- fix: cmo chest rig is medical restricted contra now

cmo chestrig changes

---

Resources/Prototypes/Entities/Objects/Materials/ore.yml
Resources/Prototypes/Procedural/biome_ore_templates.yml
Resources/Prototypes/Procedural/vgroid.yml
Resources/Prototypes/_Goobstation/Procedural/biom_ore_templates.yml
Resources/Prototypes/_Goobstation/Procedural/salvage_loot.yml
Resources/Prototypes/ore.yml

I reverted back almost at the identical ore composition and ore procedural generation
Bounty : https://discord.com/channels/1202734573247795300/1313673129599438899
With the recent changes, it seems there is an heavy strain on station resources and science resources in general, mostly due to wizden #https://github.com/space-wizards/space-station-14/pull/30920.
**Changelog**
:cl:
- remove: Removed Wizden ore nerf
- tweak: Ore procedural generation on asteroïds and vg roid. Increased ore composition

Ore balancing (revert from wizden nerf)

---

Resources/Locale/en-US/reagents/meta/narcotics.ftl
Resources/Prototypes/_Goobstation/Recipes/Reactions/chemicals.yml
Resources/Prototypes/_Goobstation/Recipes/Reactions/single_reagent.yml
Resources/Prototypes/_Goobstation/explosions.yml

Meth will now explode when heated to 420K, with a small area of effect that destroys adjacent machines.
Adds some danger/excitement to chem, and more pyrotechnics options.
An attentive chemist will take their meth off the hotplate when it finishes cooking without any issue,
the inattentive chemist or one that uses ChemMaster temperature jank will have their meth explode in their face
Considering the SS13 equivalent happens at only 10K above it's creation temperature, this is significantly more lenient
- New explosion type that deals mainly blunt damage, will allow tweaking of tile destruction if someone makes the explosion more powerful
- Heating Desoxyephedrine to 420K will make it explode strong enough to take out directly adjacent machines
**Changelog**
:cl:
- tweak: Desoxyephedrine, …

Make Meth Explosive!

---

Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml

Literally 1 line, prevents BSO from spawning with 2 emergency boxes.
Real
Real

Fix BSO getting two emergency boxes

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml

Added therapeutic patches, essentially the rapid patch in reverse
It may end up being too strong, but I created this because I noticed how little the rapid patch is used, due to overdosing. So I decided to create a variant that actually contends with the normal and large patches.
- New patch that injects 0.5u/s and has 40u capacity, craftable at the medical techfab for the same price as other patches
**Changelog**
:cl:
- add: Therapeutic patches that inject 0.5u/s with a total capacity of 40 units.

Therapeutic patches

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml

See title
Adds a quick way for officers to be outfitted with bodycams
- changed secdrobe.yml to include 5 bodycams
**Changelog**
:cl:
- tweak: The SecDrobe now has 5 bodycams, so you can film your clown abuse in crystal clear 360p!

Bodycams in the Secdrobe

---

Resources/Prototypes/Entities/Structures/Furniture/sink.yml

I changed the amount of water in the sinks to 9999999, similar to this PR https://github.com/Goob-Station/Goob-Station/pull/762
The PR above removed water regeneration to reduce lag, and made it so SinkEmpty has 9999999 water. The normal sink parents off of SinkEmpty, but then redefines their quantity to 500, so every sink below that inherits their 500 water instead of the intended 9999999 water. That means 3 out of 5 sinks that get mapped into the game have neither infinite water nor regenerative water, and quickly run out. 
I changed the Quantity: 500 in Sink and SinkStemlessWater to have the intended 9999999 water.
**Changelog**
:cl:
- fix: Fixed some sinks having 500u of water instead of infinite water.

Fixed sinks having 500 water instead of 9999999 water

---

Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml

makes goliaths slower, squishier and makes them see less but also makes them do 50 damage per hit
goliaths drop 2 hide instead of 1 when butchered
hivelords are a bit slower
hivelord minions damage, attack speed and vision reduced a little
the shit you get from butchering hivelords now rots in 6 minutes instead of 2 and when rotten is worth 1000 instead of 500
makes vgroid more bearable, as of now it's not worth going there since the loot is shit and you have to cheese all mobs in it by building railings.
**Changelog**
:cl: 
- tweak: Goliaths and hivelords are now weaker.

goliath and hivelord rebalancing

---

Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml

made ling headslugs able to crawl under tables and doors
so the ability is worth using
**Changelog**
:cl:
- tweak: Changeling headslugs can now crawl under tables and doors

changeling slugs can now walk under tables and doors

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Recipes/Lathes/sheet.yml

Remove Bluespace Crystal craft from protolathe. Now it's rare ore only.
1. Bluespace crystal entirely ruining economy (one crystal costs 3000 credits when components costs less than 50 credits)
2. Craft 30 bluespace crystals - get 30 scram implants without cooldown. 
:cl:
- remove: Removed bluespace crystal craft from protolathe.

Rage Nerf - Remove Bluespace Crystal craft from protolathe

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml

Buffed sabre back to its original reflection chance 
Sabre is useless without reflection this change makes it actually a viable weapon for captains to defend themselves 
**Changelog**
- tweak: Captain Sabre's reflection was buffed back to 30% chance.

Buff sabre

---

Content.Server/Fluids/EntitySystems/PuddleSystem.Spillable.cs
Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/pneumatic_cannon.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/pneumatic_cannon.yml
Resources/Prototypes/_Goobstation/Entities/Weapons/Guns/pneumatic_cannon.yml

made thieves able to throw containers with liquids in them (does not include beakers as they break on impact) and shoot non-lethal guns like disablers, practice guns, syringe guns and pneumatic cannons
disablers do 0 damage now so there's no reason for thieves not to be able to fire them
space cola cans are very cool for slipping seccies 
**Changelog**
:cl:
- tweak: Pacifists can now throw things with liquids in them, shoot syringe guns and disablers

thieves can now throw cans and shoot non-lethal guns

---

Resources/Prototypes/Recipes/Reactions/pyrotechnic.yml

Gave Phlogiston priority identical to CLF3, allowing for it's formation before smoke and foam removes it's reactants from the beaker.
Makes phlogiston more than just an alternative to CLF3 that doesn't explode.
I like plasma fires :godo:
- Phlogiston now has a priority of 20
**Changelog**
:cl:
- tweak: Phlogiston now has a priority of 20, which makes it's reaction take place before foams and smokes :feelsgood:

Raise Phlogiston Reaction Priority

---

Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/high_caliber_magazine.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Rifles/rifle.yml

burner rifle gets AP for shits and giggles, ammo is more available and mags are slightly bigger.
it was suggested on the discord, you kinda plow through bullets.
1.6-1.1 TC per bullet :trollface: 
https://discord.com/channels/1202734573247795300/1314468353783631892
**Changelog**
:cl:
- tweak: The Burner assault rifle now has AP as god intended.
- tweak: The Burner assualt rifle now has 15 round mags and you can buy more in the uplink.

Burner assault rifle buff

---

Resources/Prototypes/Voice/speech_emotes.yml

see title
just otherwise doesn't make sense, it's like using `*Screams.` as a real emote
.toLowerCase().slice(-1)
**Changelog**
no cl no fun

give wehs a lowecase emoting

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml

title
IPCs need them to not explode from a shocked grille and maybe engi wont be stingy when theres this many
**Changelog**
:cl:
- tweak: EngiVends now have 12 insuls instead of 6.

up insuls in engivend to 12

---

Content.Shared/Weapons/Ranged/Components/NoWieldNeeded.cs
Content.Shared/Weapons/Ranged/Events/GunRefreshModifiersEvent.cs
Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
Content.Shared/Wieldable/WieldableSystem.cs
Content.Shared/_Goobstation/Weapons/Ranged/NoWieldNeededComponent.cs
Resources/Locale/en-US/_Goobstation/metabolism/metabolizer-types.ftl
Resources/Locale/en-US/metabolism/metabolizer-types.ftl
Resources/Prototypes/Chemistry/metabolizer_types.yml
Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/Reagents/Consumable/Drink/soda.yml
Resources/Prototypes/Reagents/biological.yml
Resources/Prototypes/Reagents/botany.yml
Resources/Prototypes/Reagents/chemicals.yml
Resources/Prototypes/Reagents/cleaning.yml
Resources/Prototypes/Reagents/elements.yml
Resources/Prototypes/Reagents/fun.yml
Resources/Prototypes/Reagents/gases.yml
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/Reagents/narcotics.yml
Resources/Prototypes/Reagents/pyrotechnic.yml
Resources/Prototypes/Reagents/toxins.yml
Resources/Prototypes/_Goobstation/Body/Organs/yowie.yml
Resources/Prototypes/_Goobstation/Body/Prototypes/yowie.yml
Resources/Prototypes/_Goobstation/Chemistry/metabolizer_types.yml
Resources/Prototypes/_Goobstation/Damage/modifier_sets.yml
Resources/Prototypes/_Goobstation/Entities/Mobs/Species/yowie.yml
Resources/ServerInfo/Guidebook/Mobs/Yowie.xml

I changed the Yowie to have some better bonuses to make up for their severe limitations and add RP value. I also adjusted one of those limitations.
My changes include:
- Making the heat resistance equal to that of Vulps (they have fur too)
- Slightly nerfing their cold resistance
- Making them immune to non-metabolised poison attacks (of which there are not all that many)
- Giving them their own organs, organ prototypes, and metabolisms
- Removing **poison** damage on all metabolism effects, making them immune to certain reagent effects (such as ForcedSleep), removing most medicine overdose damage/effects, and giving them comprehensive healing from most narcotics
- Slightly increased their unarmed attack (to 10) and gave them a wideswing alt attack
- Added a component for bypassing …

Make yowie playable

---

Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
Resources/Prototypes/Entities/Objects/Tools/welders.yml

1 cable now heals 3 heat damage (previously 1.66)
1 weld now heals 25 brute damage (previously 15)
ipcs aren't combat viable as of now because of their super slow healing and their fire weakness (2 flare gun shots kill them)
**Changelog**
:cl:
- tweak: Ipcs heal faster now.

buff ipc healing

---

Content.Shared/Atmos/Atmospherics.cs
Resources/Prototypes/Atmospherics/gases.yml

Changed Frezon tritium ratio back to 1:50 instead of 1:8, changed frezon price from 1.5 to 0.3. So now you need way less tritium to make frezon (as much as it was needed before the [wizden nerf](https://github.com/space-wizards/space-station-14/pull/32407))
Considering we have sm, and with the addition of the new gasses, being able to produce more moles of frezon for a lower selling price is better than a lower amount of moles for higher price.
**Changelog**
- tweak: Changed frezon oxygen:tritium ratio from 1:8 -> 1:50, and changed frezon price per mole from 1.5->0.3

Make frezon great again

---

Resources/Prototypes/GhostRoleRaffles/settings.yml

removes raffles being extended when someone joins
major role raffles are now 25 seconds
short raffles are now 5 seconds
extend by 10 seconds on join is fucking stupid
they were too long in the first place
**Changelog**
:cl:
- tweak: Raffle timers are now lower.

lower raffle time

---

Resources/Prototypes/_Goobstation/Entities/Structures/Walls/asteroid.yml

I made it so that bluespace crystal ore rocks show up on the mineral scanner like all the other rocks with ores in them. 
People already complain about BS crystals being removed from the lathe, so now at least salvage can find them more easily.
I saw that map: [ "enum.MiningScannerVisualLayers.Overlay" ] was under all the ore rocks outside of the _Goobstation folder, but the BS crystals didn't have it. I copy pasted it there, and the rocks showed up on the mineral scanner.
Yep, there they are. I spawned in all the different types of wall rock in case some didn't show up.
**Changelog**
:cl:
- fix: Bluespace Crystal ore rocks now show up on the mineral scanner.

Fixed bluespace crystals not showing up on mineral scanner

---

Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml

The Blue-shield Officer now spawns with the EG-4 and pin-pointer in their inventory instead of having to find their locker.
I've been playing a lot of late-join BSO, and realized that if you late join into a bad situation, you're kind of just fucked. Even though you are supposed to be an elite body guard you can actually only do anything if you find your locker, and if you late-join into the station being fucked/someone has already looted your locked your only solution is just crying. With this change, even if you late join into the 90% of command being dead and all the power out you can *attempt* to pull some john wick shit and kill the nukies/issue.
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/code …

Blueshield revolver on spawn

---

Resources/Prototypes/Roles/Jobs/Security/detective.yml

Detective now starts with forensic gloves equipped.
I was talking in-game about tweaking the previous BSO changes, and someone suggested I change this, so I did. I also thought it was pretty dumb that you had to leave fingerprints/fibers everywhere, and THEN get to your locker.
**Changelog**

Detective now starts with forensic gloves equipped

---

Content.Server/Implants/ImplanterSystem.cs
Content.Server/_Goobstation/Implants/MindcontrolImplantSystem.cs
Content.Shared/Implants/Components/SubdermalImplantComponent.cs
Content.Shared/Implants/SharedImplanterSystem.cs
Content.Shared/_Goobstation/Implanter/PreventSelfImplantComponent.cs
Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/mindcontrol_implant.yml

allows traitors and surpluses to buy:
- death acidifier
- microbomb
- macrobomb
also makes all 3 take 4x time (20 seconds) to implant into other people so no fast roundremoval
why not, traitors can already suicide bomb with other explosives or syndibomb anyway
also made a poll on discord for it and it was 10/1 in favor of adding macrobomb
tested, trust
also removes shitcode from mind control implanter (no gameplay changes)
**Changelog**
:cl:
- tweak: Traitors may now buy the acidifer, microbomb, and macrobomb implants.
- tweak: Suicide implants now take 4 times as long (20s) to implant into others.

allow traitors to buy suicide implants

---

Content.Shared/Weapons/Reflect/ReflectComponent.cs
Content.Shared/Weapons/Reflect/ReflectSystem.cs
Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml

Ported [this](https://github.com/space-wizards/space-station-14/pull/31902).
**Changelog**
:cl: BIGZi0348
- tweak: Reflective vest now reflects lasers only while equipped.
- tweak: Energy katana now reflects lasers and projectiles only while in hands.

Tweak - Reflective vest and Energy Katana should reflect only in correct slots

---

Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/secret_weights.yml

fixed nukie names being some dumb shit
tweaked some secret weights
nukie, rev and survival too high
made fun gamemodes more common

secret weight tweaks + nukie name fix

---

Content.Shared/Stealth/Components/StealthComponent.cs
Content.Shared/Stealth/SharedStealthSystem.cs
Resources/Prototypes/StatusIcon/faction.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Head/hardsuit-helmets.yml

makes the use of the syndicate stealth hardsuit visible when in crit or dead.
its a problem that nukes just dissapere when in critical and cant be found by teammates.
there is a problem: when you go critical, the component stops updating.
that the stealth component dont start untill you take off the helmet and put it back on.
**Changelog**
:cl:
- tweak: Steathsuit stops working when in crit
- tweak: Nuclear Oprative icon is visable when in stealth

disable Stealth of stealthsuit when in critical or death AND syndicate icon shows when in stealth.

---

Resources/Prototypes/_EinsteinEngines/InventoryTemplates/ipc_inventory_template.yml

Moved the Eye slot for IPC inventory up next to the Headwear, making it consistent with the other species inventories and fixing the issue where it overlapped with the button to close the inventory.
The design doc for this change was reviewed through all three stages and approved by all relevant parties before put forward. It's the Cabal's opinion that this change may bring some future balancing changes to the Inventory meta.
Changed a 0 to a 3.
**Changelog**
:cl:
- fix: Fixed IPC glasses slot being in the wrong place. Glasses go on your face, silly.

Fix IPC Inventory Eye Slot Position

---

Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml

Title
People sometimes go unnoticed that youre low on battery as IPC, this change will actually have a higher chance of alerting people that walks by.
**Changelog**
:cl:
- tweak: Lowered IPC low battery alert intervals.

Decreased IPC Low Battery Alert Time

---

Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml

I added the Goob Station Space Law maximum sentence requirement to the Space Law in the guidebook so people stop complaining about it not being there.
Goob Station has its own Space Law that isn't shown in the game. The maximum brig time currently is 10 minutes and is not reflected anywhere in the current Space Law shown in the guidebook.
**Changelog**
:cl:
- tweak: Fixed Guidebook Space Law to mimic online GS Space Law.

Added Maximum Sentence Ruleset According to GS Space Law In-Game

---

Resources/Maps/_Goobstation/atlas.yml
Resources/Maps/_Goobstation/bagel.yml
Resources/Maps/_Goobstation/barratry.yml
Resources/Maps/_Goobstation/box.yml
Resources/Maps/_Goobstation/core.yml
Resources/Maps/_Goobstation/kettle.yml
Resources/Maps/_Goobstation/marathon.yml
Resources/Maps/_Goobstation/meta.yml
Resources/Maps/_Goobstation/omega.yml
Resources/Maps/_Goobstation/packed.yml
Resources/Maps/_Goobstation/saltern.yml

I added the mail teleporter, maildrobe and mail metrics cartridge into the nine maps that didn't already have all three. It's outside the scope of the PR, but I also added a cargo bounty computer to Kettle, because why didn't it have one? Barratry is the run down station that makes you fix everything, and even they don't make you craft your own bounty computer using the QM's spare.
Some maps already have mail teleporters and maildrobes, but not all maps. If it's functional enough for those maps, I figure it should be included in all of them. Also the Kettle bounty computer because no cargo map should require cargo to build their bounty computer.
I opened the map editor and spawned them in.
**Changelog**
:cl:
- add: Added Mail Teleporter, Maildrobe and Mail Metric Cartridge to Cargo
- fix: …

Maps mail teleporter and other mail accessories into cargo (and a bounty computer to Kettle)

---

Content.Shared/Doors/Systems/SharedAirlockSystem.cs
Content.Shared/Doors/Systems/SharedFirelockSystem.cs
Content.Shared/Maps/ContentTileDefinition.cs
Content.Shared/Prying/Components/PryingComponent.cs
Content.Shared/Prying/Systems/PryingSystem.cs
Content.Shared/Tools/Systems/SharedToolSystem.Tile.cs
Content.Shared/Tools/Systems/SharedToolSystem.cs
Resources/Prototypes/Entities/Debugging/spanisharmyknife.yml
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
Resources/Prototypes/Entities/Objects/Tools/cowtools.yml
Resources/Prototypes/Entities/Objects/Tools/crowbars.yml
Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
Resources/Prototypes/Entities/Objects/Tools/tools.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
Resources/Prototypes/Tiles/plating.yml
Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Tools/tools.yml
Resources/Prototypes/_Shitmed/Body/Parts/cybernetic.yml

Now it it possible to instantly pry tiles, firelocks and unpowered doors using tools. Instead of a do-after, there's now use delay. You still can't instantly pry using your bare hands. You can't also instantly pry plating using fire axe, there's a 5 second do-after.
There is no point of slowing down the game by adding annoying do-afters. Instant prying will make life much easier.
**Changelog**
:cl: Aviu
- add: Now tiles, firelocks and unpowered doors are pried instantly using a tool.

Instant prying

---

Content.Client/Atmos/Consoles/AtmosAlarmEntryContainer.xaml.cs
Content.Server/Atmos/Portable/PortableScrubberComponent.cs
Content.Server/EntityEffects/EffectConditions/BloodReagentThreshold.cs
Content.Server/EntityEffects/Effects/AddReagentToBlood.cs
Content.Server/StationEvents/Components/GasLeakRuleComponent.cs
Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/GasArtifactComponent.cs
Content.Server/Xenoarchaeology/XenoArtifacts/Triggers/Components/ArtifactGasTriggerComponent.cs
Content.Shared/Atmos/Atmospherics.cs
Content.Shared/Atmos/Piping/Unary/Components/SharedVentScrubberComponent.cs
Resources/Locale/en-US/guidebook/chemistry/conditions.ftl
Resources/Locale/en-US/guidebook/chemistry/effects.ftl
Resources/Locale/en-US/reagents/meta/narcotics.ftl
Resources/Prototypes/Atmospherics/gases.yml
Resources/Prototypes/Atmospherics/reactions.yml
Resources/Prototypes/Entities/Structures/Specific/Atmospherics/sensor.yml
Resources/Prototypes/Entities/Structures/Specific/Atmospherics/vox.yml
Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
Resources/Prototypes/Reagents/gases.yml
Resources/Prototypes/Reagents/narcotics.yml

Breathing nitrium now puts nitrosyl plasmide into the users blood. Presence of nitrosyl plasmide in a users blood prevents the user from falling asleep to other inhaled gases. Nitrosyl plasmide also greatly reduces stuns and time spent knocked down. 
I've also included some notation to earlier code so that it's easier to find by just searching /tg/ gases. Any changes I've made to existing files should now be noted. 
Parity with original concept of nitrium
Added a reagent effect and condition. The effect puts a reagent directly into the users bloodstream. This was done because the current AdjustReagent effect does not work with inhaled gases. The condition checks for the quantity of a reagent in a users blood, and returns true or false depending on the maximum and minimum values passed to …

add nitrosyl plasmide

---

Resources/Prototypes/secret_weights.yml

enabled the blob mode
Currently only the blob ghost role could spawn past 50 minutes into a round, and the blob mode with roundstart blobs was never added to the secret pool
**Changelog**
:cl: shibechef
- fix: Enabled blob gamemode.

enabled blob mode

---

Resources/ServerInfo/Guidebook/Mobs/IPCs.xml

There was no newline before the "Recharging an IPC" sub heading in the guidebook entry, causing the header to not be rendered and just be the `##` markdown things.
Small typo, makes it more readable.
Added one blank line before the recharging IPC header in guidebook entry. So that it is registered as proper bmarkdown.
N/A.
**Changelog**
N/A

Fix newline in IPC guidebook

---

Resources/Prototypes/Reagents/gases.yml

~~Looks like I did the oopsie this time, and accidentally made Yowies still not able to breath. I think I must have fat fingered something after testing.~~ Turns out is was a later commit, easy mistake to make but in this case there should not be a shouldHave: false. 
Anyway, time to let Yowies breath again!
:cl:
- fix: Yowies can now breathe easy. Literally.

Help Yowies breath easy

---

Content.Server/Mech/Systems/MechSystem.cs
Content.Server/Power/EntitySystems/BatterySystem.cs
Content.Server/Stunnable/Systems/StunbatonSystem.cs
Content.Server/Weapons/Melee/EnergySword/EnergySwordSystem.cs
Content.Server/_Goobstation/Emp/EmpStunSystem.cs
Content.Server/_White/Blocking/RechargeableBlockingSystem.cs
Content.Shared/_Goobstation/Emp/EmpDisableSystem.cs
Resources/Locale/en-US/_Goobstation/emp/emp.ftl
Resources/Locale/en-US/store/uplink-catalog.ftl
Resources/Prototypes/Entities/Clothing/Masks/masks.yml
Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Resources/Prototypes/_Goobstation/Loadouts/role_loadouts.yml
Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml

Replaced bso's atreides with ~enforcer~ mk58, bso doesn't deserve atreides.
Nerfed n1984 (and mateba) firerate slightly.
Emp implant now only drains 360 energy, but emp now stuns borgs and IPCs and disables energy weapons temporarily (including eswords).
Fixed some mech and emp related bugs.
Infinite EMP implant draining batteries fully is not good.
**Changelog**
:cl: Aviu
- add: EMP implanter energy drain heavily reduced, but it still disables energy weapons for 10 seconds.
- add: IPCs and borgs are now stunned when affected by EMP.
- add: Eswords can be EMPd now.
- tweak: Removed atreides from bso, replaced it with mk58.
- tweak: Bso now has security survival box.
- tweak: Energy pen is not as good at delimbing anymore.

Some nerfs

---

Content.Server/Antag/AntagSelectionSystem.cs

Fixed #1261.
Antags are rolled before jobs so they aren't added to `SelectedSessions`, instead they are added to `PendingAntags`. So checking if `SelectedSessions` count is greater or equal than target count always failed which resulted in quadruple amount of antags being selected.
**Changelog**
:cl: Aviu
- fix: Fix absurd amount of roundstart antags being selected.

Fix absurd amount of antags being selected roundstart

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/light_rifle.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/magnum.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml

Makes all incendiary rounds do less direct burn damage but more fire stacks. Previously every bullet did .25 fire stacks, now they do .50. Incendiary bullets now directly do ~1/3th the direct damage of a normal round, instead of the full damage of a normal bullet. These changes should let blob and other victims not get literally incinerated without counterplay, while also making incendiaries less like heat bullets and more like incendiary bullets. 
Currently incendiary rounds do identical damage to normal rounds but in burn and don't really ignite the target. They are basically laser rifles in a bullet instead of ignition rounds. This is a problem specifically when paired with blobs, and pretty overpowered against most threats.
Blobs currently get absolutely swept when incendiaries come …

Incendiary rework

---

Resources/Prototypes/Entities/Mobs/Species/gingerbread.yml

Changed Gingerbread's damage from water from Genetic damage to Heat damage.
It says in the guidebook Gingerbread species take 3x as much damage from water as slime people, but they were being dealt Genetic damage, which they're immune to. I considered making it 4x as much damage, because a max splash of 20 water would still only be 8 damage, but they already take 1.5x Blunt damage, so robusting them is easy enough.
I changed the touch reaction of water to be Heat damage instead of Genetic damage in gingerbread.yml
**Changelog**
:cl:
- fix: Fixed Gingerbread not taking damage from being splashed with water

Fixed Gingerbread not taking damage from water

---

Content.Server/Entry/EntryPoint.cs

title.
Goobcoins were never saved on `Update` and `Shutdown` because these methods were never invoked.
**Changelog**
:cl: Aviu
- fix: Fix goob coins not being saved on server shutdown.

Fix currency manager Update and Shutdown never being invoked

---

Resources/Prototypes/_Goobstation/GameRules/roundstart.yml

I just slightly rebalanced ling spawns. Decreased 7 lings to 4.
Currently the ling meta has shifted to working together and I've seen them take over the station multiple times effortlessly. It's really not that fun since they are designed to round remove you and it's just getting boring.
**Changelog**
:cl:
- tweak: The maximum ling count has been decreased from 7 to 4.

Decrease Changeling Spawn Amount

---

Content.Server/Antag/AntagSelectionSystem.cs

No longer will nuke ops rule spawn huge amount of nukie ghost roles (probably).
**Changelog**
:cl: Aviu
- fix: Possible fix for nuke ops rule spawning a lot of nukie ghost roles.

Fix nukeops spawning ghost roles

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

so borgs can decapitate people or heal limb damage
1 line patch is CC0-1.0
**Changelog**
:cl:
- fix: Fixed borgs not being able to target limbs.

give borgs targeting

---

Content.Shared/Administration/AdminFlags.cs
Resources/engineCommandPerms.yml

This adds a Permissions flag (in the Permissions Panel) for "Full Admin" that gives Admins 'Self' and 'Entitites' command permissions.
Because not having it sucks butt.
I added another element to the enumerator for AdminFlags and then added a custom flag matching the name.
If anything breaks, it's the AdminFlags fault.
**Changelog**
:cl:
ADMIN:
- add: Added 'FullAdmin' Permissions to give 'Self' and 'Entities' permissions to Game Admins and higher.

[Admin] Add Full-Admin Permissions Category

---

Resources/engineCommandPerms.yml

I forgot nearby was a perm. It's added.

Add 'nearby' to FullAdmin perms.

---

Content.Server/Damage/Components/DamageUserOnTriggerComponent.cs
Content.Server/Damage/Systems/DamageUserOnTriggerSystem.cs

mousetraps, glass shards and d4s now target your feet
@gluesniffler backport to ee for me pls :trollface: patch is CC0-1.0
it makes sense
DamageUserOnTrigger has TargetPart field, set to Feet by default. can be removed or set to anything else in yml
no
**Changelog**
:mouse: exclaims, "Piep!"
:cl:
- tweak: Mousetraps now damage the feet specifically.

make mousetraps damage your feet

---

Resources/Prototypes/Entities/Objects/Misc/dat_fukken_disk.yml
Resources/Prototypes/Entities/Structures/Machines/nuke.yml

Both the nuclear fission explosive and the nuclear authentication disk are now immune to being ashed by Supermatter.
On Goob 1, round 9049 lasted for 2 hours because there was a stupid amount of blobs, and nukies also. However previously in the round an engi had ashed the nuke with the SM. So the nuke could never be detonated. This softlocked the round and most people got very fed up.
Added the SupermatterImmune component to the NuclearBomb and the NukeDisk.
**Changelog**
:cl:
- tweak: The nuke and nuke disk are now immune to Supermatter.

Make nuke and nuke disk SM immune

---

Resources/Prototypes/Guidebook/species.yml
Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
Resources/ServerInfo/Guidebook/Mobs/Species.xml

Added Onis to the guidebook, since they existed in the files but were missing in game.
Onis exist in the character creator, but them not having a guidebook page makes them feel a little "secret". This PR fixes that issue.
Added Onis to `Resources/Prototypes/Guidebook/species.yml`. Edited existing Oni guidebook snippet to exclude diet (since there's no differences), and removed section about prying open doors since we have instaprying in game rn. Also rearranged Species.xml to get rid of duplicate Vox entry, and sorted it alphabetically.
Should be none
**Changelog**
🆑 SX-7
- add: Added oni entry to guidebook

Add Onis to guidebook

---

Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml

now parents off space mobs, doesn't need oxygen or pressure anymore
everything else the same
"last resort" when space kills you in 3 seconds
tested, trust
**Changelog**
:cl:
- tweak: Changeling headslugs now take no airloss or spacing damage.

headslugs survive in space

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Bow/bow.yml

Give bow ClumsyProof
Makes monkeys (and anything clumsy) able to shoot bows
1 line change
i cant be bothered to record a monkey hunting mice montage
**Changelog**
:cl:
- add: Monkeys (or anything else clumsy) can now shoot bows!

Bow is now ClumsyProof

---

Content.Server/_DeltaV/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs
Content.Server/_DeltaV/NanoChat/NanoChatSystem.cs
Content.Shared/_DeltaV/NanoChat/NanoChatCardComponent.cs

Fixed NanoChat message notifications not showing up in situations where you'd definitely expect them to occur.
Now, for a chat to not send a notification upon a new message, three conditions need to be fulfilled:
- You don't have the chat muted
- Your PDA UI is open
- You have NanoChat as your open program
- Your currently-selected chat is the aforementioned chat
Notifications should **always** occur when you don't have the chat open on your screen, because otherwise you might not even know that you got a new message.
Adds a new field to `NanoChatCardComponent` called `PdaUid` that stores a reference to the PDA the NanoChat card is inserted in. The field is updated whenever the card is inserted or removed from a PDA.
Importantly, PdaUid also removes the need for an `EntityQueryEnumerator` …

NanoChat Notification Fix

---

Content.Server/EntityEffects/Effects/StatusEffects/GenericStatusEffect.cs
Resources/Locale/en-US/guidebook/chemistry/effects.ftl

Guidebook now properly informs whether a chem is accumulating or not.
Guidebook was wrong and it was annoying, also highly misinformative in regards to around a dozen chemicals. Accumulation is really important in regards to microdosing, and gauging drug's efficiency, yet true information was obscured from most players.
Function creating reagent description now uses the `Refresh` variable in addition to `Type` in order to determine true behaviour of a chem, and the locstring has an additional switch statement in order to use it. Previously `StatusEffectMetabolismType.Add` combined with `Refresh=True` was indistinguishable from `StatusEffectMetabolismType.Set` on the user end, yet it resulted in a different (and misleading) guidebook entries being generated. Now that's no longer the case. …

Chem guidebook accumulation display fix

---

Content.Server/_Goobstation/Emoting/FartSystem.cs
Content.Shared/_Goobstation/Emoting/FartComponent.cs

Updated the MolesAmmoniaPerFart DataField of FartComponent to not be a const.
The YAML Linter was very upset that there was a static data field. 
Took away the const keyword and updated references to it accordingly.
- [ x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
:cl:
- tweak: updated FartComponent.MolesAmmoniaPerFart to not be const. We have appeased the YAML Linter...for now.

Fixing FartComponent references to appease the YAML linter.

---

Resources/Prototypes/_Goobstation/Entities/Objects/Materials/materials.yml

Fixes a regression introduced by the merges of PRs #569 #759 and #900
Bluespace crystals are mineable ores and should be allowed to be picked up by ore bags
Re-added the Ore and Ingot tags so the bluespace crystals are picked up by ore bags and are insertable in lathes once again.
**Changelog**
:cl:
- fix: Fixed a regression that prevented Bluespace Crystals from being picked up by ore bags.

Make Bluespace Crystals Ore Baggable Again

---

Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Warden hard suit now has 60% resistance in both blunt and pierce, but it's pierce resistance has been lowered to 30% from 40%.
Along with this, the helmet now has 20% resistance in blunt & pierce. Hopefully this changes will match the riot suit.
The description of the suit specifically states it as being a modified riot suit despite having worse stats than an actual riot suit, and having high pierce resist. Also, I saw this in a bounty and thought it'd make Wardens hard suit slightly different than a security hard suit with higher stats.
Slight stat-tweaks.
- [ X ] I have added media to this PR or it does not …

Warden hardsuit buff

---

Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml

reinstates https://github.com/space-wizards/space-station-14/pull/21896, makes fridges survive nuke
lore-accurate fridge
pretty much no way to abuse this, you aren't dragging a fridge into combat and if you are, you aren't going to be able to use it tactically
see mentioned PR
**Changelog**
:cl:
- tweak: Closet freezers now have 99% explosive resistance, which lets them survive nukes.

give fridge 99% explo res

---

Content.Server/_EinsteinEngines/Flight/FlightSystem.cs

Harpies are now capable of performing their flight do-after while moving.
No longer will I awkwardly pause in halls, start a do-after, then get interrupted because I almost lost sight of the person I was walking with.
I just removed break on movement from the do-after (thanks mocho)
**Changelog**

Harpies can fly while moving.

---

Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs

reduced space damage to limbs to 20%
so when you get 200 damage from space the limbs only get 40 (if your limbs are already badly damaged they might get severed still)
cold damage is unaffected
fixes #1365
should be changed to 0% if body parts get clothing coverage + individual part barotrauma so parts handle their own damage and hardsuits without helmet protect everything but the head
1 line ops
**Changelog**
:cl:
- tweak: Reduced spacing damage to limbs.

prevent space nuggetting

---

Content.Shared/_Goobstation/CCVars/CCVars.Goob.cs

its in the title stupid
5 seconds is really low
**Changelog**
:cl:
- tweak: Increased the default threshold for a ragequit to 30 seconds from 5.

Increase Default Ragequit Threshold to 30 Seconds

---

Resources/Prototypes/_Goobstation/Reagents/Materials/materials.yml

Changed the value of making bluespace crystals to double the value of the raw materials instead of roughly 50x the value of the raw materials.
Being able to turn 235 spesos into 12,500 spesos means that salvage + protolathe = infinite money. It makes bounties pointless, because a little bit of mining sets you up with spesos for life. I considered making the value exactly the same as the input, but I figure making bluespace crystals still takes a lot of time and a protolathe. If the maintainers would rather make the input and output the same to put this exploit to rest once and for all, change the price in the file to .5875
I changed the price of a bluespace crystal from 3000 spesos to 470 spesos.
**Changelog**
:cl:
- tweak: Making bluespace crystals doubles the value of the materials …

making bluespace crystals doubles the value instead of 50xing the value

---

Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml

Fixes being unable to access Winter Coat storage (inventory never opened)
was borked, now fixed
Flipped the order of the parents for the `ClothingOuterWinterCoatToggleable` entity. I'm guessing some scuffed inheritance was breaking the ability to use the coat storage, and since all except the base winter coat were children of this entity, they were broken.
I also removed some redundant `Item` components because they had no actual values assigned to them and were already being inherited by their parent entities.
**Changelog**
:cl:
- fix: Fixed all the Winter Coats storage being inaccessible. Now you can take things back out that you stored inside.

Fix Winter Coat Storage

---

Resources/Locale/en-US/_Goobstation/guidebook/guides.ftl
Resources/Prototypes/_Goobstation/Guidebook/sop.yml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/AlertLevels/AlertLevelsSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Command/HeadOfSecuritySOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Command/NanotrasenRepSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Command/ResearchDirectorSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Science/RoboticistSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Science/ScientistSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Security/DetectiveSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Security/OfficerCadetSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Security/WardenSOP.xml
Resources/ServerInfo/_Goobstation/Guidebook/SoP/StandardProcedures/EarlyEvacuationSOP.xml

Updated Security to account for shift-start weaponry. Added information to Alert Levels and how they should be treated (in the job entries AND in the Alert Levels. Fixed up the priority of the children and removed the underscores. **ADDED EARLY EVACUATION INFORMATION!**
I hate people that early evac for shits n giggles as command.
**Changelog**
:cl:
- add: Added Early Evacuation Procedures to SOP.
- add: Added clarification for how Alert Levels are treated in SOP.

Add Early Evac, Clean Up Security, and Clarify Alert Levels in SOP

---

Content.Server/_Goobstation/PlayerListener/DormNotifier.cs
Content.Server/_Goobstation/PlayerListener/DormNotifierComponent.cs
Content.Server/_Goobstation/PlayerListener/DormNotifierMarkerComponent.cs
Content.Shared/_Goobstation/CCVars/CCVars.Goob.cs
Resources/Locale/en-US/_Goobstation/playerlistener/dorm.ftl
Resources/Prototypes/_Goobstation/PlayerListener/Marker.yml

Adds a marker, "Dorm Activity Marker", which checks for humanoid player entities in X tiles from it, after which starts a timer. When the timer finishes - checks if they're still near the marker, if they are - notify everyone on server.
The conditions to trigger the message are as follows:
1. Mobs in proximity must be humanoid
2. X(>1) amount of humanoids are in a Y distance of tiles away from a marker
3. At least two humanoids are currently players
4. None of the humanoid mobs are dead, crit, AFK or disconnected
Additionally, if any of the condemned is nude, as in have a jumpsuit slot which is empty - it will also reveal their name, piercing identity blocking.
Markers will have to be mapped in a different PR, but can be added dynamically in a round.
Markers have two VV'able fields - …

Paradormal Activity Early Warning System

---

Content.Server/Discord/WebhookPayload.cs
Content.Server/_Goobstation/PlayerListener/RageQuitNotifySystem.Discord.cs
Content.Server/_Goobstation/PlayerListener/RageQuitNotifySystem.cs
Content.Shared/_Goobstation/CCVars/CCVars.Goob.cs
Resources/Locale/en-US/_Goobstation/playerlistener/ragequit.ftl

OOC messages are not used in the relay, send them to a webhook instead
Renames cvars so that they could be properly set in the server config file.
Solves for users connecting and disconnecting multiple times in a 30 second timespan.
:cl:
- tweak: ragequit messages can now be sent to a discord webhook

Discord notif for ragequits, solve for constant reconnection

---

Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs
Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl

Makes it so that if you would go into crit by using jaunt, it won't let you.
It would suck if you didn't read the whole description of the ability or forgot and accidentally crit yourself. I think a more ideal solution would be to make it so that it just requires confirmation so you still could do it (which would be great for if you have a friend where you're going, or if you injected yourself with enough chems to heal you up before), but this is a decent solution for now.
I've tested that it still works if you aren't low on health and all of that.
**Changelog**
:cl:
- tweak: Ashen Jaunt won't let you use it if it would crit you.

Jaunt Idiotproofing

---

Content.Server/Body/Systems/BodySystem.cs
Content.Shared/Body/Part/BodyPartComponent.cs
Content.Shared/Body/Systems/SharedBodySystem.Parts.cs

title
applies to damage-caused severing (which probably wont matter as youll already be bleeding) and surgical amputation
bloodloss damage makes no sense when its heavy arterial **bleeding**
so now it does that, 6 bleeding stacks for limbs and 10 (max) for the head
now when delimbing people you need gauze to keep them from bleeding out, crazy
simple enough
evil surgery and evil execution vs urists
no
**Changelog**
:cl:
- tweak: Losing a limb makes you bleed profusely instead of dealing bloodloss damage.

make limb severing bleed instead of bloodloss damage

---

Resources/Prototypes/_Goobstation/Blob/blob_mobs.yml

Blobbernauts now have a 10 second raffle like carps instead of 25 seconds
Blobbernaut npcs tend to walk off blob tiles and die before the raffle ends, or sometimes just walks into the abyss of space

Shorten blobbernaut raffle timer

---

Resources/Prototypes/Roles/Jobs/Security/warden.yml

Warden now spawns with their unique headset equipped.
Reported as a bug.
Changed 
"ClothingHeadsetAltSecurity" -> "ClothingHeadsetAltWarden"
**Changelog**
:cl:
- tweak: Warden now spawns with their unique headset equipped.

Edited warden to spawn with their own unique headset.

---

Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs

The ashen path's nightwatcher's rebirth now engulfs people that are already caught on fire, like originally intended. 
The in game description says "a spell that burns all nearby heathens who are currently on fire, healing you for every victim afflicted". It seems to have done the same thing in ss13. Prior to this change it actually engulfed everyone not on fire, and anyone already ignited was safe, which is the opposite of what it was supposed to do. It was also very overpowered as you could literally kill everyone on screen in less than a second by tapping a button, and solo the station with this ability alone. Its still very powerful because the blade and the fireball ignite people, and it still heals a great amount, but people no longer instantly die while clueless. 
Also minorly …

Fix nightwatcher's rebirth

---

Content.Server/Projectiles/ProjectileSystem.cs
Content.Shared/Projectiles/ProjectileComponent.cs
Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_arrows.yml

- adds support for having penetrating projectiles not penetrate certain entities
- make hardlight bow x-ray arrows not penetrate blob tiles (hits first and despawns)
- makes emitter bolts reflect as energy shots
- raise reflective tile reflect 60%->90%
x-ray arrow change:
- without this, x-ray arrows penetrate and kill all normal blob tiles in a line, and kill strong/reflective tiles in 2 hits, and core in 4 hits
emitter bolt change is basically just a fix
reflect change:
- even with the x-ray change, hardlight bow arrows oneshot or 2-shot blob tiles, so it's just an infinite ammo long-range blob destroyer dealing heat damage which blob below delta size simply can't counter; therefore
- reflective tiles have 100 hp as opposed to strong tiles' 150hp, but only have 60% reflect, which is …

make hardlight bow not stupid op against blob

---

Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
Content.Server/StationEvents/Events/VentCrittersRule.cs
Resources/Locale/en-US/deltav/station-events/events/vent-critters.ftl
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/GameRules/pests.yml

From Delta-V: (https://github.com/DeltaV-Station/Delta-v/pull/2495)
actually didnt take that long didnt need the nuking pr at all :trollface: :
this makes vent critters better for everyone, sec and crew alike:
- 1 vent is picked for all mobs to spawn from
- the station gets 30 seconds advance warning before they spawn, giving crew time to run away and sec to arm up
- number of critters scales with player count so lowpop doesnt get as many as highpop
- false alarm, its just mice!!!
current numbers can go up to like 9 slimes on highpop, requiring good sec coordination to deal with
makes vent critters less ass and more fair to new players that dont have a spear ready to not get killed by simplemobs now that you can run away, sec actually has something to do instead of "oops the crew killed …

[PORT] Vent Critters Rework from Delta-V

---

Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml

reduced lockout threshold to 30kpa which is what deltav uses and works well
every station becoming oasis is bad
**Changelog**
:cl:
- tweak: Fixed air alarms being bad.

make air vents not shit

---

Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/Roles/Jobs/CentComm/cburn.yml
Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
Resources/Prototypes/Roles/Jobs/CentComm/official.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/_Goobstation/Roles/GhostRoles/Fun/hecu.yml

adds NTR and BSO access to
all ERT roles, HECU, centcomm official, CBURN, deathsquad roles and future agent and admin id card
fixes #1341 
**Changelog**
:cl:
- fix: All CentComm cards/roles now have NTR and BSO access aswell.

Bso ntr centcomm role access

---

Content.Server/_Goobstation/Speech/Components/GlorpAccentComponent.cs
Content.Server/_Goobstation/Speech/EntitySystems/GlorpAccentSystem.cs
Resources/Prototypes/_Shitmed/Entities/Mobs/Species/abductor.yml

Adds Glorp accent to the Abductor.
Because it would be really funny for the abductor to yell at people in an incomprehensible language, with very certain words coming through like "Skill issue" plus more that can be added.
Just adds the Glorp Accent system and component, and modifies the abductor YAML to replace muted with the glorp accent.
Replaces every word you say with a psuedorandomized table of glorp-like words, with a few specific words in a white list which are surrounded in quotes, also randomly adds "glorpshit" and "glupshitto" for more funni comedy
https://github.com/user-attachments/assets/4c05c483-5734-4f38-ad5c-f9ea4f3fe11b
**Changelog**
:cl: Koi
- tweak: The Abductor now speaks in a near-incomprehensible Glorp accent! But it appears he has picked up on a few colloquial …

Glorp Accent for Abductor

---

Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs
Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Knowledge.cs

Ritual of knowledge now checks if entity is in container.
Nightwatcher's rebirth now deals (- 10 - PathStage) damage to you for each burning entity, instead of dealing (your current damage - 10 - PathStage) damage to you for each burning entity, which can easily lead to gibbing or delimbing.
**Changelog**
:cl: MJ Sailor
- fix: Nightwatcher's rebirth now won't delimb or gib you.
- fix: Fixed ritual of knowledge stealing your clothes and organs.

Fix ritual of knowledge and nightwatcher's rebirth

---

Content.Server/_Goobstation/Supermatter/Systems/SupermatterSystem.cs

Supermatter no longer magically removes 15% of the gas mix from the chamber every second.
Pretty trivial bugfix, since it seems to be an unintended behaviour. It'll make things like Atlas SM work properly out-of-the-box (as I believe is intended), without need to hook up the distro to keep it topped off. Should decrease the likelihood of SM delamming itself 30 minutes in because someone set it up with a single can.
In SM code, `ProcessAtmos` removes gases from the mix, modifies them, and merges them back. `HandleDamage` removed gases, but didn't return them, resulting in 15% of gases being removed from the SM every second (since `sm.GasEfficiency` is `0.15f`). This fix simply mirrors code from `ProcessAtmos` in `HandleDamage`, and fixes the unclear and possibly unintended behaviour.
Atlas …

Made SM not suck (gas) (out of the chamber)

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Removes movespeed penalty from elite suit ~~and makes it a bit cheaper~~. Only movespeed penalty removed.
Bounty.
Also it's as expensive as jugsuit, offers less protection than blood-red against most common damage types, and "less slowdown" is a lie cuz noone walks. In conclusion: trash, and why you'd buy this, except for one in a million singuloose strat (read: never).
Literally like 2 lines in yaml changed, it's faster to read the code than this PR
**Changelog**
:cl:
- tweak: Increased speed of elite syndicate suit by 11%

Unnerf elite syndie suit

---

Resources/Locale/en-US/_Goobstation/flavors/flavor-profiles.ftl
Resources/Locale/en-US/_Goobstation/reagents/meta/biological.ftl
Resources/Locale/en-US/_Goobstation/reagents/meta/physical-desc.ftl
Resources/Prototypes/_Goobstation/Flavors/flavors.yml
Resources/Prototypes/_Goobstation/Reagents/biological.yml
Resources/Prototypes/_Shitmed/Entities/Mobs/Species/abductor.yml

Adds a unique blood type for abductors.
Because I felt that an alien species based off of the grey aliens bleeding the same blood as humans was weird.
Also, it allows you to tell which blood is abductor blood easily because it's purple.
In the future, this blood type could have some unique stuff to it, but right now it's just recolored insect blood :p
Changed the blood type from default to AlienBlood
Created new biological reagent folder.
Added new alienblood reagent into the folder.
**Changelog**
:cl:
- add: Abductors now have a …

Abductor Unique Blood

---

Content.Server/Station/Systems/StationSpawningSystem.cs
Resources/Locale/en-US/_Goobstation/preferences/ui/humanoid-profile-editor.ftl

Preferred Cyborg name is now applied to the Station AI.
Customisability, there is presently no way to customise your AI name.
Add station AI check to the borg name adder, while making sure the AI doesnt get a designator.
**Changelog**
:cl:
- add: Preferred borg name is now applied to Station AIs.

Apply preferred borg name to Station AI

---

Content.Server/Power/Components/BatteryComponent.cs
Resources/Prototypes/Entities/Structures/Power/smes.yml

Tripled Joule price, resulting in a normal, filled SMES to be valued at about 5.1k.
Updated SMES names to match power value.
Increased Adv. SMES capacity to align with #402.
Makes power selling more viable.
Adv. SMES is no longer an SMES clone that costs more.
Changed numbers.
**Changelog**
:cl:
- fix: Adv. SMES capacity buffed (2x)
- tweak: Increased sell price of filled SMES

SMES Fix and Value Increase

---

Content.Client/Stealth/StealthSystem.cs
Content.Shared/Stealth/Components/StealthComponent.cs
Content.Shared/Stealth/Components/StealthOnMoveComponent.cs
Content.Shared/Stealth/SharedStealthSystem.cs
Resources/Prototypes/Anomaly/behaviours.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml
Resources/Prototypes/XenoArch/Effects/normal_effects.yml

makes stealth things capable of *full* full cloak while stationary, affects every stealth thing (including ninja) except ones mentioned below
note: this is all configurable, i just set the defaults to let everything go full stealth if stationary (no full stealth if moving)
does not affect: anomalies, artifacts
currently everything stealth is just useless because you get spotted instantly and people hate it, this makes them actually viable but not too strong
if this is too evil can just configure only certain prototypes to (not) have this, it's all configurable
"but this will make stealth op" no it won't, current options with stealth:
you use stealth against an unrobust player: you win both with and without stealth
you use stealth against a robust player: you lose both with (they will see …

fix stealth

---

Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/_Goobstation/GameRules/Dynamic/dynamic.yml

Dynamic cannot be voted for, and origin cannot be rolled
Dynamic has been broken for over a month now, but can still be voted for which leads to people being funny and stalling the next round repeatedly. Origin also hasn't been able to load for some time now.

Removing broken map and mode from pools (temporarily)

---

Content.Shared/_Goobstation/Heretic/Systems/HereticClothingSystem.cs
Resources/Prototypes/_Goobstation/Heretic/Entities/Clothing/Neck/specific.yml
Resources/Prototypes/_Goobstation/Heretic/Entities/Clothing/OuterClothing/armor.yml

Now you can't valid a heretic by equipping heretic gear on them. Removed the restriction of wearing amber focus and heretic armor by non-heretics, since it's kinda silly, they still can't wear eldritch medallion because it gives thermals. Also ghouls can wear ashen eyes medallions.
**Changelog**
:cl: Aviu
- fix; Non-heretics can't equip heretic gear on heretics anymore (if they can't wear it themselves).
- fix: Ghouls can wear heretic medallion.
- tweak: Everyone can wear heretic gear once again with an exception of eldritch medallion.

Fix heretic gear

---

Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Melee/wonderprod.yml

can no longer rightclick and steal wonder batong
this is actually kind of a fix (see tech details)
prevent rightclick for 25% chance of abductor defeat before it becomes meta and entire playerbase does it so can't play abductor without getting rightclicked anymore
i also noticed it has the RestrictByUserTag component which is supposed to make the batong only usable by abductor, but it doesn't work, so this kinda works instead
trust
**Changelog**
:cl:
- tweak: Wonderprod can no longer be disarmed.

undisarmable wonderprod

---

Resources/Locale/en-US/_Goobstation/ghost/ghost-role-component.ftl
Resources/Locale/en-US/store/uplink-catalog.ftl
Resources/Prototypes/Entities/Objects/Weapons/Bombs/plastic.yml
Resources/Prototypes/Voice/speech_emotes.yml
Resources/Prototypes/_Goobstation/Voice/speech_emote_sounds.yml

- the syndicate has joined the AI bubble
- c4 now a guaranteed ghost role
- has syndicate radio
- can emote to c4 beep
- basically syndicate pai
Argument for Sentient C4 in Space Station 14
The introduction of sentient C4 in Space Station 14 would revolutionize gameplay, adding layers of complexity, humor, and ethical dilemmas that align perfectly with the game’s chaotic and unpredictable nature. Here’s why:
1. Enhanced Gameplay Dynamics: Sentient C4 could introduce a new layer of strategy. Imagine C4 that refuses to detonate unless it’s convinced of the mission’s worthiness, or that negotiates with players before exploding. This would force players to think creatively, whether through persuasion, bribery, or threats, adding depth to sabotage and defense
2. Comedic Potential: A sentient …

ai-powered c4

---

Resources/Prototypes/Entities/Mobs/Player/silicon.yml

now borg jobs properly spawn as posibrains and not MMIs
you are now properly strong steel instead of weak flesh, this is how it was supposed to be, selectable borg change probably broke it
trust
**Changelog**
:cl:
- fix: Borg jobs now properly start with positronic brains.

fix borg jobs being MMIs

---

Resources/Locale/en-US/_Goobstation/emotes.ftl
Resources/Prototypes/_Goobstation/Actions/emotes.yml

Re-added spin emote, it won't show in the emote wheel though.
So I can do spin-flip.
Invalid category so emote wheel ignores it.
**Changelog**
:cl: Aviu
- add: Spin emote is back. Though it's not available in the emote wheel, you have to bind it or type it manually.

Bring back spin emote

---

Resources/Prototypes/_Goobstation/Heretic/Entities/Mobs/NPC/polymorph.yml

- makes it actually take no fire damage like it says
- fixes slowdown on any amount of damage
- no more permableed
- doesn't gib on 400 blunt anymore (it has 1500 hp)
- attacks slightly faster
- huggable
flesh ascension is currently kinda bad since you lose all abilities and gear, and even despite that it still dies to man with gun, this makes it worth it
also the ascension description straight up lies to you about a few things
all tested, works
**Changelog**
:cl:
- fix: Flesh ascension no longer takes temperature damage, slows down on a small amount of damage, or gibs on 400 blunt.
- tweak: Flesh ascension now attacks slightly faster, recovers quickly from bleed, and is huggable

make flesh ascension good

---

Resources/Prototypes/Entities/Objects/Misc/pen.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Recipes/Lathes/tools.yml

allows autolathe to print pens for 0.25 steel each
why could they not before
tested, works
**Changelog**
:cl:
- add: You can now print pens at an autolathe.

pen recipe in autolathe

---

Resources/Maps/_Goobstation/Nonstations/nukieplanet-honkops.yml
Resources/Maps/_Goobstation/Nonstations/nukieplanet.yml

Adds: a biomass extractor for the biomass fabricator, a linked lever for the industrial reagent grinder, the hydroponics trays no longer start unusable, and there is now just enough power for both the hellfire burner and freezer to run (previously not enough for EITHER). Also adds it on the honkops map.
It's cool having nukies get more/easier access to sandbox stuff, and it's already discouraged by nukies having a very limited time to do so.

Nukie base QOL

---

Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs

Test were checking for SiliconComponent (for IPCs) after checking RespiratorComponent (IPCs don't have it)

Fix NukeOps Test

---

Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Resources/Prototypes/_Goobstation/Catalog/Fills/Crates/syndicate.yml
Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml

see media
also makes mosin 4x2 in inventory
only 5 ushankas to not spam entities too much but if told it's fine i'll make it 10
funny
balanced since you aren't really killing anyone with mosins so them being this cheap is fine
the bonus items are just for extra funny
mosin being 4x4 was just bad should've been 4x2
**Changelog**
:cl:
- add: Syndicate bulk mosin crate.
- tweak: Mosins are now 4x2.

bulk mosin crate

---

Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml

added built-in Digital Audio Workstation (DaW) to IPCs hotbar, that allows them to play music like harpys without holding anything
...for some reason...
Money duh
there are some minor problems, but fixing them will take way too long, and ive already spent a whole day on this thing fixing other stuff...
**Changelog**
:cl:
- add: Added a built-in DaW in IPCs.

[bounty] DaW to IPCs hotbar x2

---

Content.Server/Antag/AntagSelectionSystem.cs
Content.Server/Station/Systems/StationJobsSystem.Roundstart.cs
Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml

You no longer always become an assistant if you roll and have "stay in lobby" preferred option. This way you lose your antag roll but you can't abuse it by rolling antag with people readied up and then rolling again as a latejoiner.
Changed nukies and wiz roll behaivor to PrePlayerSpawn from BeforeJobs. Because, for example, if a person rolls wiz and has "stay in lobby" option, wiz wouldn't spawn most likely if they roll it but are not assigned to any job. It should work as before for wiz and nukies.
Tested wiz and traitor game presets while having no jobs priorities enabled and all antags enabled and "stay in lobby" option selected. Spawned as wizard successfully but didn't spawn as a traitor, as intended.
Current system can be abused.
Don't spawn a person as assistant if they roll and …

Fix antagrolling

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Wizard/mirror.yml

Tajaran not accessible in wiz mirror. Also felinids are availible on emag lathe.
Was 1am so I forgor while adjusting things for wiz
Like 2 line changes

Tajaran hotfix

---

Resources/Prototypes/Entities/Mobs/NPCs/miscellaneous.yml

removes passive damage from killer tomatos
poll on discord was highly in favor of doing this
readded fun
make killer tomatos not useless
if sec doesn't see botanist stockpiling them it's sec skill issue and they should die
also we have AI now so even more so
if this turns out bad later, i'll instead make their lifetime scale off potency with a new PR
**Changelog**
:cl:
- tweak: Killer tomatoes no longer take damage over time.

untime killer tomato life

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml

Gave captains sabre a 30% reflect chance again.
Lets compare.
Energy Sword
- Easily accessible by any traitor, costs 37tc.
- Deals 30 damage a hit, increased sever chance.
- 50% energy reflect chance, small amount for other projectiles
- Fits into a pocket slot/storage implant, easily concealable
Captains Sabre
- Elite weapon, only one spawns for the MOST important person on the station.
- Deals 17 damage, less than a syndicate toolbox.
- No reflect chance, useless against anyone with a firearm that isn't a pistol.
- Either takes your ENTIRE belt slot, or a 4x2 in your inventory.
- Recieves nerf after fucking NERF
I don't think I have to elaborate further.
YAML. Literally three lines
N/A
- [ X ] I have read and am following the [Pull Request and Changelog …

Sabre buff (again)

---

Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
Resources/ServerInfo/_Goobstation/Guidebook/Medical/Medicalpatches.xml

Medical patches now have a better guidebook entry and different descriptions.
The previous guidebook was inaccurate and did not cover content comprehensively enough, and the descriptions of the patches were a bit jarring to look at and not very helpful or informative. This improves both of those.
Changed a yml and an xml. I also removed the out-of-place capital letters in the name of the makeshift patch's crafting recipe.
None that I'm aware of. It was only yml and xml changes.
**Changelog**
:cl:
- tweak: Improved the description and guidebook entry of medical patches.

Improved the formatting of a few things related to patches

---

Content.Benchmarks/MapLoadBenchmark.cs
Resources/Prototypes/Maps/Pools/default.yml

Adds lambda to map pool and benchmarks. It's literally in the files, all ready and polished and ready to go yet it's not in the mappool?? Better than gate.
https://github.com/Goob-Station/Goob-Station/pull/1413
Also if this gets closed I'm making a PR to remove the map from test pools, or perhaps remove it entirely.
**Changelog**
:cl: SX-7
- fix: Lambda is actually in map pool now. Oops!

Adds lambda to map pool and benchmarks

---

Resources/Prototypes/Entities/Objects/Specific/chemistry.yml

Bluespace syringes can now be put in syringe gun ammunition slots.
Given that syringes inject over time (see) [pull #1626](https://github.com/Goob-Station/Goob-Station/pull/1626) and can be pulled out before emptying their contents, I felt this is fine to implement. 
I added the SyringeGunAmmo tag to the bluespace syringe in the yml. This is incredibly simple so I don't see the need to add media to this PR.
N/A
**Changelog**
:cl:
- tweak: Bluespace syringes are now valid ammo for syringe guns.

Bluespace syringes are valid syringe gun ammo

---

Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
Resources/Prototypes/_Shitmed/GameRules/events.yml
Resources/Prototypes/secret_weights.yml

People are sick of the endless blob and abductor tide, people want more wiz + its a fast gamemode. Speedmerge.
**Changelog**
:cl:
- tweak: Upped wizard chance, reduced abductor and blob chance.

SPEEDMERGE THIS!!! Reduce Abductor and blob midround rate, increase wiz start round rate

---

Content.Server/_Shitmed/Antags/Abductor/AbductorSystem.Gizmo.cs

Small doafter fix.
**Changelog**
:cl: Mocho
- fix: Abductors can no longer instantly gizmo their targets.

Fixes abductor instagizmo

---

Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
Resources/Prototypes/Catalog/Cargo/cargo_atmospherics.yml
Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
Resources/Prototypes/Catalog/Fills/Crates/materials.yml
Resources/Prototypes/Reagents/Materials/metals.yml

title
also lets you buy vapour canisters since it's probably the safest gas there is (it hurting slimes is a myth and is false)
many of those prices were literally 1984, especially atmos cans since gases are literally free and cans now sell for $200 but the prices are from $1k can era
also this is technically a wizden PR port and even wizdenners agreed with this
reasoning for many of the price changes are in comments in the diff
**Changelog**
:cl:
- tweak: Gas canisters, some guns and some materials are now cheaper to buy.
- add: You can now buy water vapour canisters.

downprice some guns/atmos cans/materials

---

Content.Server/DeviceNetwork/Systems/NetworkConfiguratorSystem.cs

fixes alt verbs not appearing for devices without DeviceNetworkComponent, like conveyors, which made linking conveyors really annoying
see CL for the primary purpose of this
it's a fix
tested
**Changelog**
:cl:
- fix: Fixed alt-click actions not showing up while linking some devices, like conveyor belts. You can now click a lever then alt-click conveyor belts to link their default links quickly.

fix alt verbs for device linking

---

Resources/Prototypes/_StarLight/Entities/Clothing/Uniforms/jumpsuits.yml

removes the "contortionist's jumpsuit" name from it, it's now a regular atmos jumpsuit
it is supposed to be a stealth item
yaml
**Changelog**
:cl: pheenty
- fix: The contortionist's jumpsuit no longer outs itself by the name.

fix contortionist's jumpsuit

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml

Baseball bat now has knockback on hit and applies minor stamina damage.
The baseball bat was a fairly uninteresting and bland weapon - quite literally mop 2.0 (the exact same damage, only difference being structural) and barely ahead of a toolbox in terms of usefulness in a fight.
Its all yaml.
Baseball bat now uses "type: MeleeThrowOnHit" and "type: StaminaDamageOnHit" 
Stamina damage is set to 7.5 (9 hits to stam-crit someone with a vest + helmet).
MeleeThrowOnHit is set to 5 speed and 0.25 lifetime.
https://github.com/user-attachments/assets/127def2a-17dc-4d21-a0e2-fb8e19a1a36e
Confirm the following by placing an X in the brackets [X]:
**Changelog**
:cl: the_biggestbruh
- tweak: Baseball bat is now more robust. Get that home run!

Robust baseball bat

---

Resources/Prototypes/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Nukie armor protects far more from explosions, as do chest rigs
Bombing is by far the lamest way to fight nukies, its still usefull against mechs and borgs though.
:cl:
- tweak: Increased nukie explosion resist

Increase nukie explosive resist so people stop cheesing them

---

Resources/Prototypes/borg_types.yml

Gave medical cyborgs the 1.5x surgery medical interns have. Gave medical cyborgs the ignore clothing ability abductors have.
Medical cyborgs are robots designed specifically to heal people, so it makes sense they'd do it faster. Not being able to strip people means when patients pile up in medical, and people need surgery to be healed, you have to ask someone with hands to strip them first. Now medical cyborgs can help medical when they're overwhelmed with patients. 
I gave them the 1.75x surgery modifier that doctors and chemists have at first, but then I saw how quickly you could remove someone's heart with a roundstart surgery module, so I went with 1.5x speed. Being able to surgery through clothes might be too powerful if they're emagged, but at least it requires people to be lying …

Medical cyborgs do surgery faster and can do surgery through clothing

---

Resources/Prototypes/Entities/Objects/Weapons/security.yml

Replaced stun baton wide swing with thrust attack, like it was before.
Upstream broke something and now batons wide swing.
**Changelog**
:cl: Aviu
- fix: Stun batons no longer wide swing, instead they thrust on right click.

Stun baton no longer wideswings

---

Content.Client/_Goobstation/Weapons/LaserPointer/LaserPointerSystem.cs
Content.Server/_Goobstation/Weapons/Ranged/LaserPointerSystem.cs
Content.Shared/_Goobstation/Weapons/SmartGun/LaserPointerComponent.cs
Content.Shared/_Goobstation/Weapons/SmartGun/SharedLaserPointerSystem.cs
Content.Shared/_Goobstation/Weapons/SmartGun/SmartGunSystem.cs
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/SMGs/smartgun.yml

Made it so you can't track yourself using smartgun.
Fixed potential issue when you could theoretically break laser pointer if your client doesn't send network events (like if you have prediction disabled or something)
Also added zoom to smartgun, Half the zoom of hristov.
Relying on client network events for laser pointer is bad. Now if no event was recieved from client in 0.5 seconds (and the gun is not wielded by an npc), it automatically resets laser pointer so that it points at wielder direction and has red color.
**Changelog**
:cl: Aviu
- add: You can now zoom slightly when wielding smart smg.

Small smartgun fix

---

Resources/Prototypes/_Goobstation/Reagents/medicine.yml

Buffed T3 chems
Many of the "supposedly" good + hard to make chems are actually worse than T1 sometimes. This changes oxal and salicylic to be "advanced but all at once", and ebifin/procenyl/syri are buffed to have the same healing amount per unit as other T3s
Yamlmaxxing
**Changelog**
:cl: SX-7
- tweak: Buffed T3 chems

Chem tweaks

---

Content.Shared/Mining/MiningScannerSystem.cs
Content.Shared/_NF/Mining/Components/InnateMiningScannerViewerComponent.cs
Content.Shared/_NF/Mining/MiningScannerSystem.Innate.cs
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/ServerInfo/Guidebook/Mobs/Dwarf.xml

ported dwarf innate mineral scanner from frontier, but changed distance to 3 (still very good in lavaland)
dwarves being good miners is good
Rouden agreed
tested, works
https://github.com/new-frontiers-14/frontier-station-14/pull/2112
**Changelog**
:cl: pheenty
- add: Dwarves now have innate mineral scanner. Rock and Stone!

dwarves feel ore

---

Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml

see CL
70 TC is way too overpriced, every single person i ask about it agrees
it doesn't really do much and if people do gib pot or something, admin issue
even then, it's easily (and this is intentional) metagameable and it's easy to drag its own user with it by just dragging it
**Changelog**
:cl:
- tweak: Syndicate dimension pot 70 TC -> 40 TC.

downprice dimension pot

---

Content.Server/Nutrition/EntitySystems/FoodSystem.cs

If you press Z while holding insuls, mothpeople will eat it. Now that's no longer the case, and they'll be quick-equipped first
There's been a bunch of bugs relating to item use order, gotta work on it. For now a hotfix so you don't eat your heretic medalion, insuls, whatever

Hotfix - moths no longer eat before equipping items in hand

---

Resources/Prototypes/_Goobstation/Entities/Mobs/Player/bingle.yml

title
it just dies to grilles and shocked doors right now
**Changelog**
:cl:
- tweak: Bingles are now insulated.

insulate bingle

---

Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml

14 blunt -> 25 blunt + 30 structural
it's a big mech why does it hit as hard as a toolbox
**Changelog**
:cl:
- tweak: Ripley punch damage increased 14 blunt -> 25 blunt + 30 structural.

increase ripley punch damage

---

Resources/Prototypes/_Goobstation/GameRules/bingleEvent.yml

title
announcement is very attention-grabbing so right now when bingles spawn, the whole of crew and sec mobilises to immediately go kill them and they can't do anything
observed this every time i've seen bingles spawn
**Changelog**
:cl:
- tweak: Bingles are no longer announced.

remove bingle announcement

---

Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/Random/insuls.yml
Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/Random/landmines.yml
Resources/Prototypes/_Goobstation/Maps/submarine.yml

- Added slots for BSO and NTR
- Added some extra slots for some jobs
- Mapped in some funny stuff here and there.
- Fixed submarine mining shuttle dock colliding with the cargo one (whoops)
Basically my first mapping PR, probably will pay off someone to take care of these from now on, I suck at mapping, put me back in the code caves coach.
**Changelog** 
:cl: Mocho
- tweak: Added some extra slots for some jobs on Submarine
- tweak: Mapped in some funny stuff here and there for Submarine.
- fix: Added slots for BSO and NTR on Submarine.
- fix: Fixed submarine mining shuttle dock colliding with the cargo one (whoops).

Submarine Tweaks

---

Content.Server/Animals/Systems/EggLayerSystem.cs
Content.Shared/Nutrition/Components/HungerComponent.cs
Content.Shared/Nutrition/EntitySystems/HungerSystem.cs
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

Mice no longer spawn gazillion mice 10 minutes into the round through exponential scaling
Lag. Fixes https://github.com/Goob-Station/Goob-Station/pull/1767
Rn mice spawn with 25 hunger, which lets them use their "spawn" ability 2 times. This will generate two mice that can do the same. This is *obviously* bad since it's gonna lag the server to hell after 30 minutes or less. As such, food requirement for spawning mice is changed to 20, and starting food amount is set to 15. This in combination with the original food rate consumption decrease makes it so that mice need to eat something (finite resource) before they start any multiplication attempts.
Roundstart:
After all food on the station has been exhausted, and population has stabilized
No changelog cuz this PR likely should be merged in …

Ininite mouse/lag exploit patch

---

Content.IntegrationTests/Tests/GameRules/TraitorRuleTest.cs
Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml

This reverts commit 79369deb583252492c36d850d627457a9fe40516.
I have been MALDING, SEETHING, and frothing at the mouth over being unable to play antag as the true command of the station, Tiders.
This PR is made with 100% pure copium and hate over the change.
**Changelog**
:cl: Tideonia Liberation Forces
- fix: The shackles have been lifted brothers, take arms and fight once more.

Decrease Goob's Standard of Roleplay to LRP-∞ (Revert #1174)

---

Resources/Locale/en-US/_Goobstation/servercurrency/server_currency.ftl
Resources/Prototypes/_Goobstation/ServerCurrency/token_listings.yml

Adds admin abuse tokens for 1000 GC
Funny. 1000 GC was chosen so that people don't spam it too much, and so that admins feel like it's reasonable to do crazy stuff to fulfill the tokens.
Will lower the price if no one buys it, or if admins are lazy bums and just smite you on the spot too much (god at least refund the token then, will you? We all have bad days, no need to take it out on others)
**Changelog**
:cl:
- add: You can buy admin abuse tokens now

Admin abuse tokens

---

Content.Server/Zombies/ZombieSystem.Transform.cs

Zombies can't lay eggs now.
Targeted fix, prevents infinite mice. Stops LAG. Chose to remove egglayer on zombify since it fixes potential future problems most reliably I think. 
I just spawned and zombified these mice and they didn't lay eggs for 20 minutes, and they don't have egglayer component, so all is good I think
Idk no more egglaying zombies
**Changelog** SX-7
:cl:
- fix: Fixed infinite zombie mice bug

[Hotfix] Fix infinite mice electric bogaloo

---

Content.Server/Dragon/Components/DragonRiftComponent.cs
Content.Server/Dragon/DragonRiftSystem.cs
Resources/Locale/en-US/_Goobstation/ghost/ghost-role-component.ftl
Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/carp.yml

spawn cooldown 30s->24s
now has 15% chance to make a sharkminnow instead
it's currently pretty weak and can't really do anything to even one man with gun
it just needs a buff
tested
**Changelog**
:cl:
- add: Dragon carp rifts now have a 15% chance to spawn a sharkminnow instead.
- tweak: Dragon carp rift spawn spacing 30s->24s.

buff dragon rift

---

Content.Server/_Goobstation/Blob/BlobCoreSystem.cs
Content.Shared/_Goobstation/Blob/Components/BlobCoreComponent.cs

makes blobs spawn with 250 blobcoin
makes it less luck-reliant, you can build a basic base of 2 resource nodes (and a factory rather soon after, i tested this) this way
now you don't Just Die:tm: if you get spotted instantly
discord approves
tested, works
**Changelog**
:cl:
- add: 250 starting points for blob.

add blob starting money

---

Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/bingle.yml
Resources/Prototypes/_Goobstation/Entities/Mobs/Player/bingle.yml
Resources/Prototypes/_Goobstation/Entities/Mobs/Player/silicon.yml
Resources/Prototypes/_Shitmed/GameRules/events.yml
Resources/Prototypes/_Shitmed/Roles/Antags/MindRoles/mind_roles.yml
Resources/Prototypes/_Shitmed/Roles/Antags/abductor.yml

1) bingle requires 1 hour overall
2) derelict syndie borg requires 1 hour as borg
3) regular derelict borg spawned through entity spawn requires 1 hour as borg
4) agent and sci abductor now have their own mind roles because why the fuck was it lone abductor. this allows them to show up as their actual role in the round end screen instead of "abductors-ghost-role-name", this line is not even present in the game, i removed it earlier but overlooked the mind role
1) basically fix, to be consistent with the other antags and maybe prevent raiders from taking it
2) same
3) fix, the event ghost role requires it
4) basically fix, makes sense, not really player facing.
didnt even test in game but if yaml linter passes it's probably fine (it's just yaml anyway)
**Changelog**
no cl no fun

some fixes

---

Resources/Prototypes/_Goobstation/Entities/Mobs/Player/bingle.yml

There is 0 reason these beings need this. They are already difficult once they get to multiply. 
Zombies, much slower, less dangerous, no stun do not get insultation. The much faster, 2 hit stun bingle does not need this, especially when they can spawn in an area that just benefits them. They are not that weak, they should lose more than they win. This is handholding. 
It removes any realistic way to fight them if you're forced to melee. AI becomes nullified when trying to defend against them since they can just beat a door down now with no repercussion. This just sucked. 
**Changelog**
:cl:
- tweak: removed insulation from bingle

Revert this fucking shit "insulate bingle (#1782)"

---

Resources/Prototypes/_Goobstation/Wizard/Random/polymorph.yml

makes staff of change have a chance to turn you into a bingle or bingle prime (which will also spawn the pit)
funny
also bingle is good for having ghost roles which we lack right now
also allows you to go funny binglezard gimmick
made discord vote, currently **heavily** in favor
tested, works
**Changelog**
no CL, it'll be a surprise

rare staff of change bingle transformation

---

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml

there is now a jaunter in the salvage closet
if newbie duffelbag can have it, may as well have it in the salvage lockers too
also it is not enjoyable to fall down a pit
**Changelog**
:cl: shoebill
- tweak: Jaunters can now be found in Salvage equipment closets.

add jaunter to salvage closet

---

Content.Server/_Goobstation/Wizard/Components/EndRoundOnWizardDeathRuleComponent.cs
Content.Server/_Goobstation/Wizard/Components/RuleOnWizardDeathRuleComponent.cs
Content.Server/_Goobstation/Wizard/Systems/WizardRuleSystem.cs
Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml

title
why does round even end on wiz death, it doesn't for blob and such, not even for nukies
currently most wizard rounds are just wizard dying instantly which stops all the side antags and crew that wanted to do things from being able to do anything
i don't think i've seen any person express a favorable opinion about roundend on wizard death ever
**Changelog**
:cl:
- tweak: The round no longer ends on wizard death.

remove roundend on wiz death

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml

removed multishot from grenade launchers (only really affects china)
why was this a thing in the first place?
yaml
**Changelog**
:cl: pheenty
- remove: China Lake no longer can be dualwielded.

disallow china lake dual wielding

---

Content.Shared/Projectiles/SharedProjectileSystem.cs
Content.Shared/_Goobstation/Wizard/Traps/SharedIceCubeSystem.cs

Get rid of two most commonly encountered heisenfails
As I noted in the comment in `SharedIceCubeSystem.cs`, for some reason engine just sometimes returns `NaN` as `LinearVelocity` vector in StartCollideEvent. I have no idea why it only happens to icecube, my assumption is that most other code uses `PhysicsSystem` to get linear velocity, and it's just some edge-case bug that flew under the radar. As such, just checking if it's valid solves the issue. Performance overhead from calculating `LengthSquared` twice should be minuscule. It's technically an issue that could be put into RT GH, but I can't really document it well enough.
The second heisenfail, less common since it was only introduced in 182b2db00d017086ca1ac6210189f17185601e61 is just an upstream coding mistake that got past review. …

Removing two test heisenfails

---

Resources/Prototypes/_Goobstation/Wizard/traps.yml

Wizard trap opacity from 2% > 5%
Previously invisible on white tiles, now just barely visible.
Changed color values in traps.yml.
**Changelog**
:cl:
- tweak: Wizard traps now have an opacity of 5%

Make Wizard Traps More Visible

---

Resources/Locale/en-US/_Goobstation/emotes.ftl

adds "starts" to the beginning of the tweaking emote text and that's it, if i managed to mess this up im basically the dumbest person alive
because "the mouse (123) tweaking!" doesn't make sense
one word in one line of code
n/a
**Changelog**
gonna go ahead and say it doesn't need one

Add "starts" to "tweaking!" emote text

---

Content.Server/EntityEffects/Effects/HealthChange.cs

#1860 Introduced faulty logic where chems would not proccess due to supercode.
"Equality comparison of floating point numbers. Possible loss of precision while rounding values"
Do not compare floating numbers with != i guess
**Changelog**

[MERGE FAST] Fix Chemicals not processing at ALL

---

Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.cs
Content.Server/_Goobstation/Heretic/Components/MansusGraspComponent.cs
Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
Content.Shared/_Goobstation/Heretic/Components/HereticComponent.cs
Resources/Prototypes/_Goobstation/Heretic/Actions/Heretic/basic.yml

shit was annoying and weird you had to click on a something to deactivate.
MansusGraspActive is now MansusGrasp and is set to the action id to allow cooldown setting through c#
**Changelog**
:cl:
- tweak: Mansus grasp now can be deactivated through the action.
- tweak: Mansus grasp cooldown starts after use now.

Mansus Grasp Rework

---

Content.Shared/_Lavaland/Procedural/Prototypes/LavalandMapPrototype.cs
Resources/Prototypes/_Lavaland/Procedural/lavaland_planets.yml

bluespace ore can spawn in lavaland again
its meant to be there
BSCrystal added to the markers
its also not commented anymore
it wasnt my fault i swear
**Changelog**
:cl:
- fix: Bluespace ore can appear in Lavaland again

Lavaland bluespace ore fix

---

Content.Server/_Goobstation/ServerCurrency/ServerCurrencySystem.cs
Content.Shared/_Goobstation/CCVar/CCVars.Goob.cs

Set GC multi for non-antag roles to 1.
If you want this back, **MAKE IT MORE EXPLICIT**, thank you
https://github.com/Goob-Station/Goob-Station/pull/1910 messed up and gave command increased GC gain in most command roles. Slight issue - the 3x multi is still being applied. This results in up to 150(!!!) GC being earned per round, and if you main command you can get a ghostrole token in ~4 rounds.
This fix will still make these roles earn 3-5 times as much as most other ones, while not making it so you can earn enough antag tokens to get higher per-round chance of antag that by just playing a tider.
Just set var and cvar to 1. Not ripping up the system since it could be used in the future and set to more reasonable values. I don't think I missed anything.
**Changelog**
:cl:
- fix: Fixed …

fix gc over-earnings in command/sec roles

---

Content.Server/_Goobstation/StationEvents/Components/GameDirectorComponent.cs
Content.Server/_Goobstation/StationEvents/GameDirectorSystem.cs
Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/_Pirates/game_ticking.yml
Resources/Prototypes/_Shitmed/GameRules/events.yml

pirates can spawn
roundstart antags are tied to weights again.
**Changelog**
:cl:
- fix: Pirates, Abductors and the Blob can now spawn as midround event in storyteller modes!
- fix: Nukie spam

Storyteller minor update

---

Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml

makes firelocks be same as airlocks in terms of damage
firelocks were 25% tankier than rwall before
they should realistically be same as airlocks since both are tanky space-grade doors
you might think firelocks would be tankier than doors but they're made of cheapium (basically same construction as doors) so no
**Changelog**
:cl:
- tweak: Firelocks are no longer made out of concentrated reinforcedwallium.

the fall of firelock meta

---

Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs
Content.Server/_Goobstation/Changeling/ChangelingSystem.cs
Resources/Locale/en-US/_Goobstation/Changeling/abilities/changeling.ftl

changeling absorb now checks for hard grab OR incapacitated, instead of grab AND incapacitated, allowing absorbing dead bodies without grabbing them and alive grabbed people. also fixed a typo
fix basically, makes no sense why would ling need to grab a dead body, 13 parity
tested, works as intended
**Changelog**
:cl: pheenty
- fix: Changeling absord no longer requires grabbing dead bodies or killing grabbed ones.

fix changeling grab

---

Resources/Locale/en-US/_Starlight/store/uplink-catalog.ftl
Resources/Prototypes/_StarLight/Catalog/uplink_catalog.yml
Resources/Prototypes/_StarLight/Entities/Clothing/Uniforms/jumpsuits.yml

- no longer atmos job-specific
- add atmos-specific contortionist jumpsuit for 60 TC that allows inventory
why was it atmos-specific
new one because fun, it's a doafter to enter vents anyway and you can be locked in with a crowbar+wrench so i think it's fine
tested, works
**Changelog**
:cl:
- add: Contortionist's bluespace jumpsuit: atmos job-specific contortionist's jumpsuit that allows inventory.
- tweak: Contortionist's jumpsuit is no longer atmos job-specific.

improve contortionist jumpsuit

---

Content.Shared/Damage/Systems/DamageableSystem.cs
Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
Content.Shared/_Goobstation/Weapons/DodgeWideswing/DodgeWideswingComponent.cs
Content.Shared/_Goobstation/Weapons/DodgeWideswing/DodgeWideswingSystem.cs
Resources/Locale/en-US/_Goobstation/damage/dodge-wideswing.ftl
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

- mice can now dodge wideswing
- a dodged wideswing does stamina damage instead
- mice can now be knocked down
- mice now have 20 stamina
they're small so makes sense they should be able to dodge broad attacks
makes mice more trolly
allows you to actually be nimble as a mouse and dodge hits because without this it's impossible
tested, works
**Changelog**
:cl:
- add: Mice now dodge wideswing. It does stamina damage to them instead.

mice dodge

---

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Content.Server/_Lavaland/Shuttles/Systems/DockingConsoleSystem.cs

Fixes, or at least attempts to limit occurences of one annoying bug
Bug, duh
There's two bugs that are getting fixed
Usually, on FTLtoDock the docking config is created on FTL init. As such, if two shuttles were to target the same dock, one will be forced to FTL nearby instead. This tweak makes it so that the shuttle will attempt to get a new docking config before FTLing nearby.
Open server and client in release mode, delete/obstruct salv dock, FTL from lavaland to station when arrivals shuttle is in transit (Arrivals->Station)
On master this will result in mining shuttle FTL to space nearby, on this branch the shuttle will choose another dock.
Mining shuttle system checked for `BecomesStationComponent`. This component is however applied to things like arrivals shuttle, station, cargo …

lavaland shuttle fix (hopium)

---

Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/medical.yml

Atropine carts weren't in the techfab for some reason so i fixed it
:cl: JoeHammad
- fix: Fixed atropine not being available in the medical techfab

SPEEDMERGE I BEG: Atropine fix

---

Content.Server/_Shitmed/Medical/Surgery/GhettoSurgerySystem.cs

previously turning off edagger didnt remove surgery stuff now it does so you cant do surgery with an edagger turned off
condition wasnt inverted, forgot surgerytool removal

fix edagger examine being evil

---

Content.Server/_Goobstation/PlayerListener/DormNotifier.cs
Content.Server/_Goobstation/PlayerListener/DormNotifierMarkerComponent.cs
Content.Shared/_Goobstation/CCVar/CCVars.Goob.cs

Makes dorms markers mappable, and increases the times a bit
Leonid uses them rn but they don't work properly (marker doesn't store radii/name data), and the timeouts are pretty short, making it possible to trigger them randomly. Both of these are adressed
Like a few vars here, few decorators there
No CL since this is a small, mostly mapping-related change

fix dorms marker

---

Resources/Prototypes/_Goobstation/Recipes/Lathes/sheet.yml

now 0.2 diamond and 1 plasma, down from 1 and 0.5
diamonds are very rare, a whole diamond for a bsc is a scam
**Changelog**
:cl:
- tweak: Bluespace crystal recipe is now 0.2 diamond and 1 plasma.

make bluespace crystals cheaper

---

Resources/Prototypes/_Lavaland/Entities/Objects/Weapons/Guns/Basic/pka.yml
Resources/Prototypes/_Lavaland/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Resources/Prototypes/_Lavaland/Entities/Objects/Weapons/pka_upgrade.yml

PKA shotty fires 3 shots instead of 4
PKA shotty requires wielding to fire
Fire-rate upgrade costs 40 space instead of 20
Range upgrade takes 20 storage instead of 30
i got bribed with 500 goob bucks (it was also like objectively the best PKA in the game)
yaml
**Changelog**
:cl: the_biggestbruh
- tweak: Proto-kinetic shotgun fires 3 shots (instead of 4)
- tweak: Proto-kinetic shotgun now requires wielding to fire
- tweak: PKA fire-rate upgrades now require 40 storage instead of 20
- tweak: PKA range upgrades now take up 20 space instead of 30

PKA shotty & fire-rate upgrade nerf & range upgrade buff

---

Resources/Maps/_Goobstation/marathon.yml
Resources/Maps/_Goobstation/omega.yml
Resources/Maps/_Goobstation/packed.yml
Resources/Prototypes/Maps/marathon.yml
Resources/Prototypes/Maps/omega.yml
Resources/Prototypes/Maps/packed.yml

Mapped BSO & NTR rooms onto packed, marathon, and omega.
I also mapped holopads onto marathon because I felt like it.
Twas in the TODO.
I was bored and in a mapping mood.
Map changes!
Marathon
Omega
Packed
**Changelog**
:cl:
- add: Mapped BSO & NTR into Marathon, Packed, and Omega.
- add: Marathon now has holopads.

Blueshield mapping

---

Content.Server/Gateway/Components/GatewayComponent.cs
Content.Server/Gateway/Systems/GatewaySystem.cs
Resources/Maps/_Lavaland/Lavaland/outpost_lavaland.yml
Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_Lavaland/Entities/Objects/Devices/flatpack.yml
Resources/Prototypes/_Lavaland/Entities/Structures/Machines/gateway.yml
Resources/Prototypes/_Lavaland/tags.yml

#1986 but QM doesn't get a flatpack
effectively just makes it easy for admins to link a gateway to lavaland, simply spawn one flatpack
ease of lavaland gateway linking
**Changelog**
:cl:
- add: Lavaland now gets a gateway for easier gateway linking by admin.

lavaland gateway lite

---

Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml

bso no longer spawn with their weapon box, it is found in their locker instead
bso goes to cryo - another latejoins - picks new weapons. while getting a choice is good, this results in more bso weaponry on the station than intended.
**Changelog**
:cl: pheenty
- tweak: BSO weaponry box is now in the BSO's locker instead of being given at spawn.

move bso weapon box to the locker

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Resources/Prototypes/Entities/Objects/Weapons/security.yml
Resources/ServerInfo/Guidebook/Security/Security.xml

- remove baton delayed knockdown, make click behavior same as wideswing
- revert disabler projectile speed buff, keep other buffs
- halve practice disabler fire cost
nonlethals are way too overtuned, sec main PR makers can't fathom having to pick up a gun and actually shoot the antag as opposed to click with baton once
no more clicking people once to down them
**Changelog**
:cl:
- remove: Stun baton delayed knockdown.
- tweak: Disabler projectile speed buff reverted.

partially revert disabler/batong buffs

---

Resources/Locale/en-US/_Goobstation/blob/blob.ftl
Resources/Locale/en-US/_Shitmed/abductor/abductor-ui.ftl
Resources/Prototypes/_Goobstation/CollectiveMind/collective_minds.yml
Resources/Prototypes/_Shitmed/GameRules/events.yml
Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Blob.xml

see diff
fixes abductors not actually getting glorpmind
collective mind existing is currently not communicated at all for blobmind and glorpmind is just broken
**Changelog**
:cl:
- tweak: Briefings now communicate how to use your collective mind channel when appropriate (+e for blobmind, +a for glorpmind).
- tweak: Changeling hivemind channel color changed.
- fix: Fixed abductors not having glorpmind.

collective mind fixes

---

Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml

30 kpa -> 60 kpa
30 is too small.  We have a lot of shifts that end with bad atmos without big atmos problems. Locked vent can be easily fixed with screwdriver, but air leak cannot.
:cl:
- tweak: Increased air vent lock pressure threshold

Increase air vent lock pressure threshold

---

Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.KravMaga.cs
Resources/Prototypes/_Goobstation/MartialArts/judo.yml

Kravmaga no longer stunlocks
Judo slightly weaker
Both were incredibly unfun to be on the receiving end
:cl: Armok
- tweak: Krav Maga legsweep no longer stunlocks
- tweak: Judo Combos longer, throw is G>D>D, Armbar is D>D>G>G
- tweak: Judo moves stam damage changed, throw now does 30, and armbar 70.

Martial arts tweak

---

Resources/toolshedEngineCommandPerms.yml

fixes stuff RT changed
asked to, also fix
fullmins had access to RT commands, but since 247 the RT commands used another perms system on top of regular perms system, this adds them to that. can't do it in seperate file since this garbo is hardcoded in RT
user with admin and fullmin perms (cvar loginlocal is false)
Can execute `entities`, `self`, 'ent', and `nearby` commands now
Deadminned users and regular users can't use these
- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.
This is a non-player facing fix, no cl

Give fullmins fullmin commands (again)

---

Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml

title
people complain on discord about wizard being too common
lowering nukies to 0.02 (from 0.09) was a test to see if "the other gamemodes in gamedir are failing so it falls back to nukeops". and well it doesn't. nukies basically do not exist now, so it's safe to up it to 0.05 now
TWO LINES OMG
**Changelog**
:cl:
- tweak: Nukies should now once again appear in the game, and wizard should appear somewhat rarer.

lower wizard and up nukie weights

---

Content.Shared/_Goobstation/MartialArts/Components/GrantMartialArtKnowledgeComponent.cs
Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.SleepingCarp.cs

Carp scroll is now only learnable by 3 people.
Some nukie shifts, one syndicate buys a carp scroll for the entire crew. You can imagine how that goes.
And just general balance tbh.
see commit
**Changelog**
:cl:
- tweak: Carp scroll can now only be learned by a single person.

Carp scroll learning tweak

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Biocube fabricators can be sped up using space lube.
I want to use the biocube fabricator to make a bunch of cubes because it would be funny, but it takes a really long time to print them. Space lube biocube fabricators still take a long time, but it's faster.
One line of YAMLmaxxing
**Changelog**
:cl: RatherUncreativeName
- tweak: Biocube Fabricators can be sped up using space lube.

Biocube fabricators can be sped up with space lube

---

Resources/Prototypes/Entities/Objects/Misc/space_cash.yml

lets spesos burn and be eaten
realism
**Changelog**
:cl:
- add: Spesos can now burn and be eaten.

it's about sending a message

---

Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/GameRules/pests.yml
Resources/Prototypes/GameRules/random_sentience.yml
Resources/Prototypes/GameRules/unknown_shuttles.yml

title
notably, makes ion storms/etc actually happen, also fixes midround shuttle events
fix
**Changelog**
:cl:
- fix: Fixed many events not happening.

add game director weights to a bunch of events

---

Resources/Locale/en-US/_Goobstation/collective-mind/collective-mind.ftl
Resources/Locale/en-US/_Imp/Drone/ghost-role-component.ftl
Resources/Prototypes/Entities/Objects/Tools/tools.yml
Resources/Prototypes/_Goobstation/CollectiveMind/collective_minds.yml
Resources/Prototypes/_Goobstation/tags.yml
Resources/Prototypes/_Imp/_Drone/Mobs_Player_silicon.yml
Resources/Prototypes/_Imp/_Drone/drone.yml
Resources/Prototypes/_Imp/_Drone/drone_tools.yml

- the omnitool no longer has an 1-second cooldown between tool changes
- now gets an experimental RCD
- now has its own dronemind collective mind channel
good
makes them way more worth it and more interesting to play
basically engiborg lite with this
tested, works
**Changelog**
:cl:
- add: Maintenance drones now have an experimental RCD.
- add: Maintenance drones now have their own collective mind channel on +d.
- tweak: The maintenance drone omnitool no longer has a cooldown between tool changes.

maintenance drone improvements

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Resources/Prototypes/Entities/Structures/Shuttles/cannons.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/Weapons/Gun/industrial.yml

ptk800 and exosuit pka (now called proto-kinetic launcher) now respect lavaland changes being pressure damage reduction and upgrading.
makes sense
tested works
**Changelog**
:cl:
- tweak: PTK-800 and mech proto-kinetic launcher now deal more damage in low pressure and less damage in a normal athosphere, and are upgradeable with modkits.

make ptk800 and mech pka respect lavaland changes

---

Content.Shared/Doors/Components/DoorComponent.cs
Content.Shared/Doors/Systems/SharedDoorSystem.cs
Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml

see media section
only affects doors if:
- you're walking towards it
- the door would open to someone with no accesses
- you're moving fast enough (crawling is slow enough to have it not trigger)
and the proximity check only happens when you have just walked in within 2 tiles of the door
the performance impact is so low that it doesn't register in the profiler
prevents doors from being annoying
poll is so far favorable (11/1 at the time of writing)
see diff it's small
https://github.com/user-attachments/assets/d7f50c8a-40ad-4040-aa96-c074926abcd9
**Changelog**
:cl:
- add: Access-less doors now open ahead of time when approached.

proximity airlock opening

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml

title/see diff
requested by aviu: also gives them 5u chem storage instead of 2u
good
also prevents small explosions from erasing spears in your bag/etc
tested
**Changelog**
:cl:
- tweak: Spears are no longer destructible.
- tweak: Spears can now contain up to 5u of chemicals, but inject 1u on melee and 2u on throw.

undestructiblify spears

---

Content.Server/_Goobstation/Bingle/BinglePitSystem.cs
Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs

title
can't rob bingles of their victory anymore
it's really easy to counter them before that (just turn off grav) so if bingles got to this point they deserve to just win
tested, works
**Changelog**
:cl:
- tweak: Max-size bingle pit now ignores gravity.

make max-size bingle pit ignore gravity

---

Content.Shared/_Shitmed/Surgery/Conditions/SurgeryBodyConditionComponent.cs
Content.Shared/_Shitmed/Surgery/Conditions/SurgeryOrganSlotConditionComponent.cs
Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Steps.cs
Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.cs
Content.Shared/_Shitmed/Surgery/Steps/SurgeryAddOrganSlotStepComponent.cs
Resources/Locale/en-US/_Shitmed/surgery/surgery-popup.ftl
Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml

ported from https://github.com/DeltaV-Station/Delta-v/pull/3059
@gluesniffler 
can be used for adding evil organs like unique abductor organs but not supercode, CBMs cdda, etc
- `SurgeryOrganSlotCondition` added to a surgery makes it require a body part to have/not have an organ slot. this can let stuff like not showing brain transplants for ipc head
- `SurgeryAddOrganSlotStep` makes a step of above surgery create an empty slot with the specified id in that component.
- `SurgeryBodyCondition` also lets you white/blacklist certain body prototypes for surgeries very epic, lets ipc-specific surgeries be made
:trollface:

port surgery code for manipulating organ slots

---

Resources/Prototypes/Atmospherics/thresholds.yml

makes air alarms not angry at high oxygen
why did they have an upper bound for oxygen and why was it so low
"but high oxygen means worse fires" no it doesn't, as an experienced atmos i can say that you either are in a fire or you aren't, there's no "worse"
and we don't have oxygen poisoning so high oxygen is just safe
**Changelog**
:cl:
- tweak: Air alarms no longer go into danger state due to high oxygen amount.

make air alarms not angry at oxygen

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_Lavaland/Catalog/Cargo/cargo_cargo.yml
Resources/Prototypes/_Lavaland/Catalog/Fills/Crates/cargo.yml
Resources/Prototypes/_Lavaland/Entities/Objects/Devices/flatpack.yml
Resources/Prototypes/_Lavaland/Entities/Structures/Machines/gateway.yml
Resources/Prototypes/_Lavaland/tags.yml

allows cargo to buy lavaland gateway flatpack for 20k
can't interlink them
incentivises salv to get money
also rewards it more
it's basically qol
tested, works
**Changelog**
:cl:
- add: You can now buy lavaland gateways at cargo for a high price.

purchasable lavaland gateway

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml

laser rifle 4x4 -> 4x2
why was it 4x4
mocho said could maybe make it 3x2 even
**Changelog**
:cl:
- tweak: Laser rifles huge (4x4) -> large (4x2).

smallen laser rifle

---

Content.Goobstation.Common/CCVar/CCVars.Goob.cs
Content.Goobstation.Server/StationEvents/GameDirectorSystem.cs
Content.Goobstation.Shared/StationEvents/IncompatibleGameModesPrototype.cs
Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml

Some roundstart gamemodes are now incompatible. Like nukies + blob or nukies + zombies or nukies + revs. Also double blob, nukies and wizards.
Read discussion in https://discord.com/channels/1202734573247795300/1354899626439999629
In short, I was requested to do this because some of the gamemodes being selected together is just awful.
**Changelog**
:cl: Aviu
- add: Roundstart nukeops can no longer spawn with revs, blob or zombies.
- fix: Fixed 2 roundstart nukie squads, 2 blobs or 2 wizards being selected sometimes.

Incompatible roundstart game director gamemodes

---

Content.Server/Body/Systems/InternalsSystem.cs

hide o2 alert without a breath mask
shit clogging up my damn alert indicator pt 1
**Changelog**
:cl:
- tweak: Internals alert is hidden when not wearing a breath mask now.

hide o2 alert without a breath mask

---

Content.Shared/Doors/Components/DoorComponent.cs
Content.Shared/Doors/Systems/SharedDoorSystem.cs
Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml

title
many bug reports and many issue reports so it doesn't seem like this was a good idea afterall
might make another PR readding them as their own proto later so not every airlock has this
**Changelog**
:cl:
- remove: Proximity airlock opening.

revert proximity airlocks

---

Content.Shared/CCVar/CCVars.Interactions.cs

Reverts Goob-Station/Goob-Station#2131
who the fuck told you this does not look awful and is a good idea
even then who the fuck told you to use specifically 5 and not -1
and finally who the fuck told you to put it into default cvar values instead of asking durk to put it into server config
btw no, this is not mald pr, mald pr is the original one, where the average ipc player with skill issues does not know what hotkey is
:cl: pheenty
- tweak: Multiple storage behavior was reverted.

Revert "Increse the ammount of inventry you can have open at one time"

---

Content.Goobstation.Server/NPC/GroupRetaliationComponent.cs
Content.Goobstation.Server/NPC/GroupRetaliationSystem.cs
Content.Server/NPC/Events/NPCRetaliatedEvent.cs
Content.Server/NPC/Systems/NPCRetaliationSystem.cs
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/NPCs/mob.yml
Resources/Prototypes/_Goobstation/Reagents/narcotics.yml
Resources/Prototypes/ai_factions.yml

add NPC group retaliation and adds it to mice and monkeys
if you hit a NPC with group retaliation, it will also aggro all nearby NPCs
mouse retaliation times out after 5 seconds
raised mousebites polymorph threshold to 50
good
monkeys needed this
gave to mice because funny, from testing it can't really damage you much
https://github.com/user-attachments/assets/52855563-ac8c-4e70-a780-18e4e445b57a
**Changelog**
:cl:
- add: Group retaliation to monkeys and mice.

add group retaliation

---

Resources/Prototypes/_Goobstation/Wizard/actions.yml
Resources/Prototypes/_Goobstation/Wizard/spellbook_catalog.yml

It was a really funny bit to abuse, I regret nothing. I doubt the admins do either :trollface:
Disabling prediction breaks things, which is a nothingburger when people only play our server, but since wizden 1984d the network tab from everywhere that makes fixing it only possible on goob (peak)
**Changelog**
:cl: Mocho
- remove: 1984d curse of byond spell, admins can still use though

1984 byond curse, april fools is over sadly

---

Resources/Prototypes/_Lavaland/Entities/Objects/Specific/Salvage/shelter.yml

Removes grid preloading from bluespace shelter capsules, as it was causing buggy behavior. This is probably a band-aid fix.
Buggy behavior to do with the preloaded grids not being initialized properly. Most notably, there is no light tube, and door accesses are not loaded correctly, leading to doors always being locked (even with admin ID) instead of never being locked.
Changed two lines in YML from 5 and 3 to 0.
From what I can tell (and I don't know much C#, or any really), bluespace shelter capsules use the same grid pre-loading system that shuttle events do, loading the grids onto an uninitialized map. The difference, however, is that shuttle events first move the grids into an entirely new map, which is only then initialized.
Preloaded shelter capsules don't do this; they directly …

Bluespace shelters: Remove preloaded grids

---

Resources/Prototypes/Catalog/uplink_catalog.yml

Added surplus bundles (Super Surplus and Surplus) to nukies uplink
I think it would funny, nukies with random stuff
Changed blacklist to whitelist in uplink catalog
**Changelog**
:cl:
- add: Nukies now can buy surplus and super surplus bundles!

Nukie-Surplus

---

Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml

title 
Nukies are all about attrition, they should not have any infinite ammo ranged options
:cl: Armok
- tweak: Nukies cannot purchase anaconda

Remove anaconda from nukie uplink

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/Packs/medical.yml
Resources/Prototypes/Recipes/Lathes/Packs/science.yml
Resources/Prototypes/Recipes/Lathes/Packs/security.yml
Resources/Prototypes/Research/arsenal.yml
Resources/Prototypes/Research/industrial.yml
Resources/Prototypes/_Goobstation/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/science.yml
Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/shared.yml
Resources/Prototypes/_Goobstation/Research/arsenal.yml

Removed the explosives research and made all grenade components roundstart. The advanced remote signaller was moved to advanced tools research.
Hoping to see modular grenades made more often, reusable cleanades, lube bombs, bomb bombs, and such. Makes acquiring explosives without spending TC a bit easier for traitors, makes jugmixing your funny carpetium bombs as a chemist less necessary.
- Removed explosives research and made the payloads and triggers static for lathes
- Moved advanced remote signaller to advanced tools research
- Added triggers to their own recipe pack in the goobstation shared packs
- Chemical payload moved to BasicChemistryStatic pack
- Autolathes, Security, Science, and Medical techfabs have access to triggers roundstart
- Security techfab has access to all payloads …

Roundstart grenade tech SECOND TRY

---

.github/PULL_REQUEST_TEMPLATE.md
Resources/Locale/en-US/_Goobstation/servercurrency/server_currency.ftl
Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml

Made wizard a low number as its intended to be. The whole reasoning its this strong compared to a normal antag is because its 1. supposed to be a solo antag that drives the entire round, 2. is INCREDIBLY uncommon in 13, which discredits a lot of the malding over the OP skills when you only have to deal with them once every few hundred rounds if not more.
Also killed the wiz token in high tier since Rouge and Nigel have both expressed interest in just either 1984ing it or moving it into its own thing.
No I will not increase prices, nor create a special token for wizard in this PR, go nag the agmins to get their shit together, its been a month since the last time we heard of their "we're reworking them internally" uh huh.
PS: I might be regarded and unable to math here, presumably 0.007 / …

1984 wizard spawn rates and antag token

---

Resources/Prototypes/_Goobstation/game_presets.yml

This reverts commit e54c6b6b31352b7cba0daf067dab779d4e19c797.
Revert PR 2384
The gamedir variant is spawning trash in the SM at roundstart activating it immediately.
Because this is Wizden code and Wiz do not have an SM there is no check in place to ensure that trash does not spawn on SM - This is a problem for us though.
**Changelog**
:cl:
- fix: No more roundstart SM activations

Revert "Gamedir roundstart variation (#2384)"

---

Content.Goobstation.Shared/Enchanting/Systems/EnchantRelaySystem.cs

goidacode only raised InventoryRelayedEvent<DamageModifyEvent> on clothing so changed the thing to raise the proper event
fixes #2419
:cl:
- fix: Fixed protection enchant not working.

fix protection enchant

---

Resources/Prototypes/_Floofstation/Entities/Mobs/Species/resomi.yml

Alters Resomi race's cold-based movement speed changes to match with their lower temperature tolerances (and parity with the UI element).
For an ice-world race, they sure do seem quite crippled in mobility by the slightest of breezes.
YML changes. Thresholds calculated based on the alert scale from TemperatureSystem and rounded up, where:
`ceil(((normalBodyTemperature - coldDamageThreshold) * alertThreshold) + coldDamageThreshold)`
with the alert thresholds being 0.66, 0.4, and 0.
This is also the same fashion in which they were calculated for BaseMobSpeciesOrganic (albeit it was rounded down there), so parity there as well.
**Changelog**
- tweak: Resomi are slowed less by cold temperatures

Make Resomi go less slow when cold

---

Resources/Prototypes/Entities/Objects/Specific/chemistry.yml

Made the cryostatis syringe valid ammo for the syringe guns.
It was probably a oversight that the cryostasis syringe was not valid ammo for the guns. Bluespace syringe can already be fired so this shouldn't change balance much. Cryostatis syringes are mapped in virology in some maps  and they were generally useless until this. This would make explosives syringes marginally more useful assuming the revert breakable syringes is merged (which I support).
Its a single line yaml change adds the required tag to the prototype. Perhaps it can be argued that they tag should be added to syringebase object instead but I did not want to make a big change.
https://github.com/user-attachments/assets/2e80991c-822c-4813-8d3d-8f7bc1a8248c
**Changelog**
:cl: teneketaro
- add: Cryostatis syringes can now be …

Make cryostasis syringe fireable from the syringe gun.

---

Content.Shared/Stealth/Components/StealthOnMoveComponent.cs
Content.Shared/Stealth/SharedStealthSystem.cs
Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml

- Syndicate Stealth Suit resistance decreased (pierce 40% -> 35%, heat 35% -> 25%)
- Syndicate Stealth Suit now requires 3 seconds of no stealth losing (no moving, attacking someone) to start accumulating stealth.
Stealth suit was overpowered for it's price. For 75 TC you was absolutely invisible even if you moved slightly. It was hard to counterplay (and it's still hard to play against)
https://github.com/user-attachments/assets/be70a1e3-8329-432d-87cd-c57580618594
**Changelog**
:cl:
- tweak: Syndicate stealth suit heat and pierce protection was decreased.
- tweak: Syndicate stealth suit now requires 3 second of no-stealth loss to start accumulating stealth.

Syndicate Stealth Suit Nerf

---

Content.Goobstation.Shared/Enchanting/Components/CanEnchantComponent.cs
Content.Goobstation.Shared/Enchanting/Systems/EnchanterSystem.cs
Resources/Locale/en-US/_Goobstation/enchanting/enchanter.ftl
Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Resources/Prototypes/Entities/Objects/Magic/books.yml
Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
Resources/Prototypes/_Goobstation/Heretic/Entities/Structures/Specific/Heretic/ritual_rune.yml
Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml

You now have a reason to interact with Chaplain. You will not steal his bibles and raid chapel without saying a word. 
**Changelog**
:cl:
- tweak: Only heretic, wizard and chaplain have ability to enchant items now.

Limit Enchanting to Chaplain/Heretic/Wizard

---

Resources/Maps/_Goobstation/Nonstations/ghostbar.yml

Removed antag arena portal from ghost bar until we make it optimized for server. Admins still can teleport players to it.
It causes too much lags and servers problems. It requires admin to stop spamming there. 
:cl:
- remove: Ghost bar arena portal was temporarily removed.

Temporarily remove ghost bar antag portal

---

Resources/Prototypes/Entities/Objects/Misc/pen.yml

3 -> 20 damage
why did they do 3 embed damage if they do 15 melee
**Changelog**
:cl:
- tweak: Advanced pens (e.g. cybersun pen) now do 3 -> 20 embed damage.

more embed damage for advanced pens

---

Resources/Changelog/GoobChangelog.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/e_sword_welder.yml

welder sword is now slightly less effective against blob, 10/5 heat/slash instead of 11/4, also looks better. also it's no longer 4 times limb damage as the real esword, this was too much. in exchange it has 10% prob to reflect lasers (epen has 25%) because it's cool (antags don't use lasers anyway). also it's no longer usable to craft double energy swords.
**Changelog**
:cl:
- tweak: Welder energy swords now have 10% chance of reflecting lasers, deal 5/10 damage instead of 4/11, and are half as effective in damaging limbs as the real eswords.
- fix: You can no longer use welder energy swords to craft a real double energy sword.

Fixwelderswords

---

Content.Server/Singularity/EntitySystems/RadiationCollectorSystem.cs

buff of radcollectors in preparation for PTL
removes wizden 1984 on rad collectors
makes them more efficient at high rads to make it actually worth it
good
in preparation for PTL
doesn't change their power output per radiation so won't break anything
**Changelog**
:cl:
- tweak: Radiation collectors are now more efficient at higher radiation. Also removed them being bad if you use cold plasma.

buff radcollectors

---

Content.Shared/Atmos/Atmospherics.cs

removes atmos tempcap
it's useless
only reason it exists is because notafet broke atmos and added this so air only went to 262kK or so and not infinity
the thing that caused that was reverted long ago so now it just exists for no reason
this should have no gameplay implications that matter, as tempcap gas is hard to make and if you want to use it for flooding using colder hot gas is just better
**Changelog**
:cl:
- remove: Atmos temperature limit effectively removed.

effectively remove atmos tempcap

---

Content.Goobstation.Common/Bingle/BinglePitComponent.cs

Changes how many items bingles need to spawn a new bingle, 20 -> 12
#1830 minorly buffed bingles but changed the items needed from 10 to 20 for no said reason, and now bingles just get swept variably hard. They were already a minor threat at 10 per bingle, and now just can be wiped by a single person, which is boring. 
**Changelog**
Original change had no cl, no cl for reverting

Unnerfs bingles

---

Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml

Each blob tile no longer has a point light. Reverts #1915
I believe this was made as a balancing change, but this doesn't nerf the blob very hard at all and feels like the wrong direction to do so. It may even be harder as you can't distinguish reflective tiles as easily, as they were special in that they glowed in the dark. The lighting engine breaks at 128 lights on screen, which is easily hit with this change and you can visibly notice it breaking when near a blob. It also just doesn't feel thematic for a blob to emit a light at every tile.
**Changelog**
:cl:
- remove: Blobs no longer emit light.

Remove random lights from blob

---

Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/armour.yml

Bluespace armor and the syndicate variant are now invisible in the strip menu.
They're supposed to.
N/A
It works bro, just trust me.
N/A
**Changelog**
:cl:
- tweak: Invisible armor (Syndie and Centcomm) are now invisible in the strip menu.

Invisible Armor Fix

---

Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesEui.cs

Ghost Spawners with time locks now properly group together. so... really. stuff like maintenance drones don't have to pollute the ghost roles anymore.
So it doesn't look like this anymore:
Heads up, this is baby's literal first C# project. so please bear with me if i'm comitting sacrilege with this. But. the grouping function of ghost roles doesn't group for class? prototype? type? (I don't know the terminology) of the requirements, just the UID/instance of those ghost spawners requirements. which are different on every ghost role spawners.
This fixes it by not grouping by those. just by the name and description. and does the requirements by using the first indexed requirements. later down the code. this can cause problems sure. but you really shouldn't have the same exact name and desc …

Ghost Spawners with time locks now properly group together.

---

Resources/Prototypes/_Goobstation/Roles/Jobs/Fun/visitors_startinggear.yml

Alien tourists had mediocre drip, now they really have that shit on.
(Discussed this with Ilya after original PR, fun little tweak)
I pictured the average dad on holiday and realised a fanny pack is more appropriate than a backpack.
Following loadout items changed:
Shoes slot changed from regular shoes -> Fake Jordans
Back slot removed
Waist slot added Leather Waist bag
##Media 
:cl:
- tweak: Dripped out the Alien Tourist

Visitor Aliens now have Fanny Packs and totally real Jordans

---

Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs

wideswing stamina damage now scales with amount of entities hit -1
makes sense
tested, works
**Changelog**
:cl:
- tweak: Wideswing stamina damage is now per target hit -1.

per-ent-hit wideswing stam damage

---

Content.Goobstation.Client/Research/UI/FancyResearchConsoleMenu.xaml.cs

Research menu doesn't look bad now
Was broken, look at media
BG was not scaling up/down (usually good thing), which didn't leave space for sidebar on undersized screens - which is the default. 
It's caused by v249.0.0 fixing dynamic scaling allowing elements (static bg in this case) to go <min size. Or rather, before this change, they could go <min, which was used in the system. Now that it's fixed, it has to be explicitly set.
Before: 
Undersize - no bg on sidebar
Oversize - black bg and no stretch
After:
Undersize - yes bg on sidebar
Oversize - nice stretch
**Changelog**
:cl:
- fix: Fixed research menu sidebar/bg

Fix broken UI in research menu

---

Resources/Prototypes/_Goobstation/game_presets.yml

title
adds the relevant schedulers to gamemodes
technically fix
**Changelog**
:cl:
- fix: Midround shuttle events should work again.

fix midround shuttles not existing

---

Content.Shared/_Shitcode/Heretic/Systems/RustChargeSystem.cs

Fixed rust charge not ending when you get thrown in space.
bug.
Turns out LandEvent isn't always raised for thrown items.
**Changelog**
:cl: Aviu
- fix: Fix rust charge not ending when performer is thrown into space.

Fix rust charge.

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

its in protolathe now not circuit printer idk why i put it there
**Changelog**
:cl:
- fix: Fixed upgrade kits not being in the protolathe.

fix upgrade kits being in circuit printer

---

Content.Goobstation.Server/Fax/FaxSignalSystem.cs
Content.Server/Fax/FaxSystem.cs
Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs
Resources/Locale/en-US/_Goobstation/machines/automation.ftl
Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
Resources/Prototypes/_Goobstation/DeviceLink/sink_ports.yml
Resources/Prototypes/_Goobstation/DeviceLink/source_ports.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Tools/tools.yml

you can use automation upgrade on fax to copy paper on signal and manipulate the paper slot
due to device network goidacode it also breaks fax sending but its fine because automated spamming is bad
part 1 of automating tider money printing sweatshop
**Changelog**
:cl:
- add: Faxes now accept automation upgrades.

make fax automatable

---

Content.Server/StationEvents/Events/GreytideVirusRule.cs

Now greytide virus set emergency access on door instead of open-bolt it.
Greytide virus was open-bolt space airlocks, causing the station to depressurize. It often leaded to early evac. 
:cl:
- tweak: Greytide virus now emergency access doors instead of bolt open them.

Greytide Virus EA door instead of open-bolt them

---

Resources/Prototypes/_Goobstation/Entities/Objects/Misc/Crafting/ghetto_stuff.yml

Tide Flipper is now considered major contraband.
people are starting to mald about it, but sec should do their job in confiscation of these things
1 line yaml
**Changelog**
:cl: LuciferEOS
- tweak: Tide flipper is now considered a major contraband.

Move tide flipper to major contra

---

Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs

~~basically reverts https://github.com/space-wizards/space-station-14/pull/29827
so fast shotgun loading with spam clicks is legit a feature~~
shotgun loading doafter no longer breaks on move (still breaks on damage)
:cl:
- tweak: You can now reload shotguns on the go.

slightly less awful shotgun reloading

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml

Kitchen knifes now can be thrown like combat knifes.
Even glass shards can be thrown like that
copied comps from combat knife, throwing knifes is useless but it is fun sometimes
also tested, works
trust.
**Changelog**
:cl: LuciferEOS
- tweak: Kitchen knifes now do damage when thrown at somebody.

Kitchen knifes do damage when thrown

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

borgs can now self-weld
the doafter takes 30s and spends about 40 fuel
why aren't they able to
borgs are already weak just let them
tested, works
**Changelog**
:cl:
- tweak: Borgs can now self-weld.

borg self-weld

---

Content.Server/EntityEffects/Effects/HealthChange.cs
Content.Shared/Body/Components/BodyComponent.cs
Content.Shared/Damage/Systems/DamageableSystem.cs
Content.Shared/_Shitmed/Body/Components/BodyTypeEnums.cs
Content.Shared/_Shitmed/Surgery/Consciousness/Systems/ConsciousnessSystem.Networking.cs
Content.Shared/_Shitmed/Surgery/Pain/Components/NerveSystemComponent.cs
Content.Shared/_Shitmed/Surgery/Pain/Systems/PainSystem.Damage.cs
Content.Shared/_Shitmed/Surgery/Traumas/Systems/TraumaSystem.Process.cs
Resources/Prototypes/Catalog/VendingMachines/Inventories/robotics.yml
Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Resources/Prototypes/Entities/Mobs/NPCs/lavaland.yml
Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/medical.yml
Resources/Prototypes/_Shitmed/Body/Parts/animal.yml
Resources/Prototypes/_Shitmed/Body/Prototypes/Animal/dragon.yml
Resources/Prototypes/_Shitmed/Body/Prototypes/Animal/goliath.yml
Resources/Prototypes/_Shitmed/Body/Prototypes/Animal/laserraptor.yml
Resources/Prototypes/_Shitmed/Entities/Surgery/wounds.yml
Resources/Prototypes/_Shitmed/Recipes/Lathes/medical.yml

**Changelog**
🆑Mocho
- tweak: Reduced paincrit duration, increased adrenaline pain reduction and pain thresholds, and reduced wound pain multipliers.
- tweak: Added stitches and bonesetters to borg inventories and lathes.
- fix: Attempted some fixes at PVS/flickering issues
- fix: Dragons, goliaths, watchers and cyborgs are not immortal anymore.
- fix: Fixed chemicals being 1/11th of their intended values.

Woundmed Fixes 1

---

Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml

Wiz weight from .007 to .025 bringing it from approx 0.9% chance to 3.14%.
Wizards are meant to be rare yea but unlike any other game mode only 1 person gets it, combined with the chance made it stupidly rare to actually roll a wizard. Math in the bounty brought it to something like 4000 hours average for someone to roll wizard. Not to mention while wizards are meant to be round changing a lot of players like to just play wizards that are either friendly or take so long to do anything, I've seen 1 wizard since the change and they casted no magic all round because they were hidden as a tider trying to set up a gimmick.
Balance: There is none just people wanna play wiz more.
Why: Bounty https://discord.com/channels/1202734573247795300/1371226249183100999/1371226249183100999
1 line yaml …

[BOUNTY] Better wiz chances

---

Resources/Prototypes/Entities/Objects/Materials/ore.yml

annoying as fuck getting 20 rad damage when mining
actual bananium still radioactive because le refinement
:cl:
- remove: Bananium ORE is no longer radioactive.

remove radiation from bananium ore

---

Content.Server/Singularity/EntitySystems/SingularityGeneratorSystem.cs
Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/generator.yml

no longer looses
also adds cooldown to tesla generator between making teslas
tested, works
**Changelog**
:cl:
- fix: 1x1 tesla setups should no longer loose.

fix 1x1 tesla

---

Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs

Heretics and Changelings can no longer be brainwashed by Communist Propaganda. 
Heretics only want to take a propaganda at books and Changelings want a propaganda at their next meal. 
The conversion of these antags and unclear way to approach revs/headrevs as objectives is stupid. Removing the ability to convert either makes killing or eating revs/headrevs more black and white.
Changed method OnPostFlash of RevolutionaryRuleSystem.cs to check for HereticComponent and ChangelingComponent. If either are found it returns empty hence not converting them.
**Changelog**
:cl:
- tweak: Changelings and Heretics can no longer be made revolutionaries
- add: Headrevs are back on the menu for all you ling enjoyers
- remove: Your studies of the mansus are no longer superseded by being shown The Death …

Heretics & Changelings can no longer be made Revolutionaries

---

Resources/Prototypes/Entities/Mobs/Player/observer.yml

gives ghosts mass scanner like aghosts have
so can see nearby grids
shouldn't affect balance
tested, works
**Changelog**
:cl:
- add: Ghosts can now access mass scanner UI.

give ghosts mass scanner

---

Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs

Wiz was missing from antag menu
Bad, sad, closes https://github.com/Goob-Station/Goob-Station/issues/2643
1 line
No
No
**Changelog**
No

Add wiz back to antag menu

---

Content.Client/UserInterface/Controls/FancyWindow.xaml

Fix for close button being under title if title is too long when opening vend menu. For example PlastSteel Chef Vend.
Before this PR the menu would need to be dragged to be wider so the close button appeared.
Added ClipText="True" to FancyWindow.xaml.
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
Tested with some other vending machines as well, they worked normally. So I hope nothing breaks?
**Changelog**
Fix for close button being hidden in some Vending Machines.

Fix for close button being hidden in vend menu with too long title

---

Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusSystem.cs
Content.Server/StationEvents/Components/StationEventComponent.cs
Content.Shared/GameTicking/Components/GameRuleComponent.cs
Resources/Prototypes/GameRules/cargo_gifts.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/GameRules/midround.yml
Resources/Prototypes/GameRules/pests.yml
Resources/Prototypes/GameRules/random_sentience.yml
Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/GameRules/unknown_shuttles.yml
Resources/Prototypes/_Goobstation/GameRules/bingleEvent.yml
Resources/Prototypes/_Goobstation/GameRules/event_types.yml
Resources/Prototypes/_Goobstation/GameRules/midround.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/GameRules/secretplus.yml
Resources/Prototypes/_Goobstation/GameRules/unknown_shuttles.yml
Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml
Resources/Prototypes/_Goobstation/_Pirates/game_ticking.yml
Resources/Prototypes/_Shitmed/GameRules/events.yml

attempts to fix bug where nukeops fails to choose anyone
moves ChaosScore to GameRuleComponent from StationEventComponent so we don't have to add `- type: StationEvent` to roundstart events
i used a regex to migrate the yml field but seems like it didn't troll
i suspect the nukeops bug is caused by the gamerule getting killed due to being a station event (1s duration by default), but this doesn't happen in localhost since it loads fast enough
heisenbug, has to be tested in production
**Changelog**
:cl:
- fix: Possibly fixed nukeops.

attempt to fix nukeops heisenbug

---

Content.Server/EntityEffects/Effects/HealthChange.cs
Resources/Prototypes/Entities/Mobs/Species/gingerbread.yml
Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
Resources/Prototypes/Entities/Mobs/Species/slime.yml
Resources/Prototypes/Nyanotrasen/Entities/Mobs/Player/felinid.yml
Resources/Prototypes/_Goobstation/Entities/Mobs/Species/tajaran.yml

gingerbreads, slimes, skeletons and most importantly cats can now be sprayed with acids, also affects styptic powder
also buffed milk because long ago aviu removed skeleton damagemodifier so at least they have good healing now, one milk splash (20u) can heal 15 damage, wow
also removed the contact topical cap, because well, it was made for styptic and sulfudiazine which are absolutely fine after the chemical splitting fix so why nerf them (them being blocked by wounds is already a huge nerf by alone), moreover it also affects the said milk making it absolutely useless, also slimes cannot be water bombed now etc, it's a bad thing to have. 
it's also hyper goida because it's hardcoded to all chemicals, if it's really needed it should be done another way, but i don't see why would you want …

fix acids and contact topicals

---

Resources/Prototypes/Recipes/Reactions/fun.yml

Chemical reaction that makes plastic makes stacks of 10 plastic instead of stacks of 1.
The output of plastic is the same as before, but now it's a lot faster and easier to pick up the plastic. Instead of clicking 30 times to pick up a stack of plastic, you have to click 3 times to merge the stack.
Old method, makes 120 stacks of one piece of plastic.
New method, makes 12 stacks of 10 plastic.
**Changelog**
:cl: RatherUncreativeName
- tweak: Chemistry plastic reaction makes plastic in stacks of 10 instead of stacks of 1.

Plastic chemical reaction makes stacks of 10 plastic

---

Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/Roles/MindRoles/mind_roles.yml
Resources/Prototypes/_Goobstation/Objectives/objectiveGroups.yml
Resources/Prototypes/_Goobstation/Objectives/traitor.yml

Earlier removal of syndie objectives from traitor led to this very "fun" issue of no objectives as antag, which means DADG. This rectifies it by making reinforcements familiars.
Basically very problematic without it lmao. Also fixes admin "make antag" verb.
The entire system is hilariously garbage, this is a stand-in solution while a cleaner version might be created in the future.
- Make antag verb uses `.Last()`, which is why the `TraitorReinforcement` is being moved above `Traitor` (this makes makeantagverb give objectives)
https://github.com/user-attachments/assets/0d174895-9892-4a9c-8160-122fd13a3697
**Changelog**
:cl:
- fix: Syndicate reinforcement is now a familiar

Fix syndie reinforcement objectives

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Turrets/turrets_base.yml

Ports https://github.com/space-wizards/space-station-14/pull/38212/files
Any time there are more than 3 turrets per APC, the lights begin to flicker at an extremely fast pace, to the point where it can cause seizures.
fix: ai turrets shouldn't create flickering lights now

HOTFIX: Stop AI turrets from causing flickering lights

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Turrets/turrets_ballistic.yml

100hp->250hp
no longer explodes
nukies can buy
it's currently almost entirely useless since it's balanced around wizden, dehyd carp is better than it
so those stat changes are intended to make it good for defensive use
health raise seems large but reminder that it has no resistances and can't dodge so you just shoot it and it dies
you can easily kill it with a mech (available every round) or a basic gun and armor by just running at it
also it still has little dps so it should be fine
it exploding means you can't use it to defend a base so it has no usecase so i removed that
and nukies doing turret ops would be fun
**Changelog**
:cl:
- remove: Disposable ballistic turret no longer explodes.
- tweak: Disposable ballistic turret 100->250 hp.
- tweak: Nukies can now buy disposable ballistic …

buff syndi ballistic turret

---

Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
Resources/Changelog/GoobChangelog.yml

Shoves mispredicted before and had infinite range, no more.
This also fixes the lag, since the prediction didn't guarantee for objects to be properly set (so it spammed server console)
Bug
Slipped by when testing after moving to shared
https://github.com/user-attachments/assets/118258e6-db62-4665-b83c-1a1bdecdbf04
Double audio was fixed in the second commit of this PR, didn't re-record.
**Changelog**

(Hot)fix shove prediction

---

Resources/Prototypes/Entities/Objects/Devices/Circuitboards/computer.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Objectives/objectiveGroups.yml
Resources/Prototypes/Objectives/stealTargetGroups.yml
Resources/Prototypes/Objectives/thief.yml

Commented out any trace of Expedition Board steal objective.
Lavaland removed expedition board and migrate.yml'd any trace. Just commenting out any trace of the objective.
Discord bug fix: https://discord.com/channels/1202734573247795300/1381697906087821333
I commented so many lines. It's a very funny ( I may be insane )
**Changelog**
:cl:
- fix: Thieves have finally got with the times and no longer try to steal Expedition boards. It's been forever.

Bug fix life

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_Goobstation/Entities/Structures/Machines/lathe.yml

Moved the Appraisal Tool and Pickaxe recipe pack from normal lathe to Cargo Fab.
Fixes #3112
**Changelog**
:cl:
- tweak: Appraisal tools removed from Lathes and added to Cargo Fab.

SUPER DUPER HUGE RECIPE CHANGES!!!!

---

Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml

Gave the reflective vest the same reflect chance amount as the DEsword post-changes.
Crew are abusing the reflective vest to completely circumvent the AI turrets. The DEsword was slightly nerfed to prevent this. It simply is not fun having command grab a single reflective vest, which they have roundstard, and walk up to AI core to card it.
**Changelog**
:cl: OnsenCapy
- tweak: Reflective vest can no longer be abused to completely circumvent AI turrets.

Fix reflective vest oversight

---

Resources/Maps/_Goobstation/atlas.yml

Added new High Security Atmospherics doors to Supermatter containment. Provided some more windows to look at it through.
Built on Pheenty's prior brigmed work to give brigmed more space. Also swapped out the Station Records computer in brig for a Criminal Records computer as sec did not have one accessible to them outside Wardens office.
1984 for mice and TA's
Brigmed was a brig cell
**Changelog**
:cl:
- tweak: Atlas Supermatter containment got a minor facelift as well as having its access restricted to Atmos and CE
- tweak: Atlas Brig has had a minor facelift to make Bridmed larger and add Criminal Records Computer at the cost of one secway.

Atlas Supermatter/Security Mapping Changes

---

Content.Shared/Zombies/PendingZombieComponent.cs

The poison per second from an infection from 3 to 1.8
The time it takes to crit from a bite now without meds is from approx 33 seconds to 55 not accounting prior damage and with absolutely no poison meds which make the damage change irrelevant anyways.
Getting bit a single time by a mouse at mach 3 through cap/bso level armor and dying before even making it to med is honestly fucking awful. Zombies are lethal enough with speed, and the time from a single bite to crit makes it impossible to have even the slightest chance of getting to med. Yea, bites shouldn't be irrelevant just "make your way to med sometime within the next hour", but with the speed change not getting a single bite is honestly incredibly difficult, as well as armor is much shittier at preventing bites. We don't need it …

Make Zeds Fun Again

---

Resources/Maps/_Goobstation/bagel.yml

Replaced doors on Bagel SM containment with high security atmospherics doors.
Replaced Plasma Windows surrounding SM with Uranium windows
Gave Brigmed a bit of a facelift as it seemed a little bit rushed in it's initial iteration
Total TA Death
**Changelog**
:cl:
- tweak: Changed the SM containment's doors and windows for fresh models direct from Centcomm
- tweak: Gave Bagels Brigmed a makeover

Bagel SM + Brigmed Tweaks

---

Content.Shared/Damage/DamageSpecifier.cs

Fixes polymorph bug
Bug
FP2 Division operator of damage specifier was mysteriously missing a `.ArmorPenetration`, causing the new specifier to be a copy of the original instead, which caused a runtime error when the operator was trying to add already existing entries. This caused the polymorph process to fail at runtime, resulting in a creation of some urist.
https://github.com/user-attachments/assets/e529b353-bf0e-4ebd-a814-4c733e562b84
idk how to do bananium
**Changelog**
:cl:
- fix: Polymorphs no longer spawn urists

Fix polymorphs

---

Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Engineering/nails.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/nailgun.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Nailgun/nailgun.yml

Tweaked Nailgun stats to make it a little bit more balanced
In it's current state, the nailgun has an incredibly high damage output and a very low TTK. Combined with no spread to shots and the nailgun is incredibly overtuned.
The following tables provide the damage statistics for a full magazine:
| - | Naked | Armor Vest Non-AP | Armor Vest AP |
| - | ------- | ---------------------- | ---------------- | 
| Current Values | 200 Pierce | 48 Pierce | 172 Pierce | 
| Reduced Values | 120 Pierce | 22.8 Pierce | 97.2 Pierce | 
The armor vest used to test was a standard issue armor vest with 45% Piercing resist
1. Magazine size: 50 -> 40
2. Nail box size: 100 -> 80
3. Fire Rate: 12 -> 8
4. Standard Nail Damage: 5 -> 3
5. AP Nail Damage: 4 -> 3
6. AP Nail Piercing: 0.75 -> 0.65
Lathe prices for …

Tune down the nailguns damage output

---

Content.Goobstation.Common/CCVar/CCVars.Goob.cs
Content.Goobstation.Server/StationEvents/GameDirectorSystem.cs
Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusComponent.cs
Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusSystem.cs
Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs
Content.Server/StationEvents/EventManagerSystem.cs
Resources/Locale/en-US/_Goobstation/game-ticking/secretplus.ftl
Resources/Prototypes/DeltaV/GameRules/events.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/GameRules/pests.yml
Resources/Prototypes/_Goobstation/GameRules/events.yml
Resources/Prototypes/_Goobstation/GameRules/secretplus.yml
Resources/Prototypes/_Goobstation/game_presets.yml

- adds survival+: secret+ but no roundstart antags and it ramps up over time
- adds new debug cvars to try out secret+ event rolls in localhost
- tweaks a few chaos score values
- tweaks secret+ event-picking values since it was struggling to regulate its chaos budget
- minor fix in secret+ event picking logic
- adds chaos change variation: secret+ can now pick to generate more or less chaos for this round, but will still tend to pick closer-to-1 multipliers
more gamemodes more variety
if people don't want it they won't vote it anyway
should make entropy feel better
considering the new debug cvars now exist you can actually check out examples of event rolls ingame yourself by spoofing 60 players (minus some from 80 since dead players decrease chaos score) and 40x speedup or so
tested all …

survival+, more secret+ adjustments

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Resources/Prototypes/_Goobstation/MisandryBox/JobObjectives.yml

This very simple pr is to change the action needed to open and close the borg maints panel to a screw driver instead of a crowbar
I feel as if this is better in line will all other maints panels in the game which use the screwdriver the borg also did before recent changes 
Not much to say here this is one line of code change in yml 
I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl:
- tweak: Borg maint panel using a screwdriver to open and close once again

Changes the Borg maints panel back to using a screwdriver

---

Content.Goobstation.Shared/SetSelector/SetSelectorSystem.cs
Resources/Changelog/GoobChangelog.yml
Resources/Prototypes/_DV/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Resources/Prototypes/_Goobstation/Catalog/Fills/Belt/belts.yml
Resources/Prototypes/_Goobstation/Catalog/selectable_sets.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/CentralCommand/set_selectors.yml

I was promised 1k more GC to make an actual balance PR like I thought would be better instead of the complete revert I was originally told to.
The entire point of BSO was to be strong in defending heads as you only have one life with forced lifeline. BSO 100% got away with having too much in terms of powercreep, but in it's current state is dead, considering rounds of 85+ people having no BSO.
Revolver got hit stupid hard by less speedloaders considering the pheenty nerf that makes them have a wait time on recharge. Readding a lethal speedloader allows you to follow original intent (skill swapping loaders for consistent dps) while recharge keeps you from infinite chaining. 3 damage was also removed to make one loader 90 from 108 damage so while this allows Revolver to keep holding fire it …

[Technically Bounty?] Bso balancing but actually trying

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml

Changed the Syndicate Disaster victim to be a defector who is crew aligned as opposed to a free agent
We don't need more free agent spawns that can act as antags 
**Changelog**
:cl:
- tweak: Syndicate Disaster victims are now Crew Aligned

Syndicate Disaster Victim Reclassification 

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml

Reverts Goob-Station/Goob-Station#3342
Bandage fix instead of reminding admins of the rules they are supposed to be enforcing. 
Syndicate Survivours are still syndicates and should be able to keep their allegiances, or opt to be crew aligned at THEIR will. 
Free agent on top. 
:cl:
- tweak: Syndicate Disaster victims are returned to being Free Agents.

Syndicate Disaster Victim FreeAgentification

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml

Reverts Goob-Station/Goob-Station#3363
Syndicate disaster victims are not literal syndicate.
The syndicate is formed of several companies, i.e. cybersun, interdyne, etc etc.
The disaster victims are just normal crew from these corporations stations. No one is going to barely escape from their station getting nuked, get taken in my another station, and then instantly just go "durrrr I need to kill everyone"

Revert "Syndicate Disaster Victim FreeAgentification"

---

Content.Goobstation.Server/Weapons/DelayedKnockdown/DelayedKnockdownOnHitSystem.cs
Content.Goobstation.Shared/Inventory/GoobInventorySystem.Relays.cs
Content.Goobstation.Shared/MartialArts/SharedMartialArtsSystem.CorporateJudo.cs
Content.Server/_Shitcode/Heretic/EntitySystems/PathSpecific/ChampionStanceSystem.cs
Content.Shared/Damage/Systems/SharedStaminaSystem.cs
Content.Shared/_Shitcode/Weapons/Misc/TakeStaminaDamageEvent.cs

stamres wasn't working, upstream merge seemingly broke smth because of wizden stamina resistances
before (vid from goob discord):
https://github.com/user-attachments/assets/2c4a0039-77d3-46db-8926-706a1e08f6b0
after the fix:
https://github.com/user-attachments/assets/a9b95db0-c7bc-46ca-ba9b-cde752037bfa
yeah getting total stam res via the event of "what happens BEFORE taking exactly 1 stamina damage" is not really its correct use but hey it works as before, cant be fucked to unshitcode it
also why the fuck did we have completely unmarked goob files in core namespace, well im not goobmodding it
:cl:
- fix: Stamina resistances work once again.

fix stamres

---

Resources/Prototypes/Entities/Mobs/NPCs/pets.yml

Fixed the conflicting ghost role takeover saying Pun Pun is crew aligned with the role saying you're a free agent after you control Pun Pun.
Bug fix.
Pun Pun was inheriting MindRoleGhostRoleFreeAgent from the base monkey mob, so I added MindRoleGhostRoleNeutral to Pun Pun directly. I didn't test other monkey ghost roles, but I think those ones already have the Familiar mindrole, so they're probably fine.
Before the fix:
After the fix:
**Changelog**
:cl:
- fix: Pun Pun has been reminded of his contract and is no longer a free agent.

Makes Pun Pun no longer a free agent

---

Content.Shared/Zombies/ZombieComponent.cs

mald PR #4213123124 due to SCP:SL parity
i made zombies slightly slower, previously 1.05x speed, now 0.95
their infect chance is so high now that it just feels like a forced landslide victory speedrun for zeds. zeds used to be pretty slow before the buff but 0.95 still keeps basically CMO hardsuit parity, allowing you to actually run away and juke the AI (have you ever FOUGHT AI zombies? holy fuck they're fast bro)
literal component change
no
**Changelog**
:cl: router
- tweak: Made zombies move 5% slower than humans, from 5% faster previously. [font size=3]what the fuck I didn't know left for dead had runner zombies[/font]

VERY SLIGHTLY nerf zombie speed

---

Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/contractor_baton.yml

title
yaml
https://github.com/user-attachments/assets/b93638e3-bc0b-4015-a7d8-62ea94e09732
**Changelog**
:cl: the biggest bruh
- tweak: Contractor baton attack rate increased (1 -> 1.25) and the use delay when active has been decreased (2.5 -> 0.5)

decrease cooldowns on the contractor baton (bounty)

---

Content.Shared/Item/SharedItemSystem.cs

Ported https://github.com/funky-station/funky-station/pull/967 to fix some issues with slimes and pockets.
*This does not fix the welding torch somehow being in a container, but that's a bug that has existed for a while and is something to do with the welding torch specifically, I think.*
No longer should slimes have issues with tools placing into their storage due to the game innately choosing the storage, basically everything that was stated in the port PR.
This changes the inventory checking system, again, check the port PR.
My computer is simply on too slow of internet to upload videos, and screenshots will not suffice.
This might break stuff with inventory, but I didn't notice it when testing and I specifically tested with the telescopic spear and baton that was the initial change I …

[Port] Fix/Tweak Item Toggling for Slime and Pockets

---

Content.Shared/_Shitcode/Heretic/Components/DisgustComponent.cs
Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml
Resources/Prototypes/Entities/Objects/Weapons/security.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/blueshield.yml

Batons could insta stun by hitting, throwing, and disarming. No longer. Should keep time to stun values about the same.
:cl: Armok
- remove: Insta stun abuse
- tweak: Tweak stun batons to require sprite clicking to be effective

Fix insta stun + tweak batons

---

Content.Server/_DV/CosmicCult/CosmicCultSystem.cs
Content.Server/_DV/CosmicCult/EntitySystems/CosmicEntropyDegenSystem.cs
Content.Shared/_DV/CosmicCult/Components/CosmicNonCultistDebuffComponent.cs
Resources/Prototypes/_DV/CosmicCult/status_effects.yml

Made non cultists take more damage from cult weapons
It was always supposed to deal a lot of damage to non cultists before and it stopped dealing much damage at some point. It was dealing like 5 asphyx every 10 seconds at which point you would've just healed that asphyx damage. The downside was basically non-existent
Made a new system for non cultists using cult weapons so siphon doesn't deal a shit ton of damage. (Why didn't it have its own system in the first place??? It just reused the siphon system??)
Tested, works.
**Changelog**
:cl:
- tweak: Non cultists now take more damage when using cult weapons.

Makes it actually dangerous to use cult weapons as a non-cultist

---

.github/workflows/check-author-repoban.yml

Gives the public an option to soft repoban other users.
This is as much as "BANHIM!" as it is a roundabout way to force the issue.
Every contribution as follows (this excludes irrelevant or other non-notable PR's):
https://github.com/Goob-Station/Goob-Station/pull/1980 - gave traitors warden gear for no reason
https://github.com/Goob-Station/Goob-Station/pull/2020 - unprompted medkit buff
https://github.com/Goob-Station/Goob-Station/pull/2159 - new grenade for nukeops because "no area denial" as if suppressive fire doesn't exist
https://github.com/Goob-Station/Goob-Station/pull/2200 - Unwarranted cobra buff, inflates ammo types beyond a reasonable amount, adds M7S also for no reason other than serving own larp, invalidates Hristov with Heaven's Gate. …

Repoban JoeHamaSS14 on the crime of shitting it all up

---

Content.Server/NPC/Components/NPCSteeringComponent.cs
Content.Server/NPC/HTN/PrimitiveTasks/Operators/MoveToOperator.cs
Content.Server/NPC/Systems/NPCSteeringSystem.Context.cs
Content.Server/NPC/Systems/NPCSteeringSystem.cs
Resources/Prototypes/_EinsteinEngines/NPCs/fillbot.yml

- fixes jank stutter-movement observed under high server load
- potentially fixes more jank back-and-forth movement
- if you or the target coordinates are offgrid, NPCs will now attempt to move directly to you without pathfinding
- makes fillbot not brake because it doesn't need to
i have tested:
- space carp, offgrid and ongrid both target and source
- bunch of space carp jumping to attack me off a wreck
- spirates, offgrid and ongrid both target and source, with melee and with gun
- fillbot, ongrid, in grav and nograv
- approximately 400 mice strolling around on chloris (high server load test), jank that was before isn't there anymore
- space carp fighting spirate in melee in space
**Changelog**
:cl:
- fix: Fixed more NPC movement jank.
- fix: NPCs will now chase and attack you in …

HTN fixes round 3

---

Content.Client/PowerCell/PowerCellSystem.cs

Fixed powercell visuals with changing one bool from false to true. I guess it's wizden bug and it'll be fixed on upstream.
Client PowerCellSystem, line 69 -> _sprite.LayerSetVisible((uid, args.Sprite), PowerCellVisualLayers.Unshaded, false ->true);
**Changelog**
:cl:
- fix: Fixed power cells charge visuals.

[Fix] Powercell visuals

---

Resources/Prototypes/_Goobstation/Entities/Structures/Machines/power_laser.yml

i made the PTL significantly lighter and also made it rotatable
solves the issue of accidentally flinging PTL into space and not being able to bring it back even with jetpack  
also makes people not want to do that in the first place
no
no
no
**Changelog**
:cl: router
- fix: Power Transmission Lasers no longer have weights of small cargo ships, and can now be safely manipulated.

make PTL not be a neutron star

---

Content.Server/Atmos/EntitySystems/FlammableSystem.cs

I fixed the visual bug that retained the Fire Alert on your screen 24/7 after you have been lit aflame by any source.
Fixes #3539 
This adds the same alert clear to the extinguish function to trigger it. I'm not sure why the alert isn't clearing in the Update function, and I should probably try and fix that, but this is a blanket patch for redundancy. I'd like feedback if possible.
**Changelog**
:cl:
- fix: Fixed "On Fire" Alert Visual Bug. You can now be extinguished without it remaining on your screen.

[Fix] Flame Alert Visual Bug

---

Resources/Prototypes/Recipes/Lathes/Packs/medical.yml
Resources/Prototypes/Research/civilianservices.yml

If I turn up dead in the next month, the medbay mains did it.
Bluespace storage expansion. Put it behind medbay bluespace tech because they deserve it. 
Kill storage minmaxers with hammers.
read the yaml
Before unlock:
Unlock update: 
After unlock:
**Changelog**
:cl:
- tweak: Combat medkits now require research to unlock.

Remove combat medkit from static, add to science unlock.

---

Resources/Prototypes/Entities/Objects/Misc/kudzu.yml

Halves the chance any agresssive kudzu (or variant like fleshkudzu) has to spread 
Makes kudzu less ass to deal with
like a few numbers in one yml got tweaked 
Rouge (head of staff) said yes if this pr counts for balance/antag freeze slop (it really isnt)
**Changelog**
:cl:
- tweak: Halved kudzu, fleshkudzu (meat anom), floralkudzu (plant anom) vine spread speed.

Halve spreadChance on all kudzu variants that matter

---

Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusComponent.cs
Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusSystem.cs
Content.IntegrationTests/Tests/_Goobstation/SecretPlus/SecretPlusTest.cs
Content.Server/Antag/Components/AntagSelectionComponent.cs
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/GameRules/midround.yml
Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml

- now actually accounts for antag selection gamerules having variable amounts of antags
- should hopefully result in better-feeling roundstart antag rolls
- adjusts some chaos scores to account for changes
- devil 350 -> 150 chaos because why was it 350
- code cleanup
makes it more stable
tested, works
:trollface:
even if i were to post a video it'd not really tell you anything
**Changelog**
:cl:
- tweak: Secret+ should now be more stable in terms of roundstart antag count.

secret+ tweaks

---

Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/clowncar.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/vehicles.yml

updated speed of veichles by 1.4 +- rounding 
sprinting, "go do it yourself"
yml 
Not tested, works
**Changelog**
:cl:
- fix: Vehicles now move at 1.4 of their original values. This is due to spritning being added making them semi obsolete. Beware of clown cars.

Veichle sprinting adjustment

---

Resources/Prototypes/Species/moth.yml

Very simple change, increases the moth antennae marking limit (top, head) from two (2) to six (6), just as we had it pre-rebase.
1. It used to be this way prior to the rebase,
2. Why shouldn't we allow more options to make new pretty antennae from our options to our players? A higher limit means more options for mixing and matching existing markings to make your moth's antennae look way cooler.
3. I am sure that I am not the only pre-rebase player who made their characters antennae consist of at least 3 markings, so this makes the characters look the way they were supposed to.
(I opted for 6 rather than 3 for the limit just in case someone used more than 3 markings and so the limit wouldn't have to be increased AGAIN in the future. Besides like I said, it used to be exactly 6 in the …

Moth antennae (head, top) marking limit increase

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml
Resources/Prototypes/_Imp/Mobs/Customization/arachnid.yml
Resources/Prototypes/_Imp/Mobs/Customization/slimeperson.yml

some shader lines in yaml were incorrectly formatted causing the "glow" in the eyes to not work.
I like glowy eyes and having only one glowy eye pissed me off way too much.
Left Eye wasnt working:
Before:
After:
Jumper glowing eyes wasnt working:
Before:
After:
Slime Glowy eyes:
Before:
After:
**Changelog**
🆑 (KMano10000/ConfusedBumm)
- fix: Some glowing eyes not really glowing

Some Glowing eyes glow again!

---

Resources/Prototypes/Species/dwarf.yml
Resources/Prototypes/Species/human.yml
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/_DV/Species/harpy.yml
Resources/Prototypes/_DV/Species/rodentia.yml
Resources/Prototypes/_EinsteinEngines/Species/shadowkin.yml
Resources/Prototypes/_Floofstation/Species/resomi.yml
Resources/Prototypes/_Goobstation/Species/tajaran.yml

we knew this would happen, the same happened in EE
i dont know who thought allowing the small species to be even smaller was a good idea
resomi sprites look horrid when the sizes of oni's
and other species get so small, that theyre practically impossible to hit with any weapon or even to just chase them around
also because sprites look horrible when the sizes of cockroaches
species to be wider because wide = funny
**Changelog**
:cl:
- tweak: All species' minimum size has been raised.
- tweak: Species like dwarfs and humans can now be wider, rejoice

Raises minimum sizes for all species, makes some species wider

---

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs

This PR fixes some broken logic inside of `HumanoidProfileEditor.xaml.cs`. 
- Species appropriate default values will now be selected when pressing a slider's `Reset` button, instead of using the first species (in our case, Reptillian, which uses the Human's) default values.
- Loading a character profile with a species that has different minimum/maximum width/height values will no longer cause a wildly incorrect width/height value to be applied to that profile. ~~(incorrect values are still loaded, but the values which are loaded are now closer to the ones that should be loaded, so this is partially fixed. to ACTUALLY solve this issue, you would need to devise a way to change the minimum and maximum values of a slider without clamping the value of the slider, and I'm not about to make …

Updated Height/Width slider logic inside of HumanoidProfileEditor

---

Content.Goobstation.Server/Power/PTL/PTLSystem.cs
Content.Goobstation.Shared/Power/PTL/PTLComponent.cs

closes #3828 
Balances and fixes PTL issues.
Along to addressing several issues with the PTL
PTL was capable of generating free spesos whilst not using the battery charge, in addition the PTL's "shot" maximum in minium power per shot was changed that at maximum the PTL exchanges up to 592 Spesos per shot which means (5920 Spesos per minute if fire delay is 10 seconds by default and it has enough power).
Before the power per shot change the PTL would be capable of eatting it's entire battery in a single shot, which defeats a purpose of a battery and instantly generates a huge amounts of spesos.
- Prevents radiation intensity from going negative.
- Caps energy consumption and damage based on the component's energy limit, preventing exploits.
- Calculates spesos and evil effect based on …

closes #3828 - Fixes & Balances PTL from being able to make free spesos

---

Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/cigar.yml
Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
Resources/Prototypes/Entities/Objects/Tools/lighters.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Tools/lighters.yml

You can stick Zippos in Cigarette Boxes again.
Also you can now specifically insert premium Havanian cigar's into them too
Also increased cigarette burn time by 20%
I don't need a good reason for the flippo because um it's not really that deep
Also some of us like to find a premium cigar for evac, don't think we need to wring hands about smokers finding efficient methods of inventory management
Finally it's become too easy to smoke a full pack in a single shift, Nanotrasen's Anaerobic Health department suggests only smoking 8 cigarettes per shift and instead sharing spares with tiders, the clown and any aliens you find in maints
In the time between thinking of doing this, making the changes and creating this PR I have been fiending for a cigarette. Which I will now go for
**Changelog** …

Make Smoking Great Again

---

Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/bingle.yml
Resources/Prototypes/_Shitmed/Actions/abductor.yml

- fix abductors not being able to do anything
- remove raffle from bingle its a fucking spam role like carp
bingle eye is probably unaffected
shitcode was using the wrong parent so eye could never use actions
**Changelog**
:cl:
- tweak: Removed raffle from spawned bingle ghost roles.
- fix: Fixed abductors not being able to do anything.

fix abductor + bingle goidacode

---

Content.Server/GameTicking/Rules/Components/TraitorRuleComponent.cs
Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
Content.Shared/Actions/SharedActionsSystem.cs
Resources/Locale/en-US/_Goobstation/datasets/corporations.ftl
Resources/Locale/en-US/_Goobstation/flavors/corporateagent.ftl
Resources/Locale/en-US/_Goobstation/flavors/traitor.ftl
Resources/Prototypes/_Goobstation/Datasets/corporate_flavor.yml
Resources/Prototypes/_Shitmed/Actions/abductor.yml
Resources/Prototypes/_Shitmed/Entities/Clothing/Head/helmets.yml
Resources/Prototypes/_Shitmed/Entities/Clothing/OuterClothing/armor.yml

Fixes https://github.com/Goob-Station/Goob-Station/issues/3879
Fixes https://github.com/Goob-Station/Goob-Station/issues/3806
**Changelog**
:cl: Local schizophrenic
- fix: Fixed abductor helms protecting their other head and not the main one.
- fix: Fixed abductor's console, it now properly tells you if you're not in FTL range again, and lets you actually teleport or exit.
- fix: Fixed traitors missing their flavor text and code in uplink.

Fixes abductor issues with the console, and traitor flavor in char menu.

---

Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Species/shadowkin.yml

Gave shadowkins back their left leg (at least visibly) 
Fixes #3872 
Idk what was going on in that marking's PR but for some reason StencilClear was commented out and StencilMask wasn't properly formatted so shadowkin sprites just stopped showing their left legs. 
Also [ummmmmmmmmmmmmmmm](https://github.com/space-wizards/space-station-14/pull/12217#issuecomment-1291677115)
:cl:
- fix: Shadowkin Left Legs are visible again

Fix Shadowkin's having no visible left leg

---

Resources/Prototypes/_DV/CosmicCult/Tileset/walls.yml

fix that was never ported here so you were just able to instantly rcd deconstruct everything
since it had 0 time
:cl:
- fix: Fixed being able to RCD away cosmic cult walls and windows instantly.

fix coscult stuff being instantly rcdable away

---

Resources/Prototypes/_Goobstation/Reagents/fun.yml
Resources/Prototypes/_Goobstation/Reagents/narcotics.yml

added the thing weh juice has where it removes the reagent
this fixes transforming back into a mouse 1000 times because your original body doesnt metabolize in nullspace
same for carpolin
:cl:
- fix: Going crit as a transformed mouse/carp no longer "stunlocks" you by transforming over and over.

fix mousebites "stunlock" when crit

---

Resources/Prototypes/_White/Actions/xenomorph.yml
Resources/Prototypes/_White/Entities/Structures/Furniture/resin_weed.yml
Resources/Prototypes/_White/Entities/Structures/Walls/resin.yml
Resources/Prototypes/_White/Entities/Structures/Windows/resin.yml

Updates grass / walls / windows to rmc sprites. Current ones are ugly
New sprites
Old sprites
**Changelog**
:cl:
- tweak: Updated xenomorph weeds / walls / windows to rmc sprites

Updating xenomorph sprites

---

Content.Server/GameTicking/Rules/ZombieRuleSystem.cs
Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Species/plasmaman.yml

This PR adds a check to ensure zombie immune species such as (IPC's) are unable to get initial infected.
It's a bug
- In `Content.Server/GameTicking/Rules/ZombieRuleSystem.cs` added `zombieImmune.HasComponent(uid) // Goobstation` to the `GetHealthyHumans` check.
**Changelog**
:cl: Richard Blonski
- fix: Zombie Immune species shouldn't get initial infected anymore.

Hotfix: Zombie Immune spieces being selected as intial infected

---

Content.Goobstation.Server/Speech/ListenBlacklistSystem.cs
Content.Goobstation.Shared/Speech/ListenBlacklistComponent.cs
Resources/Prototypes/Entities/Objects/Devices/radio.yml
Resources/Prototypes/Entities/Structures/Wallmounts/intercom.yml

intercoms and handheld radios no longer listen to anything with Advertise: vending machines, medibot (the old meta), goidabot...
:cl:
- tweak: Intercoms and radios no longer spam everything vending machines or bots say.

nerf intercom spam

---

Content.Server/_White/Xenomorphs/FaceHugger/FaceHuggerComponent.cs
Content.Shared/_White/Xenomorphs/XenomorphShoveTracker/XenomorphShoveTrackerComponent.cs
Resources/Locale/en-US/_Goobstation/access/accesslevel.ftl
Resources/Locale/en-US/_Goobstation/collective-mind/collective-mind.ftl
Resources/Prototypes/_Goobstation/Access/xenomorph.yml
Resources/Prototypes/_Goobstation/CollectiveMind/collective_minds.yml
Resources/Prototypes/_Goobstation/Entities/Structures/Doors/Airlocks/access.yml
Resources/Prototypes/_Goobstation/tags.yml
Resources/Prototypes/_White/Actions/xenomorph.yml
Resources/Prototypes/_White/Body/Organs/Animal/xenomorph.yml
Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/base.yml
Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/drone.yml
Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/praetorian.yml
Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/queen.yml
Resources/Prototypes/_White/Entities/Structures/Doors/resin.yml
Resources/Prototypes/_White/Entities/Structures/Walls/resin.yml
Resources/Prototypes/_White/GameRules/events.yml

Added super weak xenomorph doors. They die to three welder hits. It's basically only good so you aren't forced to fully close off a hallway that you might need to go into
Removed xenomorph Resin Windows. They had no real use as xenomorphs have thermal vision, and screwed over the hive because you could shoot lasers through it.
Nerfed xenomorph wall health to help combat wall spamming
Nerfed xenomorph healing as it basically just made xenomorph queens immortal
Nerfed the stun. It still allows them to perma stun people but now they actually have to pay attention to who they're stunning or they could get back up in a reasonable amount of time
Facehuggers not latching to people is a huge issue so hopefully the lowered rest time will help it
Acid spit now does heat damage so the larger xeno's …

Xenomorph stuff

---

Content.Client/Clothing/ClientClothingSystem.cs

Fixes: #4137
Fixes: #4137 
- Removed goida code from `Content.Client/Clothing/ClientClothingSystem.cs`
```
if (slot == Jumpsuit)
layerData.Shader ??= "StencilDraw";
```
**Changelog**
:cl: Clinux & Richard Blonski
- fix: Fixed Jumpsuits not rendering properly on Humanoid species.

Fixes: #4137 No more Nudist Station

---

Resources/Prototypes/_Shitmed/Reagents/narcotics.yml

Upstream broke how WonderprodNocturine works, is working now
blease bro i wanna play the cool new duo abductor game mode but this glorpshit doesn't sleep blease. (could probably lower the minimum and raise the metabolism rate so abductors don't need to hit as much to sleep, but that's a balance change and i'm just here for bugfixing)
Idk how you're supposed to make it "refreshes so hitting someone with wonderprod 10 times doesnt put them to sleep for an hour," but wonderprod nocturine maxes out at 20u like in the video, and stops applying sleep at 8u, so I guess that's fine? I timed it at about 20 seconds of sleep after they stop hitting you, which seems fine for the original purpose of https://github.com/Goob-Station/Goob-Station/pull/4026 …

Fixes wonderprod sleep mode

---

Resources/Locale/en-US/_Goobstation/set-selector/selectable-sets.ftl
Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
Resources/Locale/en-US/store/uplink-catalog.ftl
Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/softsuits.yml
Resources/Prototypes/_EinsteinEngines/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/apocryphal.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/corporate.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/engineering-responsory.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/inquisitory.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/janitorial-responsory.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/leader-responsory.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/medical-responsory.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/praetorian.yml
Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/security-responsory.yml
Resources/Prototypes/_Goobstation/Catalog/Fills/Backpacks/duffelbag.yml
Resources/Prototypes/_Goobstation/Catalog/Fills/Crates/armory.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Back/modsuit.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Hands/modsuit.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Head/modsuit.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Head/voidsuit-helmet.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/modsuit.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/Shoes/modsuit.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Misc/voidsuitselectors.yml
Resources/ServerInfo/Guidebook/Engineering/SingularityEngine.xml
Resources/ServerInfo/Guidebook/Mobs/Plasmaman.xml

Re-renames voidsuits to hardsuits/tacsuits and hardsuits to modsuits.
**Changelog**
:cl:
- tweak: Spacesuit naming scheme is no longer arbitrarily different from everywhere else

Kill Voidsuits

---

Content.Server/_EinsteinEngines/Language/LanguageSystem.cs
Content.Shared/_EinsteinEngines/Language/Components/UniversalLanguageSpeakerComponent.cs
Content.Shared/_EinsteinEngines/Language/Systems/SharedLanguageSystem.cs
Content.Shared/_EinsteinEngines/Revolutionary/RevolutionaryConverterSystem.cs

Added a check for the RevolutionaryConverterComponent that, if the chosen Converter object uses spoken lines, the spoken language must be understood by the target for conversion to succeed.
This prevents someone from learning an obscure language and converting everyone quickly. Conversion happens largely via speech, so this speech should be understood. Also makes languages relevant for Revolutionaries in a positive way, instead of an easily abusable method of free conversion.
I just check the current selected language against the known languages of the target.
I did move a check from Server to Shared so I could check for understood languages in the RevolutionaryConverterSystem
**Changelog**
:cl:
- fix: Head Revolutionaries must now speak a language their target actually understands to …

Revolutionary Conversion Accounts for Languages

---

Content.Goobstation.Server/Devil/DevilSystem.Handshake.cs

intuitive counterplay to devil, cut his hands off and no more handshake
also no bingle handshake fixes #4159
:cl:
- fix: Fixed devils being able to offer handless mobs handshakes, or do so when they have no hands.

make devil handshake require a hand

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Fix #4193 
I did not do anything else at all do not even check the code changes just speedmerge
:cl:
- add: Added Mining Shuttle board to QM locker
- remove: Removed Salvage Shuttle board from QM Locker

Add Mining Shuttle board to QM Locker

---

Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/mechs.yml

Fix #4155 (For the most part)
H.O.N.K mech retains the ability to sprint but it's only a tiny difference in speed
All other mechs have had their basesprintspeed and basewalkspeed made equal (Yaml fix do something about it)
Ripley MK2 is disasterously slow, so I bumped its speed
Mech's dont have a downside to sprinting such as stamina drain so it's a bit ass.
**Changelog**
:cl:
- remove: All mechs (Except the H.O.N.K) can no longer sprint
- tweak: Doubled the move speed of the Ripley MkII (It's still pretty damn slow)
- tweak: Clarke movespeed increased from 2.5 to 3.5

Mech Tweaks

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml

makes combat medkit and combat medipen cheaper in uplink
spending your tc on consumabels feels Bad when you have other options which are more permanent
also these options inadvertently got nerfed by making topicals Shit and making brute and burn medipens aquirable by crew (therefore you have less reason to spend your tc on something you can just get for just a little effort) 
slop
**Changelog**
:cl:
- tweak: Medical items in Uplink are now cheaper in TC: Combat medkit 15->10, combat medipen 12->8, advanced medipen 28->20.

slop tot med consumables buff

---

Content.Goobstation.Shared/Overlays/SwitchableOverlaySystem.cs
Content.Goobstation.Shared/Overlays/SwitchableVisionOverlayComponent.cs

This PR networks the IsEquipment field of the `SwitchableVisionOverlayComponent` by adding it to the `SwitchableVisionOverlayComponentState`
Fixes a bug. Previously, if night vision was added to a piece of equipment by the server, and the IsEquipment field was set to true on the server, it would not work on the client, as the IsEquipment field would be false clientside.
Three lines of C#. One line for the component state, one line for the `OnGetState()` method, one for the `OnHandleState` method.
none needed (i think)
**Changelog**

Network IsEquipment field for night vision

---

Resources/Prototypes/Roles/Antags/revolutionary.yml

GOIDAMERGE THIS NOW!!!!
if you want actual reasoning: hmm today i will make the people who decide the entire flow of the round need 10 hours on tider to achieve YEA RIGHT
yml (lmao)
**Changelog**
:cl:
- tweak: Headrev time requirements made into 10 hours command instead of 10 hours overall

Headrev hours changed from 10 hours overall to 10 hours command

---

Content.Shared/Implants/SharedImplanterSystem.cs
Resources/Prototypes/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/_EinsteinEngines/Objects/Misc/translator_implanters.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/mindcontrol_implant.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/subdermal_implants.yml
Resources/Prototypes/_Goobstation/Objects/Misc/translator_implanters.yml

- Now implanters have label of containing implant. Label disappear after implanting and appears again after implant drawing.
- All implanters were renamed to just "implanters" to prevent metagaming.
I have no idea why this wizden change was reverted on goob. It was good anti-metagame change.
Resolves: #4470
**Changelog**
:cl:
- tweak: All implanters now have generic names to prevent metagaming.
- tweak: All implanters now auto-label themself with containing implant's name. Label disappear after implanting and appears against after implant drawing.

[Tweak] Implanters de-metagaming

---

Resources/Prototypes/_Goobstation/Devil/contract.yml

devil contracts are le infinite point farm
didnt test btw
**Changelog**
:cl: LuciferEOS
- fix: Devil contracts now are worth 0 points for the NTR.

[FIX] another ntr point glitch
