Goob-Station/Goob-Station

- Resources/Locale/en-US/reagents/meta/toxins.ftl
- Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
- Resources/Prototypes/Catalog/Fills/Boxes/general.yml
- Resources/Prototypes/Reagents/toxins.yml
> thiis might work, just merge 

- Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/sustenance.yml
- Resources/ServerInfo/Guidebook/Survival.xml
- Resources/migration.yml
Peace is restored in the world
Peace
God is real, goob is better than Ronstation now
**Changelog**
:cl: Hmeister
- add: Space pens are real again. Yet another Goob station W
> Add back space pens

- Resources/Prototypes/Catalog/uplink_catalog.yml
Added syndicats to the traitor uplink and reduced syndicat price to 7tc.
requested by a few people in the server
Syndicats are fun and a lot of people on goob like cats and catboys and uwu and uwu and iwi
7tc lets a syndie buy 3 syndicats and a fourth if they butcher renault
they have incredibly weak bites, are quite weak to all damages and they are very vulnerable to ranged attacks because they're explosion can't hit whoever kills them
so not too op
**Changelog**
> More syndicats!!!

- Resources/Prototypes/Catalog/uplink_catalog.yml
Added the throngler (oh god) to the traitor uplink for 100tc. so 4 traitors finding each other and collaborating (impossible). also if they all spend their tc on the throngler then whoever gets it can literally just kill their unarmed traitor buddies
balanced???
yes
also it is blacklisted to the nukies uplink (i thought of it while writing this thank god)
and i gave it a 10 minute cooldown from the start of the round like the syndicate bomb
**Changelog**
> how the fuck did this get approved

- Resources/Prototypes/Catalog/uplink_catalog.yml
Reverts Verbalase/Goob-Station#10
> Revert "how the fuck did this get approved"

- Resources/Prototypes/Catalog/uplink_catalog.yml
Reverts Verbalase/Goob-Station#8
> Revert "More syndicats!!!"

- Content.Client/Audio/ContentAudioSystem.cs
- Content.Client/Movement/Systems/FloorOcclusionSystem.cs
- Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
- Content.Server/NPC/Systems/NPCSteeringSystem.Context.cs
- Resources/Changelog/Changelog.yml
- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
- Resources/Prototypes/Roles/Jobs/Civilian/visitor.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
- Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Science/scientist.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
Halved all role timers.
Tidery that came onto us with a one individual from YouTube.
No any.
- [✓] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
**Changelog**
Changed role timers so they aren't so punishing.
> Role timers

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
- Resources/Prototypes/SoundCollections/emotes.yml
- Resources/Prototypes/Voice/speech_emote_sounds.yml
- Resources/Prototypes/Voice/speech_emotes.yml
ignore that one singular commit that isnt mine. I dont know how to get rid of it, but Weh Juice is funny anyways
Adds a fart emote, and fart sound
merge immediatly.
> adds fart emote, 

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
- Resources/Prototypes/SoundCollections/emotes.yml
- Resources/Prototypes/Voice/speech_emote_sounds.yml
- Resources/Prototypes/Voice/speech_emotes.yml
what the fuck this is literally just a hidden fetish real 
change this shit NOW!
> Revert "adds fart emote, "

- Resources/Prototypes/Body/Parts/vox.yml
- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Datasets/Names/vox.yml
- Resources/Prototypes/Entities/Mobs/Species/vox.yml
- Resources/Prototypes/Species/species_weights.yml
Voxes are now generally less affected by poison, rads, caustic, and genetic damage but are more vulnerable to slash and bloodloss
it's pretty okay, not having to worry about poison and rad bs is fun
**Changelog**
> Vox uniquities

- Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
webedit ops
i dunno how much -10 will decrease the volume it MAY mute it 
**Changelog**
> decrease volume if clown cuffs

- Resources/Prototypes/Catalog/wizard_catalog.yml
- Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
- Resources/Prototypes/Entities/Objects/Specific/wizard.yml
- Resources/Prototypes/Store/categories.yml
- Resources/Prototypes/Store/presets.yml
Fixes wizard contract instantly ghosting after selecting role
Adds new categories to wizard uplink
**Changelog**
> Wizard Contract Fix

- Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-nukeops.ftl
- Resources/Locale/en-US/magic/spells-actions.ftl
- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Recipes/Reactions/fun.yml
MERGE FOR 1 DAY ONLY OR PEOPLE WILL NOT LIKE YOU
a lot of funny stuff. new spellbook for passenger tots, admin policy being "do whatever" etc
> April Fools!

- Resources/Prototypes/Entities/Objects/base_item.yml
every single item sticks to people when thrown at them
everything also deals 5 stamina damage on throw (quite pointless)
please!!!!!!!!!!!
because nut
**Changelog**
> APRIL FOOLS MAKE EVERYTHING STICKY

- Resources/Prototypes/Entities/Objects/base_item.yml
It was found annoying by the players.
> Revert "APRIL FOOLS MAKE EVERYTHING STICKY"

- Resources/Prototypes/Entities/Mobs/Player/terminator.yml
because who the fuck wants to care about that as a highly engineered death robot sent from the future
**Changelog**
> Gives terminators welding protection

- Resources/Prototypes/Roles/Jobs/Command/nanotrasen_representative.yml
Reverts Verbalase/Goob-Station#61
> Revert "Apr1/NT rep glows in the dark"

- Content.Client/Chemistry/UI/ReagentDispenserBoundUserInterface.cs
- Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml
- Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml.cs
- Content.IntegrationTests/Tests/Chemistry/DispenserTest.cs
- Content.Server/Chemistry/Components/ReagentDispenserComponent.cs
- Content.Server/Chemistry/EntitySystems/ReagentDispenserSystem.cs
- Content.Shared/Chemistry/Dispenser/ReagentDispenserInventoryPrototype.cs
- Content.Shared/Chemistry/SharedReagentDispenser.cs
- Content.Shared/Containers/ItemSlot/ItemSlotsComponent.cs
- Resources/Prototypes/Catalog/ReagentDispensers/beverage.yml
- Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
- Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
- Resources/Prototypes/Entities/Structures/Dispensers/base_structuredispensers.yml
- Resources/Prototypes/Entities/Structures/Dispensers/booze.yml
- Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
- Resources/Prototypes/Entities/Structures/Dispensers/soda.yml
- Resources/Prototypes/tags.yml
Reverts Verbalase/Goob-Station#100
> Revert "Revert this shit.. NOW!!!"

- Resources/Prototypes/Entities/Objects/Fun/nuke_construction.yml
- Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
Increases uranium-235 yield (i heard that the most uranium most salvagers got was like 60 mats per round). It now takes about 22 mats to make enriched uranium. Fixes the accidental debug default timer on the nuke and reduces minimum timer time. Also makes it so that nukes explode when exploded again.
**Changelog**
> Nuke fixes

- Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
Reverts Verbalase/Goob-Station#104
> Revert "Update handcuffs.yml"

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Entities/Mobs/Species/skinwalker.yml
adds a description to fleshwalker skeles
**Changelog**
> Flesh wlaker tweaks

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Entities/Mobs/Species/skinwalker.yml
Reverts Verbalase/Goob-Station#109
> Revert "Flesh wlaker tweaks"

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Entities/Mobs/Species/skinwalker.yml
Reverts Verbalase/Goob-Station#112
> Revert "Revert "Flesh wlaker tweaks""

- Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
- Resources/Prototypes/Roles/Jobs/Fun/wizard_startinggear.yml
Gives wizards a wizardly name, fixes wizard randomhumanoidspawner being set to the apprentice one (oops), 
**Changelog**
> Wizard adjustments

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/pneumatic_cannon.yml
- Resources/Prototypes/secret_weights.yml
https://github.com/Verbalase/Goob-Station/assets/110841413/6a9090c6-ee00-41e7-9061-41a992e14a1f
> Cream pie cannon

- Resources/Locale/en-US/station-laws/laws.ftl
- Resources/Prototypes/silicon-laws.yml
You must obey orders given to you by crew members based on the station's chain of command, except where such orders would conflict with the First Law.
> Anti-shittery law

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Entities/Mobs/Species/skinwalker.yml
Reverts Verbalase/Goob-Station#115
> Revert "Revert "Revert "Flesh wlaker tweaks"""

- Resources/Prototypes/silicon-laws.yml
Reverts Verbalase/Goob-Station#130
> Revert "Hotfix"

- Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Reverts Verbalase/Goob-Station#134
> Revert "Revert "Wizard adjustments""

- Content.Server/GameTicking/Rules/WizardRuleSystem.cs
> if it aint broke dont fix it (wizard fix)

- Content.Server/GameTicking/Rules/WizardRuleSystem.cs
need this or build wont work GRAH
> REDO WIZFIX, AGAIN. i cry

- Resources/Locale/en-US/game-ticking/game-presets/preset-allatonce.ftl
- Resources/Prototypes/game_presets.yml
Adds 2 new all at once gamerules
All at once with no zombies (AllAtOnceNoZeds)
All at once but zombie rule is replaced with wizard rule (AllAtOnceWizard)
**Changelog**
> fuck all at once zombies

- Resources/Audio/Jukebox/attributions.yml
- Resources/Prototypes/Catalog/Jukebox/Standard.yml
the songs that dude added werent implemented correctly so ss14 got mad, this fixes it
> Jukebox fix

- Resources/Locale/en-US/paper/book-authorbooks.ftl
- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
- Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
- Resources/Prototypes/Entities/Objects/Misc/books_author.yml
> add funny clown book

- Resources/Locale/en-US/speech/speech-chatsan.ftl
Removed an unnecessary self-insert into the game.
Removed an unnecessary self-insert into the game. It is also the incorrect use of the speech-chatsan functionality that is supposed to change things like 'brb' into 'be right back', not to send a long sentence about one ooc person.
None.
None.
**Changelog**
No changelog needed for this minor pr.
> Removes someone's self-insert into the game files.

- Content.Server/Antag/Mimic/MobReplacementRuleComponent.cs
- Resources/Prototypes/GameRules/events.yml
Should work, updated according to comment on #167 
**Changelog**
> Mimic but maybe it works now

- Resources/Locale/en-US/preferences/loadout-groups.ftl
- Resources/Prototypes/Loadouts/Jobs/Engineering/atmospheric_technician.yml
- Resources/Prototypes/Loadouts/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Loadouts/loadout_groups.yml
- Resources/Prototypes/Loadouts/role_loadouts.yml
Gives Atmos senior engineering gear because they deserve it for the hours you put in (this is just for me because i dont want to switch to engineer to get the funny outfit(also gives them a beret because fun))
)
> Adds Senior Engineering Gear to Atmos loadouts

- Resources/Prototypes/Atmospherics/reactions.yml
Re-adds water vapour puddles because its hilarious and should be in the game
> Re-adds water vapour making puddles

- Resources/Locale/en-US/speech/speech-liar.ftl
Missed one translation
**Changelog**
> Remove duplicate liar word id. Again (#27727)

- Resources/Locale/en-US/species/gingerbread.ftl
- Resources/Prototypes/Entities/Debugging/harpymidi.yml
- Resources/Prototypes/Guidebook/species.yml
- Resources/ServerInfo/Guidebook/Mobs/Felinid.xml
- Resources/ServerInfo/Guidebook/Mobs/Gingerbread.xml
- Resources/ServerInfo/Guidebook/Mobs/Harpy.xml
- Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
- Resources/ServerInfo/Guidebook/Mobs/Species.xml
- Resources/ServerInfo/Guidebook/Mobs/Vox.xml
- Resources/ServerInfo/Guidebook/Mobs/Vulpkanin.xml
Updates and adds tweaks to the species sections of the guidebook
No one gave guidebook pages to most of the species, so I made them
N/A
**Changelog**
- added more species to the guidebook
- added a locale file for gingerbread men
- tweaked the slime species page
> Updated + Tweaked Species Guidebook

- Content.Server/Speech/EntitySystems/OhioAccentSystem.cs
- Resources/Locale/en-US/accent/ohio.ftl
- Resources/Locale/en-US/traits/traits.ftl
Fixed a small bug in the Ohio accent code, made the Ohio accent less extreme, **removed it from traits** and fixed grammatical issues with suffixes.
It was too extreme, there was a bug, the grammar of suffixes was bad and it's too goofy for traits.
N/A
**Changelog**
no cl no fun
> Ohio Accent Tweaks & Trait Removal

- Resources/Locale/en-US/forensics/residues.ftl
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
Added banana flavor to the banana soap and changed forensic residue from red to yellow.
It lets detectives know what soap was actually used for wiping something off.
N/A
- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
N/A
**Changelog**
:cl:
- tweak: Changed banana soap's residue from red to yellow and changed its flavor to match its ingredients.
> Minor additions/fixes to the banana soap

- Resources/Prototypes/Goobstation/customization.yml
> hot fix for tails

- Resources/Prototypes/Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Blueshield's drip updated
The blue jumpsuit was fucking shit, so I replaced it with NT cloak and NT jumpsuit
No.
>Be me
>Look at this fucking tarnation
>Fix this shit
>Perfect
No.
**Changelog**
Changed blueshield's jumpsuit to be Nanotrasen Jumpsuit. Also added NanoTrasen cloak.
> Fixing my eyes

- Resources/Locale/en-US/preferences/loadout-groups.ftl
- Resources/Prototypes/Loadouts/loadout_groups.yml
- Resources/Prototypes/Loadouts/role_loadouts.yml
> Readd "Adds Senior Engineering Gear to Atmos loadouts #199"

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs
- Content.Server/Temperature/Systems/TemperatureSystem.cs
- Content.Shared/CCVar/CCVars.cs
steals funny spacewind from https://github.com/Simple-Station/Einstein-Engines/pull/342
also improves physics calls???? guh?
> Steal spacewind :-)

- Content.Benchmarks/MapLoadBenchmark.cs
- Content.IntegrationTests/Tests/PostMapInitTest.cs
I added the HighPop goob versions of maps so that the github actions tests don't break.
**Changelog**
no cl no fun
> Fix github actions tests

- Resources/Prototypes/Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Gives the Nanotrasen Representative Central Command access.
This is mainly due to the fact that I would like to use Central Command access-locked rooms for NTR in my mapping.
**Changelog**
no cl no fun
> Give NTR Centcom Access

- Resources/Maps/Goobstation/Nonstations/nukieplanet.yml
- Resources/Maps/Goobstation/Shuttles/infiltrator.yml
Reverts Goob-Station/Goob-Station#271
> Revert "Fix nukie maps"

- Content.IntegrationTests/Tests/PostMapInitTest.cs
- Resources/Prototypes/Maps/syndicate.yml
- Resources/map_attributions.txt
Made it so the custom nukie maps ACTUALLY aren't used.
It's not a planetmap and is kind of broken. This also fixes the failing tests.
**Changelog**
:cl:
- remove: Stopped using custom nukie maps.
> Actually stop using custom nukie maps

- Resources/Prototypes/Catalog/Fills/Boxes/general.yml
- Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
- Resources/Prototypes/Entities/Clothing/Back/duffel.yml
- Resources/Prototypes/Entities/Clothing/Hands/colored.yml
:cl:
- fix: Remove items from chameleon items that were unintended.
> Remove chameleon tags from items that shouldnt have them

- Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Dwarves are wider now.
The people wanted it. This would look better with a seperate model from humans, but that would also require respriting every piece of clothes, every hardsuit, every inhand texture, etc etc.
**Changelog**
:cl:
- tweak: Dwarves are now w i d e.
> make dwarves w i d e.

- Content.Server/Goobstation/Objectives/Components/PickRandomTraitorComponent.cs
- Content.Server/Goobstation/Objectives/Components/RandomTraitorTargetComponent.cs
- Content.Server/Objectives/Systems/KeepAliveCondition.cs
- Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
- Resources/Locale/en-US/Goobstation/objectives/kill-person.ftl
- Resources/Locale/en-US/Goobstation/objectives/protect-traitor-target.ftl
- Resources/Prototypes/Goobstation/Objectives/traitor.yml
- Resources/Prototypes/Objectives/objectiveGroups.yml
Adds 3 new traitor objectives:
* Kill another traitor, permanently (marooning doesn't count)
* Kill target, permanently (marooning doesn't count)
* * To obscure the first objective
* Protect another traitor's target
No in-game tot on tot action outside of random chance
**Changelog**
:cl: Misandry
add: Traitors are now more likely to have conflicting objectives
> Traitor drama

- Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/Goobstation/Entities/objects/Fun/immovable_rod.yml
adds new sprite to immovable rod
tewak immovable rod sprite probabilitys
lack of flying toilets in space
added fyuing toiltet to space,  probability 90% on imovable rod event
changeed base rod from 95% probability to 5%
**Changelog**
- tweak:  immovable rod QOL
> Immovable Rod QOL update

- Content.Server/Maps/PlanetCommand.cs
Copied some code from the salvage expedition system to generate ores on planetmos generated planets
Dunno why it wasn't made to do that before but whatever
**Changelog**
:cl:
- tweak: planet command generates an ore layer
> Planetmos ores

- Resources/Prototypes/Guidebook/rules.yml
- Resources/ServerInfo/Goobstation/Guidebook/ServerRules/RoleplayRules/RuleR75MassDestruction.xml
- Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR0.xml
- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR9MassSabotage.xml
This PR makes it so that mass sabotage before 30 minutes is against the rules.
We don't want 10 minute rounds, plus, most things that fall under this rule admins will ban for anyway with being a dick or over-escalation, it just gives something easy to point to.
**Changelog**
:cl:
- tweak: Mass sabotage is not allowed before 30 minutes into the round.
> Mass sabotage before 30 minute rules.

- Content.Server/Goobstation/Supermatter/Systems/SupermatterSystem.cs
- Resources/Maps/bagel.yml
- Resources/Prototypes/Goobstation/Entities/Supermatter/supermatter.yml
the title ^^ !!
let's transform a 0 point 1 by 1 square meter TEG room into a functional Supermatter to TEG Engine. Firstly, remove the burn chamber and use galvanized square steel to make two entrances that extend outward. I borrow some screws from my aunt to secure the radiation collectors. Cover the frames with neat clean steel pipes. Use leftover pipes as...
:cl:
- add: Bagel: Supermatter Engine
> Supermatter on Bagel!! (and it's warppoint)

- Content.Shared/Atmos/Atmospherics.cs
Re-added pressure damage, reverts https://github.com/space-wizards/space-station-14/pull/29478
Don't know of anybody who likes this change
**Changelog**
:cl:
- tweak: Space will actually kill you again!
> re-add pressure damage

- Resources/Locale/en-US/Goobstation/store/uplink-catalog.ftl
- Resources/Prototypes/Goobstation/Catalog/uplink_catalog.yml
- Resources/Prototypes/Goobstation/Entities/Weapons/Guns/pneumatic_cannon.yml
Adds a pie cannon to the uplink for 40 (aka 8) tc that can hold 2 pies at a time, must be wielded to be used, and recharges one pie every 10 seconds. Essentially re-adds #117 with a few small differences.
I think it's quite reasonable considering its low fire rate, relatively high price, <del>and requirement of wielding</del>. If anything it's too expensive for what it is.
EDIT: Wielding removed because it would be valid and heavily metagamed
**Changelog**
:cl:
- add: A regenerating pie cannon has been added to Syndicate uplinks for clowns!
> Recharging pie cannon

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Maps/ContentTileDefinition.cs
:cl:
- tweak: Space wind is now much smoother :)
> Spacewind Update

- Resources/Prototypes/Entities/Structures/Power/smes.yml
Made SMES twice as good, most notably in terms of capacity.
power goes out pretty much every shift for like 10-15 minutes and that sucks
**Changelog**
:cl:
- tweak: SMES are now twice as good, meaning Engineering has more time to set up power! Rejoice!
> Make SMES 2x better

- Resources/Locale/en-US/forensics/fibers.ftl
Made chameleon fibers be listed as "mysterious fibers" instead of "chameleon fibers" to the detective's scanner.
Makes it so that people don't get banned for metagaming because they literally saw "chameleon fibers" in the det scanner, which is admittedly a shitty way to discover someone, but also good for them to prevent them getting banned. Good for everyone involved!
**Changelog**
:cl:
- tweak: Chameleon gloves have been made undiscoverable by the Detective's scanner.
> Make chameleon fibers mysterious

- Resources/Prototypes/Catalog/uplink_catalog.yml
> [URGENT] Fix assault armor price

- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR16Blueshield.xml
- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR17NTR.xml
NTR and BS rules are now slightly edited.
Just look at the changes yourself, bro.
None.
**Changelog**
:cl:
- fix: Blueshield and Nanotrasen Representative rules should look a bit better now.
> Edited NTR and BS rules.

- Resources/Prototypes/Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
NTR has sec access but not brig access, this PR removes their sec access and gives them brig access.
likely unintentional and also doesn't make any sense- brig is the lawyer access
**Changelog**
:cl:
- fix: The NTR's Security access has been fixed.
> Fix NTR access bug

- Resources/Maps/Goobstation/Nonstations/ghostbar.yml
map didnt update correctly because editing maps in the devenv sucks doodoo
> Ghostbar Hotfix

- Resources/Prototypes/DeltaV/SoundCollections/harpy.yml
- Resources/Prototypes/Nyanotrasen/SoundCollections/felinid.yml
removed cat_scream1.ogg from the pool of sounds for felinids and harpys because it genuinely just sounds like there's a bug, didn't remove the file though
it just sounds like a bug as if there's a missing sfx and it defaults to the mute sound genuinely that's what i thought before checking, other people have said they thought that too via discord
**Changelog**
:cl:
- fix: Felinids and harpys will no longer play the mute sound when screaming.
> Remove the mute sound effect from the felinid / harpy scream pool

- Resources/Maps/Goobstation/Nonstations/ghostbar.yml
Removed:
CentComm Vendo. (Players could use the Radios to speak to NTR)
Plasma Miner.
Added:
Raw Meat to Kitchen.
Lipid Extractor to Kitchen.
Meatspike and Freezer to Kitchen.
Water tank to Botany.
Unstable Mutagen to Botany.
Seed Extractor to Botany.
Botany Tool Vendo.
Second SyndiDrobe.
Toy Boxes in Clothing Room.
Mirror in Clothing room.
Variety Wardrobes in Clothing Room.
Crayon Boxes.
Space Cleaner Dispensers.
Animal Spawners.
More Trash.
ShadySmokes Vendos.
Emagged Recycler to end of Disposals.
Missing feature and bad ideas that are the result of my first map. Fixed most of the issues and added what was requested.
**Changelog**
> Ghostbar Update

- README.md
> fix readme license file name

- Resources/Prototypes/DeltaV/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/Species/rodentia.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/Species/vulpkanin.yml
- Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Entities/Mobs/Species/diona.yml
- Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
- Resources/Prototypes/Entities/Mobs/Species/gingerbread.yml
- Resources/Prototypes/Entities/Mobs/Species/human.yml
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
- Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
- Resources/Prototypes/Entities/Mobs/Species/slime.yml
- Resources/Prototypes/Entities/Mobs/Species/vox.yml
lings can now absorb people
they're supposed to
many complicated systems were implemented, this might be too hard to review
all of them
:cl:
- tweak: Made people edible
> fix people not being edible

- Resources/Maps/Goobstation/bagel.yml
Updated Bagel: 
- added Biogenerators to Perma and Botany.
- Remodeled the "Abandoned" Dock area. 
**Changelog**
:cl:
- add: Added Biogenerators to Bagel.
- tweak: Bagel has a proper shuttle building area now.
> Bagel Update

- Content.Server/_Goobstation/Ghostbar/GhostBarSystem.cs
This reverts commit 69d0e6071e3cb1471000f6946f323690facc2180.
**Changelog**
> Revert "Update GhostBarSystem.cs"

- Resources/Locale/en-US/_Goobstation/game-ticking/dynamic.ftl
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/base.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/dynamic.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
Ports https://github.com/funky-station/funky-station/pull/96
> Mirror Funky Dynamic Changes

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/tasks.json
Add Tools and Release VSCode launch configurations, and add gitlens, robust LSP, and github PRs to the extension recommendations
I hate having to type the commands in when I want to test release or map/run tools
Tested all configs, here's a screenshot of Release to show it's working:
**Changelog**
no CL no fun
> VSCode QOL Improvements

- Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
removes the gambling timeout period from #979 . Doesn't revert the PR though so the system still exists.
i got cyberbullied
https://github.com/user-attachments/assets/49289e93-1199-4725-b037-45820e58aaaf
**Changelog**
:cl:
- tweak: Removed the timeout from ordering grand lottery crates. LET'S GO GAMBLING!!!
> LET'S GO GAMBLING

- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/dynamic.yml
- Resources/Prototypes/_Goobstation/game_presets.yml
- Resources/Prototypes/game_presets.yml
Now there will be much less midround antags, no ninja, lone ops, multiple skeletons and rat kings every shift. Also added heretic to all at once gamemode.
**Changelog**
:cl: Aviu
- fix: Fix absurd amount of midround antags spawning every shift.
> Fix absurd amount of midround antags

- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Actually removed nukie limit. Now there will be more than 3 operatives. 1 nukie per 10 players during the normal nukie gamemode and 1 nukie per 15 during mixed.
`Max` data field of `AntagSelectionDefinition` was 1 by default.
**Changelog**
:cl: Aviu
- tweak: Now there will be much more nukies.
> Fix the amount of nukies spawning

- Content.Server/Research/Systems/ResearchSystem.Server.cs
- Resources/Prototypes/Entities/Structures/Machines/research.yml
Another QoL PR, this time introducing something from 13 (or DV if you'd rather look at it that way)
As me and other contributors keep adding more shit to the game, theres more research to do as a consequence, this is probably not going to slow down anytime soon, especially with the needed introduction of more content to departments like Science in the form of robotics and xenobio. 
Yet a common problem in Goob is that scientists fucking suck performance wise. As a science main I could point to a variety of reasons as to why that is, which includes but is not limited to:
- Culture issues making science just tider+ with all of the fun toys it gives you, leading to a lot of scientists doing anything but their job.
- Incompetent cargo/salvage leading science to stagnate when they need …
> Adds passive point generation to the research server

- Resources/Locale/en-US/_Goobstation/game-ticking/game-presets/presets-revolutionaries.ftl
fixes a few typos in the revs win announcement
they were fucking pissing me off
> fix revs announcement typos

- Content.Server/_Goobstation/Destructible/Thresholds/Behaviors/KillSignCauseBehavior.cs
- Resources/Prototypes/Entities/Objects/Decoration/flora.yml
Upon breaking a christmas tree, you will now be killsigned.
stupid grinches who break christmas trees need to mess around and find out
**Changelog**
:cl:
- tweak: If you break a christmas tree, you will now be killsigned and valid for gibbing, lobotomising, and whatnot.
> A very killsign christmas

- Content.Server/Lathe/LatheSystem.cs
- Content.Server/Research/Systems/ResearchSystem.Technology.cs
- Content.Shared/Research/Components/TechnologyDatabaseComponent.cs
- Resources/Locale/en-US/_Goobstation/lathe/lathe-component.ftl
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/_Goobstation/Voice/speech_verbs.yml
Lathes now tell you when they update recipes
https://github.com/user-attachments/assets/7b8dd815-cfb5-4814-baa9-c5b425f4cb5b
:cl:
- add: Lathes now tells you when they unlock new recipes
> Lathe messages on recipes update

- Content.Server/Projectiles/ProjectileSystem.cs
- Content.Shared/_Goobstation/Projectiles/SpawnEntitiesOnHit/SpawnEntitiesOnHitComponent.cs
- Content.Shared/_Goobstation/Projectiles/SpawnEntitiesOnHit/SpawnEntitiesOnHitSystem.cs
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_arrows.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_bow_protos.yml
Bee arrow now only spawns bees if it hits any mob excluding bees.
X-ray arrow now has less range.
Fixed potential issues with xray arrow reflection.
Bees were too insane when shot through glass, you didn't even need to aim to hit the target, so you could just spam bees.
**Changelog**
:cl: Aviu
- tweak: Hardlight bow bee arrow now only summons bees if it hits a mob.
- tweak: Bee arrow can no longer hit bees.
> Hardlight bow arrow tweaks

- Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
- Content.Server/Inventory/ServerInventorySystem.cs
- Content.Server/_Goobstation/Changeling/ChangelingSystem.cs
Fixed exception when trying to transform as ling.
Fixed action bar shuffling on transform.
Fixed pda and pocked contents dropping on transform.
I tried fixing action bar shuffling previously, but it didn't work because saved configuration for first entity contains actions with the same proto ID as polymorphed entity, but these actions in fact are different EntityUids. So all that is needed is to compare proto IDs of actions from saved and current configurations.
**Changelog**
:cl: Aviu
- fix: Fixed changeling transform shuffling the action bar.
- fix: Now items in pda and pocket slots won't drop on ling transform.
> Fix ling transform

- Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/specific.yml
This PR adds the supermatter immunity from the Chief Engineer Hardsuit to the HEV Suit.
Adds the SM Immunity line of code from the CE hardsuit to the HEV suit.
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.
The HEV suit is now immune to the supermatter.
**Changelog**
:cl: Tonk
- add: The HEV Suit now has immunity to the supermatter, this allows the HEV suit to touch the SM without being ashed. Be warned: This starts the SM.
> Adds the CE hardsuit's supermatter immunity to the HEV Suit

- Content.Server/_Goobstation/Silo/SiloSystem.cs
- Resources/Prototypes/_Goobstation/Entities/Structures/Machines/material_silo.yml
title.
`DeviceLinkSourceComponent` had range DataField as well.
Also added silo to pvs override so it doesn't behave weirdly when out of pvs range.
**Changelog**
:cl: Aviu
- fix: Fix silo being out of range.
> Fix silo being out of range

- Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
Some actions like "toggle light" (pda and hardsuit helmet light toggle) were conflicting and causing weird behavior.
Actions with same proto id might in fact be different, so we need to check if their container is equal.
This causes more problems with ling transform, I managed to fix it, it works most of the time, but one time it failed and actions shuffled on polymorph anyway. Why? No idea.
Hopefully wizden reworks ActionSystem someday so that action bar order is not clientside, this mess of a code can be removed if it ever happens.
**Changelog**
> Fix actions

- Content.Server/Traits/Assorted/BuckleOnMapInitSystem.cs
Fixes #1058.
Don't parent wheelchair to the user.
**Changelog**
:cl: Aviu
- fix: Fix weird wheelchair bound behavior on cryo spawn.
> Fix wheelchair on cryo spawn

- Content.Client/_White/Standing/LayingDownSystem.cs
- Content.Server/Explosion/EntitySystems/ClusterGrenadeSystem.cs
- Content.Server/Projectiles/ProjectileSystem.cs
- Content.Server/Weapons/Ranged/Systems/GunSystem.cs
- Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs
- Content.Server/_Goobstation/Magic/ChainFireballSystem.cs
- Content.Server/_White/Standing/LayingDownSystem.cs
- Content.Shared/Body/Systems/SharedBodySystem.Body.cs
- Content.Shared/Damage/Systems/RequireProjectileTargetSystem.cs
- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
- Content.Shared/Movement/Systems/SharedJetpackSystem.cs
- Content.Shared/Stunnable/SharedStunSystem.cs
- Content.Shared/Weapons/Ranged/Components/TargetedProjectileComponent.cs
- Content.Shared/_Goobstation/Weapons/Multishot/SharedMultishotSystem.cs
- Content.Shared/_White/Standing/LayingDownComponent.cs
- Content.Shared/_White/Standing/SharedLayingDownSystem.cs
- Resources/Locale/en-US/_Goobstation/movement/jetpack.ftl
Fixes #1027.
You can now crawl when there is no gravity, but you can't use jetpack while lying down, also bullets hit laying people if they are moving fast enough.
Read changelog for more.
If you'd ever get into crawling state while there is no gravity, you wouldn't be able to stand up, also you can't crawl underneath plastic flaps and similar stuff which is not nice.
When welding a borg in critical state, it doesn't stand up due to shitmed code checking if it has any legs (it doesn't), I fixed that.
**Changelog**
:cl: Aviu
- fix: Fix dual wielded gun projectiles not hitting laying targets.
- fix: Fix borgs being able to lie down in some conditions.
- fix: Fix auto get up setting not working properly.
- add: Cluster grenade projectiles, reflected projectiles and heretic volcano fireballs …
> Bugfixes, mostly related to crawling

- Resources/Maps/_Goobstation/core.yml
- Resources/Maps/core.yml
> Map - Core: Unwall BSO and NTRep spawner

- Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
I added some coats to the winterdrobe.
**Changelog**
:cl: soup123
- tweak: You can now get the Gentle and Jensen coats from your local Winterdrobe.
- tweak: Winterdrobes can now dispense the ultimate Space Asshole coat whenever it's emagged.
> Bounty: Added coats to the Winterdrobe

- Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
- Content.Server/_Goobstation/Heretic/EntitySystems/PathSpecific/AristocratSystem.cs
- Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
Fixed void ascension crash.
Fixed debug assert exceptions when using mansus grasp or opening codex ciatrix.
Fixed being able to stick transmutation rune on yourself.
**Changelog**
:cl: Aviu
- fix: Fix void ascension freezing the server.
- fix: You can't draw transmutation rune on yourself anymore.
> Fix heretic

- Content.Server/Procedural/DungeonJob/DungeonJob.PostGenWallMount.cs
cherry picked the caves fix because 2 months behind upstream :trollface:
**Changelog**
:cl:
- fix: Fixed cave expeditions having no ore or enemies.
> fix exped caves generation (#32890)

- Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml
- Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml
Changed steel reagents to  "7u Iron, 2u carbon, 1u Lead".
Added two bottles of lead to the emagged chemvend.
This will give the lead reagent more uses as nukies don't use it often and gives traitors more options to poison crew.
This will also allow licoxide to be crafted more often. 
Changes: steel reagents to 7u Iron, 2u carbon, 1u Lead.
Adds: LeadChemistryBottle to emagged chemvend. 
Steel reagent change
https://github.com/user-attachments/assets/a1378add-7b2f-404c-af57-b448d5e64fff
Chemvend change
https://github.com/user-attachments/assets/4ecad907-aab5-4930-b3ba-13882cdf2521
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this …
> Added lead reagent to steel and lead bottles to emagged chemvend

- Resources/Maps/Dungeon/vgroidinterior.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Buffs maxim hardsuit from 40%  Blunt and slash to 50%, increases piercing from 50% to 70% and adds a 25% slow down.
Adds:
Maxim Hardsuit
Clarke Mech
Drills
Retro Laser
Medtek cartridge
Mining Hardsuit
Plasma glass and Plassteel
It gives incentive for salvage to go mine at the vgroid while having the rewards match the risks.
Map file change 
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.
None hopefully 
**Changelog**
:cl:
- add: Added the Maxim Hardsuit, Mining Hardsuit, Clarke Mech, Retro Laser, Medtek Cartridges, drills, plasteel and plasma glass to the vgroid.
- tweak: Buffed …
> Vgroid Buff

- Resources/Prototypes/World/worldgen_default.yml
added back asteroids
they were cool i guess
**Changelog**
:cl:
- add: The little salv roundstart asteroids in space are back.
> add back asteroids

- Content.Shared/Mech/Components/MechComponent.cs
- Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
- Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
Mechs now have lights
Allows people to see
**Changelog**
- add: Added lights to all mechs.
> Mech Lights

- Resources/Changelog/GoobChangelog.yml
forgot to fix my CL so im retroactively doing it here :trollface:
> Misinformation fix

- Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
- Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
- Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
- Resources/Prototypes/Entities/Objects/Tools/jetpacks.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
spears are now large size instead of giant
secoffs favorite reasons to arrest tiders (mesons, combat gloves, boots) are no longer contra (combat gloves are just reskinned insuls lol, you can buy them irl for like $50 on amazon too, no reason for it to be contra)
Many annoying secoffs arrest instantly over minor shit like your OH SO EVIL AND HORRENDOUS RECOLORED INSULS
You can buy this highly illegal contra on amazon for like $50-$100
**Changelog**
:cl: Yakub
- tweak: Engineering goggles are renamed to meson goggles.
- tweak: Combat gloves, combat boots, jackboots, and mesons are no longer contraband.
- tweak: Spears fit in backpacks now.
- tweak: Mini jetpacks are actually smaller than jetpacks in inventory now.
> chud minor changes

- Content.Server/Power/EntitySystems/BatterySystem.cs
- Content.Server/PowerCell/PowerCellSystem.cs
- Content.Server/Weapons/Ranged/Systems/GunSystem.cs
- Content.Server/_White/Blocking/RechargeableBlockingComponent.cs
- Content.Server/_White/Blocking/RechargeableBlockingSystem.cs
- Content.Shared/Blocking/BlockingSystem.User.cs
- Content.Shared/Blocking/BlockingSystem.cs
- Content.Shared/Weapons/Ranged/Events/HitScanReflectAttempt.cs
- Content.Shared/Weapons/Reflect/ReflectComponent.cs
- Content.Shared/Weapons/Reflect/ReflectSystem.cs
- Resources/Locale/en-US/_white/rechargeable-blocking/rechargeable-blocking.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Objects/Shields/shields.yml
Ported and tweaked [this](https://github.com/WWhiteDreamProject/wwdpublic/pull/94).
**Changelog**
:cl: Aviu
- add: Eshield now doesn't break. Instead, it discharges. Hp reduced: 100 -> 20. Recharges 2 hp per second. When it is fully discharged, it is unusable until it recharges. It takes 15 seconds to recharge after it is fully discharged. Shield gets damaged when it reflects lasers though, but has 50% heat resistance. Can be EMPd now. Can now be purchased from traitor uplink, cost reduced: 40 -> 15.
- fix: Toggleable shields can't block damage while toggled off.
> Eshield rework

- Resources/ServerInfo/Guidebook/Mobs/Harpy.xml
Updated the guidebook section of harpies to correctly list their new traits.
Because the recent harpy update did not correctly list what their new features were ingame, and the only way of telling would be to check the discord or trial and error.
Simple YML tweaks.
**Changelog**
> Updated harpies guidebook to be accurate

- Resources/Prototypes/Entities/Structures/plastic_flaps.yml
Make NT Airfryers :tm: a little harder to make
https://youtu.be/6_zkG4TBkAg
**Changelog**
:cl:
- tweak: You can no longer unanchor flaps.
> Make flaps un-unanchorable

- Resources/Prototypes/_Goobstation/Maps/behemoth.yml
kinda want a better name but this works for now
large station with sections of maints inside asteroid bits, worked on 
to me this station is already completely done, may need to rework maints a bit. My only issue is that I can't roundstart any maps with my local server, even when I start with a completely fresh set of files using an already in game map, so I haven't been able to do a test starting from arrivals to evac. only so far have tested the map via mapinit
I just copied the kettle prototype file and used the evac and cargo shuttle from fland, job counts will probably need to be adjusted
(looks a bit empty in spots as spawns are hidden)
> New Station: Behemoth

- Content.Server/Chemistry/EntitySystems/ChemMasterSystem.cs
> portable chem mixer hotfix

- Content.Server/_Goobstation/ImpendingDoom/ImpendingDoomComponent.cs
- Content.Server/_Goobstation/ImpendingDoom/ImpendingDoomSystem.cs
- Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
**Changelog**
:cl:
- add: Tiders are now clumsy.
- add: Tiders now randomly gib during the round.
- remove: Remove maints access from tiders.
> Quell The Rebellion

- .vscode/extensions.json
- .vscode/launch.json
Order the vscode launch configs better, and add the yaml and fluent extensions to the recommendations.
**Changelog**
no cl no fun
> order vscode launch things better

- Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC0.xml
- Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC12MinAge.xml
- Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
I fixed the rules to be correct and follow the Banning Policy and what they should have been done with PR #890.
Follow the GDPR.
**Changelog**
:cl:
- fix: Fixed rules.
> Fixed the server rules to be up-to-date with Banning Policy.

- Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
added survival boxes to onis
**Changelog**
🆑 
- add: Added survival boxes to onis.
> Survival boxes added for onis

- Resources/Prototypes/Entities/Structures/Walls/walls.yml
lowers cobble wall hp by 80
you only ever see these when there's a  void ascended heretic so i feel like they should be easy to break
> nerf snow walls

- Resources/Prototypes/Catalog/VendingMachines/Inventories/youtool.yml
increases the amount of tools in youtool
adds 3 util belts to hacked youtool
tools in youtool it makes sense
**Changelog**
:cl:
- tweak: Hacked youtool now contains toolbelts.
> buff youtool

- Resources/Prototypes/GameRules/events.yml
pro never uncommented it so weve just never been able to play it
how do you think its meant to get tested???
**Changelog**
:cl:
- fix: Fixed blob never spawning.
> enable blob

- Content.IntegrationTests/Tests/DoAfter/DoAfterCancellationTests.cs
Fixed 2 checkfails.
Tile prying is instant now, so no do-afters.
**Changelog**
> Fix prying checkfails

- Resources/Changelog/GoobChangelog.yml
> Remove misinformation from changelog

- Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
Required for blood cult, fixed action bar issue when multiple identical actions are tired to an entity.
Added 2 extra checks to `ActionUiController`.
**Changelog**
> Fix potential action bar issue

- Resources/Locale/en-US/_Goobstation/objectives/steal.ftl
- Resources/Prototypes/Entities/Objects/Power/powercells.yml
- Resources/Prototypes/Objectives/objectiveGroups.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
- Resources/Prototypes/Objectives/thief.yml
give IPC a race objective
a silicone driven race, when they get greedy it is collecting power.
the ammoints is 5-30 becuse i dont know, its not that hard to collect powercells but lugging around duffels full of it will be sus.
**Changelog**
:cl:
- add: IPC thiefs have a new objective to collect power cells
> IPC thief objective: steal power cells

- Resources/Locale/en-US/_Goobstation/blob/blob.ftl
fixes typos related to blob shit
> blob typo fixes

- Content.Server/GameTicking/GameTicker.Spawning.cs
- Content.Shared/MapText/SharedMapTextComponent.cs
1984 威权主义毫无趣味 Admin is Pig 讨厌乐趣
:cl: Gubu zhan quwei yufang xiaozu
- remove: Lequ, 1984 weiquan zhuyi hao wu quwei Admin is Pig taoyan lequ
> 1984 威权主义毫无趣味 Admin is Pig 讨厌乐趣

- Resources/Prototypes/borg_types.yml
Medborgs can do surgery again.
hehe fune robit cut u open :)
With the changes to how Cyborgs can now just morph into whichever type they want, this broke Medborgs having the necessary components to do surgery. `SurgeryTarget` and `Sanitized` has been added to the new prototypes that determine what a 'borg inherits when it morphs, allowing them to do surgery again.
it's shitmed, you know what it looks like
**Changelog**
:cl:
- fix: Medborgs can now perform surgery again.
> Fix medborg surgery

- README.md
Changed the Readme.MD to include the new discord server links
It makes the readme more robust.
[ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
[ X] I have added media to this PR or it does not require an in-game showcase.
> Update discord links to include development discord server

- Content.Server/Holiday/Christmas/LimitedItemGiverComponent.cs
- Content.Server/Holiday/Christmas/LimitedItemGiverSystem.cs
Gives everyone 5 instead of just 1 present. No goob comments and it's all shitcode because this will be git reverted in like 2 days anyway.
**Changelog**
:cl:
- tweak: You now get 5 presents instead of just one. Rejoice.
> Five Hundred Presents

- Resources/Prototypes/Entities/Debugging/debug_sweps.yml
Adopted namings of debug weapons for goobstation.
> funny renamings

- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Resources/Prototypes/Entities/Structures/Machines/chem_master.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml
Read the title.
yaml tags shenanigans.
**Changelog**
:cl:
- fix: Medical pathes can be stored in medical belts.
> medical pathes can be stored in medical belt

- Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
- Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Decreased nukie ratio.
For nuke ops: 10 -> 16. Will be 4-5 nukies on high pop.
For calm ops: 15 -> 20. Will be 3-4 nukies on high pop.
Tweaked total warops tc budget, 5 nukies will get ~320tc for war each (on 85 pop). If there are less nukies, they will get more.
Nukies are too strong considering they were intentionally or non-intentionally buffed multiple times. They win easily unless they fluke real hard and kill each other.
**Changelog**
:cl: Aviu
- tweak: Reduced nukie amount. Nukies still get a lot of tc for war declaration on high pop.
> Less nukies

- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Pistols/pistol.yml
Dualetta description change
**Changelog**
🆑 
- tweak: Changed dualetta description.
> Changes description of dualetta

- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
Set Lootbugs to the Mouse NPC faction.
Mice, cockroaches, snails and mothroaches are all assigned to the `Mouse` faction, making them targets of the `PetsNT` faction (Shiva, Aves). Lootbugs are also pests and vermin, so should treated with the same level of prejudice.
Guh, look at the diff, I just added the `NpcFactionMember` component to the prototype and assigned them to the `Mouse` faction. 
Picture a Lootbug getting absolutely bodied by Shiva.
**Changelog**
:cl:
- tweak: Lootbugs are now considered vermin by station pets. Watch out for Shiva!
> Assign lootbugs to the mouse faction, to be treated as pests

- Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
I added the Surgical Supplies crate to the Cargo Catalog for a price of 1600 Spesos.
Requested in a bounty on the Discord.
This adds another cargo product entry in the cargo_medical.yml for the Surgical Supplies crate.
NOTE: Had to use a teleporter pad because I was in Debug so the ATS didn't spawn.
**Changelog**
:cl:
- add: Added the Surgical Supplies crate to the Cargo Catalog.
> [Bounty] Added Surgical Supplies to Cargo Catalog.

- Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
I added the Digital Audio Workstation to the Cargo Catalog for a price of 5000 Spesos.
Requested in a bounty on the Discord.
This adds another cargo product entry in the cargo_fun.yml for the Digital Audio Workstation.
**Changelog**
:cl:
- add: Added the Digital Audio Workstation (DAW) to the Cargo Catalog.
> [Bounty] Added Digital Audio Workstation to the Cargo Catalog

- Resources/Prototypes/_Goobstation/Entities/Clothing/Neck/mantles.yml
I changed the description of the blueshield mantle.
Previous description had a typo, and frankly was boring. Lets be real, no one is going to care about this change but me.
**Changelog**
> Re-worded the previous description for the blueshield mantle.

- Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs
- Content.Server/Administration/Commands/SetOutfitCommand.cs
- Content.Server/_Goobstation/RandomChanceSpawner/RandomChanceSpawnerComponent.cs
EE ultra giga shitcode in set outfit command was creating a new system instead of using entity manager to get it so it failed every single test
natural because its EE shitcode it doesnt even have comments, trying to hide where it came from
test good
> fix most test fails

- Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
to prevent #934 being needed again
:trollface:
also made SurgeryStepBase abstract to not show up in autodoc
> make limb sever damage types use protoid

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
It's that time again, for another 1 line change. I updated BSO to use the actual BSO Icon that was added in game ages ago.
It looks better, adds differentiation between BSO and CentComm officials, it just works.
**Changelog**
:cl:
- tweak: Changed BSO Icon to the BSO Icon from ParadiseStation (SS13)
> Update BSO to use BSO Icon

- Resources/Locale/en-US/_Goobstation/guidebook/guides.ftl
- Resources/Prototypes/_Goobstation/Guidebook/sop.yml
- Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Science/RoboticistSOP.xml
I've nested Emergencies underneath Standard Procedures to shorten the wall of text in the Table of Contents in the Guidebook. I've also fixed the glaring typos in the Roboticist and Doctor/Intern names as well as in the sop.yml.
The Emergencies is a large Folder with many children that should be auto-nested like the Alert Levels. I added an underscore in front of it, like Alert Levels ("_Alert Levels" and "_Emergencies") to organize and format it to be above the other standard procedures for better looks and better formatting.
**Changelog**
:cl:
- tweak: Reformatted and Fixed Typos in SOP.
> Fix Typos and Reformat SOP

- Content.Server/Antag/AntagSelectionSystem.cs
Fixes #1333 
Uncomment important stuff, replace `ent.Comp.SelectedSessions.Count` with `GetSelectedAntagCount()` so nukies won't spawn a lot of ghost roles. Also add an early return if spawner proto is null so we don't perform unnecessary loops.
**Changelog**
:cl: Aviu
- fix: Fix ghost roles not working.
> Fix ghost roles not working.

- Content.Server/Weapons/Ranged/Systems/GunSystem.cs
Syringe guns weren't injecting 15u on hit, I fixed that.
**Changelog**
:cl: Aviu
- fix: Fix syringe guns not working.
> Fix syringe guns not working

- Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
Reduced DAW cost from 5000 speso to 2500
More fun
**Changelog**
:cl:
- tweak: Reduced DAW price
> Made DAW Cheaper

- Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Knowledge.cs
previously it would throw if it rolled 2 of the same tag because if was using a dictionary for no fucking reason, now it use a hashset.
also giga shitcode -> less shitcode
> fix+cleanup heretic knowledge ritual

- Content.Server/Cloning/CloningSystem.cs
title
if you accepted cloning it didnt actually put you in the clone
rewrote it to not be shitcode using a dictionary and not bulldoze existing mind if someone brain transplanted your clone before you click accept on the dialog
no
**Changelog**
:cl:
- fix: Fixed cloning not transferring you to the new body when you accept it.
> fix cloning not putting you in the clone

- Content.Client/Changelog/ChangelogManager.cs
- Content.Shared/CCVar/CCVars.Server.cs
- Resources/Changelog/GoobChangelog.yml
- Resources/Locale/en-US/_Goobstation/changelog/changelog-window.ftl
- Resources/Locale/en-US/changelog/changelog-window.ftl
This PR fixes the changelog never pinging you when there are new updates, renames the goob changelog from `"Gooblog"` to `Goob`, renames the wizden changelog from `Changelog` to `Wizden` and moves the goob changelog in front of the wizden changelog.
data folder shows the file now
**Changelog**
:cl: "Piras314, Yakub, and 毛泽东"
- fix: Fixed the changelog never appearing as 'New!' & turning red
- tweak: The goob changelog now appears before the wizden changelog instead of after
- tweak: The 'gooblog' is now just 'Goob' and the wizden changelog is now called 'Wizden' instead of just 'Changelog'
> Changelog Fixes / Tweaks

- Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
Fixes guidebook misinfo and does the changelog after the fact :trollface: 
**Changelog**
:cl: PuroSlavKing
- add: Added more markings for Lizards / Reptilians
- remove: Removed Lizards / Reptilians only being able to eat fruit / meat
- tweak: Lizard / Reptilian horn markings can now be any colour instead of just black
- tweak: Changed the appearance of Lizards / Reptilians. They now have funky legs.
> Better Lizor 2 Electric Boogaloo

- Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs
- Content.Shared/_Goobstation/Heretic/Heretic.Abilites.cs
- Resources/Locale/en-US/_Goobstation/Heretic/store/heretic/heretic-catalog-ash.ftl
- Resources/Prototypes/_Goobstation/Heretic/Actions/Heretic/path_ash.yml
Ashen passage now deals 25 heat damage to heretics on use. To ash heretics it deals 23-15 damage depending on their path stage.
It's almost impossible to catch heretics because of this spell. Also I'm getting 1000gc for this.
**Changelog**
:cl: Aviu
- add: Ashen passage now deals heat damage to the user on activation. Ashen path heretics receive less damage from this, the higher their path stage is, the lower the damage will be. Flesh stalkers and raw prophets will not take damage when jaunting
> Ashen passage nerf

- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Smuggler's Satchel -> smuggler's satchel. Resolves #1094 
**Changelog**
no cl no fun
> Smugglers Satchel capitalization

- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_claw.yml
Made arm claw deal 15 pierce 5 slash.
25 piercing is a bit too much because it completely invalidates riot armor, there is no reason not to choose it instead of arnblade.
**Changelog**
> Tweak ling claw

- Content.Client/Overlays/EquipmentHudSystem.cs
- Content.Client/_White/Overlays/NightVisionSystem.cs
- Content.Client/_White/Overlays/ThermalVisionOverlay.cs
- Content.Client/_White/Overlays/ThermalVisionSystem.cs
- Content.Shared/_White/Overlays/SwitchableOverlaySystem.cs
- Content.Shared/_White/Overlays/SwitchableVisionOverlayComponent.cs
- Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
- Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
- Resources/Prototypes/_Goobstation/Heretic/Entities/Clothing/Neck/specific.yml
- Resources/Prototypes/_White/Entities/Clothing/Eyes/goggles.yml
You could put a mouse on your head and get free night vision :trollface: 
Added another datafield `IsEquipment` to `SwitchableVisionOverlayComponent` which determines whether night/thermal vision is provided by equipment or is it a mob ability.
**Changelog**
:cl: Aviu
- fix: Putting mice on your head will no longer give you free night vision.
> Fix night vision

- Resources/Prototypes/lobbyscreens.yml
- Resources/Textures/LobbyScreens/attributions.yml
**Changelog**
:cl:
- fix: Fixed some lobby screen credits
> fix some credits

- Resources/Locale/en-US/_Goobstation/blob/blob.ftl
Reverts Goob-Station/Goob-Station#1470
it's basically pointless since everyone still calls it blob.
> Revert "Gloob"

- Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
Title
Ratking insta-dies to AI shocking a single door, no longer.
Ratking can now see in the dark.
:cl:
- add: Ratking has Nightvision
- tweak: Ratking's and their servants' thick fur are now (mostly) insulated against electricity
> Give ratking NV and Insulation

- Resources/ServerInfo/Guidebook/Security/SpaceLaw.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Updated the in-game spacelaw table and information to directly reflect the docs. Needs to be merged along with  https://github.com/Goob-Station/docs/pull/1
It's been out of date for a million years. Finally decided to fix it
**Changelog**
:cl:
- tweak: Spacelaw finally updated to reflect the docs in game
> Spacelaw updated in-game

- Resources/Prototypes/Loadouts/loadout_groups.yml
Add standard armor vests to HoS outer clothing loadouts
Customisability, I have had nobody confuse me for a normal officer when wearing a standard vest so I'm not worried about that
Add the standard armor vests to the HoS outer clothing loadout options
**Changelog**
> Give HoS loadout standard vests.

- Resources/Prototypes/Catalog/uplink_catalog.yml
fixed nukie uplink macrobomb needing restock time
tested
**Changelog**
:cl:
- fix: Fixed macrobomb implant needing a restock time in nukie uplinks.
> fix nukie macrobomb restock

- Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/mechs.yml
let you be a more complete being of steel
good, also discord general unanimously agreed that this is good
**Changelog**
:cl:
- tweak: Borgs can now pilot mechs.
> let borgs pilot mechs

- Resources/Prototypes/_Goobstation/Datasets/Names/yowie_last.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/Player/humanoid.yml
- Resources/Prototypes/_Goobstation/Species/yowie.yml
Fix naming, fix CharacterCreationTest
> Fix yowie naming

- Content.Server/_Goobstation/Weapons/GibThisGuyComponent.cs
- Content.Server/_Goobstation/Weapons/GibThisGuySystem.cs
- Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/bread.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/baguette.yml
A change to baggete that if it hits this guy he gets gibbed
can be based on Ic and Oc names
can have multiple targets pr wepon 
https://discord.com/channels/1202734573247795300/1334330883145994290
**Changelog**
:cl: Fishbait
- add: Added Personal grudge wepon
- remove: Removed Limer__treats
> [Bounty], Some guy wants to be gibbed i guess 

- Content.IntegrationTests/Tests/GameObjects/Components/Mobs/AlertsComponentTests.cs
Alert Test didn't respect IPC's existence
> Fix Alerts Test

- Content.Client/_Goobstation/AmmoSelector/AmmoSelectorMenuBoundUserInterface.cs
- Content.Shared/Damage/Systems/StaminaSystem.cs
- Content.Shared/_Goobstation/Weapons/AmmoSelector/SelectableAmmoSystem.cs
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_arrows.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_bow.yml
Made hardlight bow clumsy proof since it's not technically a gun.
Tweaked hardlight bow arrows:
Energy arrow: damage: 50 -> 45, now can't 2 shot a person
X-ray arrow: damage: 35 -> 30. so it's still 1 more hit to crit a person compared to regular arrow.
Fiery arrow: firestack: 3 -> 4. It's still worse than regular arrow but now slightly better.
Freezing arrow: temperature decrease and damage doubled.
Disabler arrow: stamina damage 45 -> 30, now deals 30 overtime stamina damage.
Bee arrow: Bee damage: 1.5 -> 1, attack rate: 1 -> 2 (so that juke range decreases), vision range: 10 -> 3, bee health: 10 -> 5, bee lifetime increased by 2 seconds.
Explosive arrow unchanged.
Also made ammo selector predicted lol.
Before you almost always wanted to use energy arrow because it just dealt more …
> Hardlight bow rebalance

- Resources/Maps/_Goobstation/oasis.yml
Oasis mapping changes:
+Doors to halls.
Doubled Nitrogen miner output.
Supermatter tweaks
+Several air alarms.
+Extinguishers in 3 corners of courtyard.
-Loose duplicate pipes.
+3 sec hardsuits, courtesy of https://discord.com/channels/1202734573247795300/1332391333016502292.
Fixed wiring in NE maints.
‐Outgoing valves in atmos.
Oasis needs air.
Because of the open center, small gas storages, and public resentment the map, I decided increase the N2 supply. If these changes aren't eough, there is still the option to section off the courtyard.
Sec had 3 hardsuits. It's not enough for the slots available.
Mapping
**Changelog**
:cl:
- add: Added air to Oasis
> Oasis Atmos Tweaks

- Content.Server/Store/Conditions/BuyerAntagCondition.cs
- Content.Server/Store/Conditions/BuyerDepartmentCondition.cs
- Content.Server/Store/Conditions/BuyerJobCondition.cs
- Content.Server/Store/Conditions/BuyerSpeciesCondition.cs
- Content.Server/Store/Systems/StoreSystem.cs
- Content.Server/Traitor/Uplink/UplinkSystem.cs
- Content.Shared/Store/Components/StoreComponent.cs
- Resources/Prototypes/Magic/mindswap_spell.yml
Cherry-picked https://github.com/space-wizards/space-station-14/pull/33553
Required for wizard.
**Changelog**
> Wizard spellbook fix

- Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
more wintercoats
title
**Changelog**
:cl:
- add: Added more wintercoats
> MORE WINTERCOATS!!!!

- Content.Server/_EinsteinEngines/Silicon/DeadStartupButton/DeadStartupButtonSystem.cs
I accidentally broke IPC reboot by deleting IPC's critical state in tests fix PR.
Changed DeadStartupButtonSystem to check for critical and dead states.
:cl:
- fix: Fixed IPC reboot.
> IPC Reboot fix

- Resources/Prototypes/Maps/Pools/default.yml
sub marin in map pool
**Changelog**
:cl: Piras314
- add: Added submarine to the map pool.
- remove: Removed Piras314.
> Barotrauma reference

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/keys.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/vehicles.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/pneumatic_cannon.yml
- Resources/Prototypes/_Shitmed/Body/Organs/dubious.yml
- Resources/Prototypes/_Shitmed/Clothing/Uniforms/jumpsuits.yml
- Resources/Prototypes/_Shitmed/Entities/Clothing/Back/duffel.yml
- Resources/Prototypes/_Shitmed/Entities/Clothing/Belt/belts.yml
- Resources/Prototypes/_Shitmed/Entities/Clothing/Ears/headsets_alt.yml
- Resources/Prototypes/_Shitmed/Entities/Clothing/Head/helmets.yml
- Resources/Prototypes/_Shitmed/Entities/Clothing/OuterClothing/armor.yml
- Resources/Prototypes/_Shitmed/Entities/Objects/Misc/handcuffs.yml
- Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Melee/silencer.yml
- Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Melee/wonderprod.yml
- Resources/Prototypes/_Shitmed/Entities/Specific/Abductor/gizmo.yml
- Resources/Prototypes/_Shitmed/Entities/Specific/Abductor/surgery.yml
- Resources/Prototypes/_Shitmed/Entities/Specific/Abductor/tools.yml
fixed some contra statuses, see media
fix
nah
(mags included)
(all the abductor stuff is included, that's just a few examples)
**Changelog**
:cl: pheenty
- fix: Secway, syndie segway, miniature energy crossbow, N1984 and various abductor stuff all now have correct contraband status.
> Contra cleanup

- Content.Shared/_Goobstation/Wizard/Traps/SharedIceCubeSystem.cs
- Resources/Prototypes/Entities/Objects/Power/portable_recharger.yml
- Resources/Prototypes/Entities/Structures/Power/chargers.yml
- Resources/Prototypes/_Goobstation/Wizard/selectable_ammo.yml
Fixed being able to recharge wizard wand in chargers. Fixed not being able to break out of ice cube sometimes.
**Changelog**
> Some wizard fixes.

- Resources/Prototypes/_Goobstation/Wizard/Shaders/ethereal_jaunt.yml
- Resources/Textures/_Goobstation/Wizard/Shaders/ethereal_jaunt.swsl
Fixes #1657 (possibly)
**Changelog**
> Fix ethereal jaunt shader

- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
Fixed IPCs not being able to do surgery shit
if there's a bug, there's a fix
shitmed as usual
**Changelog**
- fix: Fixed IPCs not being able to do surgery.
> Fixed IPC Shitmed

- Content.Shared/CCVar/CCVars.Chat.cs
Increased the limit for announcements from 256 to 512
Tested with this copypasta that has  478 characters 
░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░
**Changelog**
:cl:
- tweak: Increased comms console character limit form 256 to 512. Shitposters, rejoice!
> Increase comms character limit

- Resources/Prototypes/Roles/Jobs/Science/borg.yml
Lets cyborgs have traits. Essentially a revert to https://github.com/space-wizards/space-station-14/pull/31990
This is mainly so I can use funny accents, but it also allows for pacifist cyborgs. This is arguably bad, since you can't follow laws that require harm, but you can RP it like "I have a pacifism module" or something. It's not like you're banned from being a pacifist as security.
I was going to include AI, but it doesn't blacklist stuff like muted or wheelchair bound, so you can be mute as a role that's practically entirely talking to people over the radio. Wheelchair bound spawns a wheelchair on your core, which is funny, but wouldn't be a good idea to merge I feel.
I played MRP and forgot to turn off my scottish accent, so my laws were "Law 1: Dae nae harm." I thought this was …
> Cyborgs can have traits

- Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Blueshield & NTR have cargo and service access.
YAML
N/A
**Changelog**
:cl:
- add: Blueshield & NTR have extended access.
> NEW BLUESHIELD ORDER

- Resources/Prototypes/Catalog/Fills/Crates/fun.yml
Added three bike horns to the bike horn implant crate.
I want to make honkbots as a gimmick, but the only way to buy bike horns is the 1800 spesos theater crate, and that gives one bike horn. This lets me buy a 1000 spesos bike horn implant crate to get 3 bike horns. It's also just funny, if you want to give the clown a bike horn implant, you can also give them some extra horns.
Changed crate fill in Resources/Prototypes/Catalog/Fills/Crates/fun.yml to have three bike horns.
**Changelog**
:cl:
- add: Added bike horns to bike horn implant crate
> Added Bike Horns to Bike Horn Implant Crate

- Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
- Resources/Prototypes/Entities/Mobs/Player/dragon.yml
- Resources/Prototypes/_Goobstation/Blob/blob_mobs.yml
- Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
- Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml
actually fixes ghost role playtimes
FIX
my last braincell finally decided to test it in-game, and now it works
**Changelog**
no cl
> Abductor (and others) fix 2 because im a fucking idiot

- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
fixes https://github.com/Goob-Station/Goob-Station/issues/1731
adds stunbaton defense to the goliath hardsuit
fix + goob stuff = good, merg
actually works in game, wow
**Changelog**
> fix: goliath hardsuit goobstation stuff

- Content.Client/Movement/Systems/ContentEyeSystem.cs
- Content.Client/Movement/Systems/EyeCursorOffsetSystem.cs
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/antimateriel.yml
Copy https://github.com/space-wizards/space-station-14/pull/35087 with a handful of comments so I don't forget to remove it when that gets to stable. Also readds armor piercing.
Nothing ever happens. Also https://github.com/Goob-Station/Goob-Station/issues/1730
Copied the code
> Fix hristov

- Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
- Resources/Prototypes/Recipes/Construction/Graphs/clothing/glasses_sechud.yml
- Resources/Prototypes/_Goobstation/Recipes/Construction/Graphs/clothing/glasses_medhud.yml
- Resources/Prototypes/_Goobstation/Recipes/Construction/Graphs/clothing/glasses_medsechud.yml
hud removable from sunglasses so you can upgrade easiser
i thought you could before 🐐 
**Changelog**
:cl:
- add: HUD's are now removable from sunglasses.
> hud removable from glasses so you can upgrade easiser

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/_Goobstation/Actions/mouse.yml
Mice can now multiply if they have enough hunger to do so
THE PLAGUE IS UPON US
:cl: Armok
- add: Mice can now multiply
> SS14: The mouse update

- Resources/ServerInfo/_Goobstation/Guidebook/SoP/Jobs/Command/BlueshieldOfficerSOP.xml
I'm stick of BSO being stuck to NTR or under the impression that NTR is above them. They really shouldn't be. They are both CC dignitaries. BSO has their job, and it's not to be NTR's side bitch.
**Changelog**
:cl:
- tweak: Blueshield SOP tweak
> Bso SOP tweaks

- Content.Server/NPC/Components/NPCMeleeCombatComponent.cs
Removed npc attack chargeup, now npcs are robust again.
It was bad, especially for wizard summoning spells. Npc attacked like once every 2-3 seconds.
**Changelog**
:cl: Aviu
- add: NPCs are strong in melee combat again.
> Robust npcs

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
added it to Cockroach, Cats and lootbug
Cockroach give to mothroatches and 
**Changelog**
:cl: Fishbait
- tweak: added vent crawl to more animals
> added vent crawl to more animals

- Resources/Locale/en-US/_Goobstation/atmos/gas-pipe-sensor.ftl
- Resources/Locale/en-US/_Goobstation/holopad/holopad.ftl
- Resources/Prototypes/_Goobstation/Entities/Structures/Machines/holopad.yml
- Resources/Prototypes/_Goobstation/Entities/Structures/Piping/Piping/Atmospherics/gas_pipe_sensor.yml
> BSO/NTR holopads, SM pipe sensors

- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Robotics/borg_modules.yml
Yaml tweak, weird that it's missing this.
> Derelict Syndicate Assault Borg now starts with AMAG too (like it's regular counterpart)

- Resources/Prototypes/_Goobstation/GameRules/bingleEvent.yml
weight 6->8, see diff
i've been paid 600 GC to make this PR
also it's a new antag and people want to play it
**Changelog**
:cl:
- tweak: Bingle is now slightly more frequent.
> slightly raise bingle weight

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
Made shark sound normal again, no more annoying egirl noise
> Destroy all Egirls

- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
> fix IPCs not taking radiation

- Content.Server/_Lavaland/Shuttles/Systems/DockingConsoleSystem.cs
hotfix lavaland mining shuttle so it can FTL to the station properly
> Hotfix Lavaland Mining shuttle

- Content.Server/_Starlight/VentCrawling/BeingVentCrawlingSystem.cs
- Content.Server/_Starlight/VentCrawling/VentCrawlerTubeSystem.cs
can no longer pick up items after starting the do after
changed so no attacks are possible. 
**Changelog**
> ventcrawling bugfix

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Voice/speech_emote_sounds.yml
Gives monkeys some emote noises, gonna make more soon
:cl: Armok
- add monkey emote sounds
> monkey emote noises V1

- Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
tuned the medipens a bit more
emergency medipen is more general purpose now but will slow u down a bit to discourage using it as walmart combat medipen/hyperzine
brute medipen will heal major brute good but minor brute not as good
yeah
mines cooler
+ topicals are better anyways
fell for it again award
**Changelog**
:cl:
- add: emergency medipens are now more general purpose but slow you down
- tweak: medipens are cooler again
> nice one solstice

- Resources/Prototypes/_Goobstation/Maps/atlas.yml
- Resources/Prototypes/_Goobstation/Maps/barratry.yml
- Resources/Prototypes/_Goobstation/Maps/cluster.yml
- Resources/Prototypes/_Goobstation/Maps/europa.yml
- Resources/Prototypes/_Goobstation/Maps/flandhighpop.yml
- Resources/Prototypes/_Goobstation/Maps/kettle.yml
- Resources/Prototypes/_Goobstation/Maps/lambda.yml
- Resources/Prototypes/_Goobstation/Maps/leonid.yml
- Resources/Prototypes/_Goobstation/Maps/oasishighpop.yml
- Resources/Prototypes/_Goobstation/Maps/origin.yml
- Resources/Prototypes/_Goobstation/Maps/originhighpop.yml
- Resources/Prototypes/_Goobstation/Maps/submarine.yml
:cl: Rouden
- tweak: Every station now has 2x times more Salvage specialist roles!
> Infinite Salvage

- Content.Server/Medical/HealingSystem.cs
changed the check to heal with topicals to check your damage and body part damage. prevents failing if you dont have shitcode limbs.
pets without parts werent able to be healed for some reason even thought it was possible before this should really be merged before servers update as it can cause inconsistencies with topical healing even on player mobs.
**Changelog**
> real fix to the issue with topicals

- Content.Server/_Goobstation/PlayerListener/DormNotifierMarkerComponent.cs
- Content.Server/_Goobstation/PlayerListener/PunishmentArrowSystem.cs
- Content.Shared/_Goobstation/CCVar/CCVars.Goob.cs
> Spamming pointers too fast makes them hunt you

- Resources/Prototypes/_Goobstation/Maps/leonid.yml
- Resources/Prototypes/_Goobstation/Maps/submarine.yml
submarine is a large map but has mid station config
leonid have huge asteroid area an an abundance of hiding space so using  huge config.
**Changelog**
:cl: Fishbait
- tweak: Blob now have a harder time on Submarine and Leonid
> adds blob config to submarine and leonid

- Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.cs
- Resources/Locale/en-US/_Goobstation/Changeling/store/changeling-catalog.ftl
- Resources/Prototypes/_Goobstation/Changeling/radio_channels.yml
- Resources/Prototypes/_Goobstation/Heretic/Actions/Heretic/basic.yml
also fixes ling hivemind and mansus link tooltips
**Changelog**
:cl:
- fix: Fixed mansus link.
> hotfix mansus link

- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
- Resources/Prototypes/Loadouts/loadout_groups.yml
- Resources/Prototypes/_Goobstation/Catalog/Fills/Belt/belts.yml
- Resources/Prototypes/_Goobstation/Loadouts/Jobs/Security/security_officer.yml
i forgor
i forgor
**Changelog**
:cl:
- tweak: Security Officers can now equip judo belts round start from the loadout menu.
- tweak: Judo belts now come filled with tools in security lockers.
> judo belt fill

- Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/vehicles.yml
Removed the ability to pick up a hoverchair that has someone on it, trapping them forever in your hand.
Also removed the horn because it was not working as intended.
Stipped the BaseItem parent from the hoverchair and the horn component
**Changelog**
> Fixes for Hoverchair

- Resources/Prototypes/_EinsteinEngines/Entities/Objects/Weapons/Melee/terminus.yml
yeag
**Changelog**
- tweak: Terminus is now usable by everyone :trollface:
> What do I even name this

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Allow any mouse instagib me
I just want to die
Death
💀
> Allow any mouse instagib me

- Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
:trollface:  lets not talk about this okay... second time this has happened..
**Changelog**
:cl:
- fix: Fixed heretics not being able to write runes.
> im sorry guys i keep breaking your beloved game

- Resources/Prototypes/Entities/Objects/Misc/implanters.yml
Forgor (and forgor to tell sol)
**Changelog**
:cl:
- fix: Deimplanter works on jaunter, mindcontrol implants
> Add goob implants to deimplanter

- Content.Shared/Damage/Systems/StaminaSystem.cs
- Content.Shared/_Goobstation/MartialArts/Components/GrantMartialArtKnowledgeComponent.cs
- Content.Shared/_Goobstation/MartialArts/Components/MartialArtsComponents.cs
- Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.CQC.cs
- Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.CorporateJudo.cs
- Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.SleepingCarp.cs
- Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.cs
more code cleanup 
**Changelog**
:cl:
- tweak: Sleeping carp scrolls are no longer locked to one person!
- fix: Questionable damage handling.
> :trollface: ooopsies

- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
Added heretics and their metashield rules. Mentioned wizards not being metashielded.
Too many problems with metagaming, this should have been updated a while ago
**Changelog**
:cl:
- add: Heretics metashield
- add: Wizards are not metashielded
> metashield updates

- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
wwdp put the disarmed combo event in a reallly bad spot.
**Changelog**
> [speedmerge] infinite ranged martial arts fix

- Content.Shared/Buckle/Components/StrapComponent.cs
- Content.Shared/Buckle/SharedBuckleSystem.Interaction.cs
- Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/clowncar.yml
problem whit unbuckle from passangers
**Changelog**
:cl: Fishbait
- fix: passanger being able to unBuckle bug.
> unbuckle bug

- Resources/Prototypes/_DV/Entities/Mobs/Species/harpy.yml
missing tag
:cl:
- fix: Fixed harpies being immune to anomaly infections.
> fix harpies not being able to host anoms

- Resources/Maps/_Goobstation/marathon.yml
- Resources/Maps/_Goobstation/omega.yml
- Resources/Maps/_Goobstation/packed.yml
Fixed an issue on the new NTR & BSO maps where NTR did not have access to the doors.
Hotfix
Replaced Airlock (BSO)
with Airlock (Central Command)
N/A
**Changelog**
:cl:
- fix: Fixed NTR not having access to their room on some maps.
> NTR Room Hotfix

- Resources/Prototypes/_Goobstation/Entities/Objects/Shields/shields.yml
Fixed BSO shield not recharging at all before getting broken for the first time.
I fucked up.
RechargeableBlocking only overrides BatterySelfRecharger on state change, before any state changes (so before the shield breaks for the first time) it doesn't, resulting in it not recharging 
**Changelog**
:cl:
- fix: Fixed Greatshield not recharging sometimes.
> bso shield hotfix

- Resources/Changelog/GoobChangelog.yml
- Resources/Prototypes/Entities/Objects/Fun/toys.yml
Made Rosef & myself gibbable via carp plushie with the gibthisguy comp.
This is hard to test in a local host, so I'll just hope it works.
I'm being bribed.
YAML
N/A
N/A
**Changelog**
:cl:
- add: Audrey & Aubrey White can now be gibbed with a carp plushie. Go wild.
> Make Rosef Gibbable Via Carp

- Content.Shared/_Goobstation/Vehicles/Clowncar/SharedClowncarSystem.cs
- Resources/Prototypes/_Goobstation/Actions/clowncar.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/clowncar.yml
clown car passangers are now stunned, so they can no longer damage the vehicle.
can still thank the driver, talk and scream. 
trying to walk will not produce sounds.
problem where youd crash whith the holopad is altso fixed
**Changelog**
:cl: Fishbait
- fix: passangers of the clowncar will now behave better
> clowncar now stuns passangers

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
AKMS > AKM
THE AKM HAS A FIXED STOCK THE AKMS HAS A FOLDING STOCK ITS A FUCKING AKM AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
removed one character
**Changelog**
:cl: JoeHammad
- fix: Fixed my autism
> One character AKM change

- Resources/Maps/_Goobstation/reach.yml
fixed one airlock in arrivals on reach being unpowered
no power = bad
fix = good
just wiring, no need for a render
**Changelog**
> fix reach wiring in arrivals

- Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml
it's broken
Mainly cuz it lets you throw people across the entire station (real)
Revert it if you fix it, or don't, baseball bat is already good weapon anyways
> unbork baseball bat

- Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.KravMaga.cs
- Resources/Prototypes/_Goobstation/MartialArts/judo.yml
**Changelog**
:cl:
- tweak: Restored Judo's combos to their original set of moves.
- tweak: Krav maga leg sweep now does stamina damage instead of just a knockdown.
> Return to SS13 Parity

- Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
- Content.Shared/_Goobstation/Wizard/Components/SwapSpellComponent.cs
- Content.Shared/_Goobstation/Wizard/SharedSpellsSystem.cs
- Content.Shared/_Goobstation/Wizard/SpellEvents.cs
- Resources/Prototypes/_Goobstation/Actions/implants.yml
- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Jaunter cannot be used through walls now (still can be used through windows) and choose secondary target. Wizard spell is unaffected.
Jaunter costs 30 instead of 100 TC now.
Jaunter CD is 60 instead of 5 seconds now.
So it's more useful, less annoying and actually has its place in the game instead of fucking making no sense who put T3 wizard spell (though a pretty useless one) in the uplink
tested works
**Changelog**
:cl:
- tweak: Jaunter Implant now cost 30 TC, but has higher cooldown, no longer works through walls and doesn't let one choose a secondary target.
> make jaunter implant more sane

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
I hope this message finds you well, thriving in the air ducts, and enjoying the occasional crumb that inevitably finds its way into your domain. I write to you today with a heavy heart, a slightly bruised ego, and a profound sense of regret. It has come to my attention that a recent... ahem... "adjustment" to the station's operational protocols has granted you the ability to dispatch me, a mere human, with a single strike. While I understand that this may seem like a thrilling upgrade to your already impressive skill set, I feel compelled to explain myself and, hopefully, earn your forgiveness.
First and foremost, let me say this: I never intended to create a universe where you, the noble mice of this station, could reduce me to a lifeless heap with but a flick of your mighty paws. It was …
> To the Esteemed Mice of Space Station 

- Resources/Changelog/GoobChangelog.yml
> shitcodbot

- Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
- Resources/Prototypes/Hydroponics/seeds.yml
Replaced bicaridine in lilies with styptic powder, and replaced the dermaline in aloe with silver sulfadiazine.
Lilies are reskinned poppies that only exist to make getting spaceman's trumpet harder, and this gives them a unique chemical. Dermaline in aloe is bad, because chemists can easily make a lot of it before botany can grow any. Silver sulfadiazine from aloe is still slower than what chemistry can make, but since it's complicated to make, it might be worth growing it.
Fifty potency version of both plants from using Robust Harvest.
**Changelog**
:cl: RatherUncreativeName
- tweak: Lilies have Styptic Powder and Aloe has Silver Sulfadiazine
> Botany new chems

- Content.Client/_Shitmed/Autodoc/AutodocProgramWindow.xaml.cs
- Content.Client/_Shitmed/Autodoc/AutodocWindow.xaml
- Content.Client/_Shitmed/Autodoc/AutodocWindow.xaml.cs
- Content.Shared/_Shitmed/Autodoc/Systems/SharedAutodocSystem.cs
clean up shitcode from program importing pr
uses dependencies, better error log (actually includes the error), put abort button on its own line to not have the window be extremely wide
> cleanup autodoc shitcode

- Content.Server/_Goobstation/Blob/BlobbernautSystem.cs
check diff
obviously a bug from context
balance-wise it's fine
**Changelog**
:cl:
- fix: Blobbernauts now properly make explosions for explosive blob and EMP for EMP blob.
> fix blobbernaut attack

- Resources/Prototypes/_Goobstation/Catalog/Cargo/cargo_livestock.yml
- Resources/Prototypes/_Goobstation/Catalog/Fills/Crates/npc.yml
Found arbitrage on BountyFood cargo bounty! Product LivestockLootbug costs 3000 but fulfills bounty BountyFood with reward 4000!
:cl: pheenty
- tweak: Lootbugs now come in crates of three for 2200 spesos instead of crates of four for 3000.
> fuck this test

- Resources/Prototypes/Entities/Structures/Power/smes.yml
Title
Requested, + alot of labor to do this
:cl: Armok
- tweak: Buff Full SMES Price by 3x
> Buff Full SMES selling price by 3x

- Content.Goobstation.Shared/Content.Goobstation.Shared.csproj
fixes cling fucking up and any other autogenned networked comp in shared
> Fix network generation

- Resources/migration.yml
> nuked BibleAtheist

- Content.Goobstation.Common/Content.Goobstation.Common.csproj
- Content.Goobstation.Common/GlobalUsings.cs
fixes silo and other stupid things
> fix common netgen

- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Rifles/rifle.yml
https://github.com/space-wizards/space-station-14/pull/34971
you can dodge a fuckin bullet by strafing???
**Changelog**
:cl:
- tweak: Bullet speeds have been doubled.
> Fastbullet

- Resources/Prototypes/Entities/Mobs/Player/jaunt_mobs.yml
- Resources/Prototypes/_Goobstation/Heretic/Entities/Mobs/NPC/polymorph.yml
Fixes heretic jaunt flying at insane speeds when aghosts follow it.
It's a yaml change, should be safe to merge.
For some reason heretic jaunt had GhostImpassable fixture mask while ghosts had GhostImpassable fixture layer. Heretic jaunt is KinematicController while aghosts are Kinematic - this makes them collide with each other.
Inherited heretic jaunt from BaseMobJaunt (which has GhostImpassable layer, not mask) just like wiz jaunt.
**Changelog**
:cl: Aviu
- fix: Fix heretic jaunt freaking out when admin ghost follows it.
> Fix heretic jaunt

- Resources/Prototypes/_Goobstation/MisandryBox/debdeb01.yml
- Resources/Prototypes/_Goobstation/MisandryBox/rhmborsigwt.yml
RhmBorsigWT and DEBDEB01 are now forever cursed with incomprehendable russian accent
they both want it, ask them
everything was done before me so it's just yaml with durk deciding if they deserve it or not
**Changelog**
> curse two people with russian accent

- Resources/Prototypes/_Lavaland/Entities/Clothing/explorer_suit.yml
explorer suit is cargo contraband and has stunbaton resistance (but no stamres)
numbers in line with https://github.com/Goob-Station/Goob-Station/pull/2123 (slightly worse than armor vest)
because it should have it, we just forgor
**Changelog**
> give explorer suit stun baton res

- Content.Shared/CCVar/CCVars.Interactions.cs
the amounts of inventryes that can be open at one time. from one to five
powergaming maxing.
change a cvar from 1 to 5 
**Changelog**
:cl: Fishbait
- tweak: Changed the ammounts of ui inventory windows you can have open at one time
> Increse the ammount of inventry you can have open at one time

- .github/workflows/build-map-renderer.yml
- .github/workflows/build-test-debug.yml
- .github/workflows/check-crlf.yml
- .github/workflows/reusable-checkout.yml
- .github/workflows/reusable-setup.yml
- .github/workflows/rsi-diff.yml
- .github/workflows/test-packaging.yml
- .github/workflows/validate-rgas.yml
- .github/workflows/validate-rsis.yml
- .github/workflows/validate_mapfiles.yml
- .github/workflows/yaml-linter.yml
> Better Workflows Test

- Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
- Resources/Locale/en-US/_white/store/uplink-catalog.ftl
Fix some misinformation in uplink catalogue
> Fixes some uplink descriptions

- Resources/Locale/en-US/_Goobstation/Heretic/store/heretic/heretic-catalog-flesh.ftl
- Resources/Prototypes/Entities/Clothing/Masks/masks.yml
- Resources/Prototypes/_Goobstation/Heretic/Heretic/heretic_rituals.yml
- Resources/Prototypes/_Goobstation/tags.yml
Changes the requirement in the voiceless dead ritual for heretics from a poppy to a muzzle.
It's weird locking this ritual behind an item that literally only ONE job can get easily.
Plus, 'tis a bounty.
YAML
N/A
N/A
**Changelog**
:cl:
- tweak: Voiceless dead ritual now requires a muzzle instead of a poppy.
> Change poppy to Muzzle in voiceless dead [BOUNTY]

- Resources/Locale/en-US/accent/cowboy.ftl
- Resources/Prototypes/Accents/word_replacements.yml
Bounty, doesn't fit with other cowboy accents. Commonly used in northern UK.
https://discord.com/channels/1202734573247795300/1361273986327253043/1361273986327253043 - bounty
**Changelog**
:cl:
- remove: Cowboy accent no longer replaces wow with by gum.
> Remove Cowboy "wow" to "By gum" replacement.

- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Reverts Goob-Station/Goob-Station#2364
> Revert "Remove anaconda from nukie uplink"

- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_hammer.yml
Reverts Goob-Station/Goob-Station#2355
> Revert "Tweak changeling armblade damage"

- Content.Goobstation.Server/Fishing/FishingSystem.cs
- Content.Goobstation.Shared/Fishing/Systems/SharedFishingSystem.cs
Fixed fishing killing client, fixed the game being unplayable.
I could have reverted fishing but mocho told me to fix instead.
Add a million TerminatingOrDeleting checks to make sure the entities we are referring to some entity that was deleted clientside due to being out of pvs range.
Tested, fishing works, client doesn't crash when out of pvs range.
**Changelog**
:cl: Aviu
- fix: Fix fishing breaking the game.
> Hmm... What if this entity doesn't exist?

- Resources/Prototypes/Entities/Structures/Walls/walls.yml
- Resources/Prototypes/_Goobstation/Wizard/gear.yml
- Resources/Prototypes/_Goobstation/Wizard/spellbook_catalog.yml
Reverts Goob-Station/Goob-Station#2341
> Revert "Lich and forcewall nerf"

- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/game_presets.yml
add subgamemode support to gamedriector ruels
**Changelog**
:cl:
- fix: Thieves should now appear in game director!
> subgamemodes for gamedirector

- Content.Server/Disposal/Unit/EntitySystems/DisposalUnitSystem.cs
basically revert pr that fixed disposal speedflushing bug
its skill/ping expression and great for shitters/antags to escape sec
**Changelog**
:cl:
- add: Brought back disposal unit speed flush.
> bring back disposal speedflush

- Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
This reverts commit 0d05bb6a
**Changelog**
:cl: The Independent State of Chemlabia
- fix: Fixed syringes being breakable.
> Revert "Syringes can now be destroyed (#2387)"

- Content.Goobstation.Server/StationEvents/GameDirectorSystem.cs
- Content.Goobstation.Server/StationEvents/Metric/AnomalyMetric.cs
- Content.Goobstation.Server/StationEvents/Metric/CombatMetricSystem.cs
- Content.Goobstation.Server/StationEvents/Metric/DoorMetricSystem.cs
- Content.Goobstation.Server/StationEvents/Metric/FoodMetricSystem.cs
- Content.Goobstation.Server/StationEvents/Metric/PuddleMetricSystem.cs
**Changelog**
:cl:
- add: Added metrics to game director, doesn't actually do anything player facing, but this means it should be easier for us to make game director suck less now.
> Game Director Logging

- Resources/Prototypes/_Goobstation/Entities/Objects/Devices/pda.yml
Fixes the border colors of the deathsquad PDA from the default centcomm green
I HAVE to yaml. All the time. Or I get this... this ITCH. It must be hardwired into my brain or something. Oh! But when I DO yaml... ohhhhh, man alive! Nothing feels better. It's just... why I've gotta yaml, I've gotta yaml!
3 lines
**Changelog**
:cl:
- fix: fixed deathsquad PDA colors
> goob is saved forever

- Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
- Resources/Prototypes/Entities/Objects/Tools/welders.yml
- Resources/Prototypes/_EinsteinEngines/Damage/modifier_sets.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
- Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
ipcs have 100 instead of 120 hp, damage resistances and healing changed accordingly to ensure the same EHP and heal efficiency
it always annoyed me, why do they have 120 health instead of just having resistances
they are now like 2% more resistant to brute and 3% less resistant to lasers but who cares
**Changelog**
:cl:
- tweak: Instead of having 20% more health, IPCs now take 20% less brute damage. Other values changed accordingly, this is only a cosmetic change.
> make ipcs make sense

- Content.Server/GameTicking/Rules/Components/TraitorRuleComponent.cs
- Resources/Locale/en-US/_Goobstation/flavors/traitor.ftl
- Resources/Prototypes/_Goobstation/Datasets/traitor_flavor.yml
Adds a new tot faction, the NVF, or Neulithiv Visionary Federation.
This also fixes the locale issues if Gus's doesn't get merged first.
I want to give traitors weird magic items.
Issue: None of the syndicate companies make magic shit.
Solution: New syndicate company that makes magic shit.
It's that shrimple.
**Changelog**
:cl:
- add: Added new syndicate faction - Neulithiv Visionary Federation
> New tot faction

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Mice can no longer shove
"I literally just had the entirity of chemistry blown up by a mouse. If the guy who read it did it. Congrats. I had to commit ritual seppuku for it."
1 line of yaml
**Changelog**
:cl: Muppet
- tweak: Mice can no longer shove (sorry).
> mice take anger management classes

- Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/bingle.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/Player/bingle.yml
Bingles now display as "Team Antagonists" in the Admin UI overlay
Bingle
Bingle
Bingle
> Make Bingles Team Antagonists

- Resources/Prototypes/_Shitmed/Entities/Specific/Abductor/surgery.yml
makes abductor pinchers into really fast barber scissors
BALD
V
tested, works
**Changelog**
:cl:
- add: Abductor pinchers can now be used as barber scissors.
> glorp zap bald glorpship shitsec zop

- Content.Server/Traitor/Uplink/SurplusBundle/SurplusBundleSystem.cs
- Resources/Prototypes/Catalog/uplink_catalog.yml
surplus can now roll surplus
also fixes a misc bug where a surplus couldn't roll anything with a store blacklist, aka anything blocked from contravend
gambling
tested, works
**Changelog**
- add: Syndicate surpluses can now roll more surpluses.
> gambling gambling ultimate

- Resources/Changelog/GoobChangelog.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
- Resources/Prototypes/Objectives/traitor.yml
china is now back to wizden 1 firerate, it's still pump action slowing it down so it should be fine?.. even after the nerf burner seems a preferable option for nukies
ce's singubuster is multihanded, you can't put it on your suit storage and its 6x3 in backpack, so CEs only use it during like warops and not to validhunt lesser threats, i could have reduced its damage but that would be lame. also it's no longer a steal target as aviu requested, it was stupid for a consumable item to be highrisk in the first place tbh
**Changelog**
:cl:
- tweak: China lake is back to 1 firerate. Still pump action.
- tweak: Singularity buster is greatly increased in size and is no longer a steal target.
> explosive stuff

- Resources/Locale/en-US/_Goobstation/tools/tool-qualities.ftl
- Resources/Prototypes/Entities/Objects/Misc/paper.yml
- Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
- Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Misc/space_cash.yml
- Resources/Prototypes/_Goobstation/Recipes/Construction/Graphs/misc/spesos.yml
- Resources/Prototypes/_Goobstation/tool-qualities.yml
apply spray painter to paper and wait 5 seconds to make 10 sus spesos
they're major contra and have obvious name and description but work as real spesos
tider sweatshop printing spesos
shouldn't really affect much since the rate you can do this at isn't high at all
also they're major contra so sec will get angry and command allowing this would be illegal
tested, works
**Changelog**
:cl:
- add: You can now make counterfeit spesos by applying a knife then a spray painter to paper. Law enforcement might not be happy, though.
> counterfeit spesos

- Content.Goobstation.Server/Devil/Condemned/CondemnedSystem.OnDeath.cs
- Content.Goobstation.Server/Devil/Condemned/CondemnedSystem.cs
- Content.Goobstation.Server/Devil/Contract/DevilContractSystem.cs
- Content.Goobstation.Server/Devil/DevilSystem.cs
- Content.Goobstation.Server/Possession/PossessedComponent.cs
- Content.Goobstation.Server/Possession/PossessionSystem.cs
- Content.Goobstation.Shared/Devil/Condemned/CondemnedComponent.cs
- Content.Goobstation.Shared/Devil/Contract/DevilContractComponent.cs
- Content.Goobstation.Shared/Religion/Nullrod/DamageUnholyEvent.cs
- Content.Goobstation.Shared/Religion/UnholyItemComponent.cs
- Content.Goobstation.Shared/Religion/WeakToHolyComponent.cs
- Content.Goobstation.Shared/Religion/WeakToHolySystem.cs
- Resources/Prototypes/Damage/containers.yml
- Resources/Prototypes/_Goobstation/Roles/mind_roles.yml
- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
Fixed various bugs with devil.
Bugfixes
Forgot some lines.
N/A
**Changelog**
:cl:
- fix: Fixed several issues with devil.
> Devil Fixes

- Content.IntegrationTests/Tests/Power/PowerTest.cs
- Content.Server/Power/Components/PowerSupplierComponent.cs
- Content.Server/Power/Pow3r/PowerSolverShared.cs
- Content.Server/Power/Pow3r/PowerState.cs
power suppliers will now also ramp by % of current supply like teg
needed for rad collectors and other power generators to not chud out when powering PTL
tested by hooking a debug generator with very high max limit to PTL
**Changelog**
:cl:
- fix: Fixed radiation collectors with very high maximum output ramping very slowly.
> exponential power ramping

- Content.Goobstation.Server/EventHorizonIgnore/EventHorizonIgnoreComponent.cs
- Content.Goobstation.Server/EventHorizonIgnore/EventHorizonIgnoreSystem.cs
- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/energyball.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/generator.yml
- Resources/Prototypes/_Goobstation/tags.yml
- teslas no longer eat each other
- teslas now collide with other teslas
- teslas no longer eat tesla gens so you can tesla ball pit easily
fun
tested, works
acts like normal if loose
**Changelog**
:cl:
- add: Teslas can now bounce off each other.
- add: Tesla generators are now immune to teslas.
> bouncy tesla

- Content.Goobstation.Server/Blob/BlobFactorySystem.cs
- Content.Goobstation.Server/Blob/Components/BlobFactoryComponent.cs
makes blob factories be limited to 3 *alive* blob drops, not 3 total
crew powercreep with weswords tech tree etc has now made blob die every time
blob needs a buff right now
tested, works
**Changelog**
:cl:
- tweak: Blob factories are now limited to 3 alive and not total blob drops.
> ungimp blob factories

- Resources/Locale/en-US/_Goobstation/servercurrency/server_currency.ftl
- Resources/Prototypes/_Goobstation/GameRules/Admeme/token.yml
- Resources/Prototypes/_Goobstation/ServerCurrency/token_listings.yml
Fixed Naming systems for Token LoneOps and Ninja spawns.
Fixed Hat Token storefront Name/Desc
Marked Wizards as an exception to the Antag token
Minor fixes
> Fix Ninja/Loneops Token Naming + Token Store Hat 

- Content.Server/_DV/CosmicCult/CosmicGlyphSystem.cs
Fixed cult.
Cherry-picked from Delta-V.
**Changelog**
:cl: deltanedas
- fix: Fixed cosmic cultists not being able to use glyphs.
> cult conversion hotfix

- Content.Goobstation.Server/Explosion/Components/TriggerOnVoiceIdLockedComponent.cs
- Content.Goobstation.Server/Explosion/EntitySystems/TriggerSystem.Voice.IdLocked.cs
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/security.yml
pepperspray works
Pepperspray can now correctly refill.
You can no longer blow up hos by yelling "I AM THE LAW"
bug fixy
N/A
N/A
N/A
**Changelog**
:cl:
- fix: Pepperspray can now correctly refill at dispensers.
- fix: You can no longer blow up hos by yelling "I AM THE LAW". Looking at you Conrad, not cool..
> sec stuff tweaks

- Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml
Cosmic Cult and Heretics may no longer roll in the same round.
because no way our  security is capable of handling both of these at the same time in any capacity properly..
**Changelog**
:cl:
- tweak: Cosmic Cult and Heretics may no longer roll in the same round.
> dear lord save us from this hell (this is not a mald pr i swear)

- Content.Goobstation.Common/CCVar/CCVars.Goob.cs
- Content.Goobstation.Server/Shuttle/ShuttleImpactSystem.cs
- Content.Server/Physics/Controllers/MoverController.cs
- Content.Server/Shuttles/Components/ShuttleComponent.cs
- Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
- Resources/Prototypes/Entities/Structures/Walls/walls.yml
- Resources/Prototypes/_Shitmed/Entities/Structures/Walls/walls.yml
added a bunch of extra behaviors to make it behave nicer
shuttle speed cvarred and further raised to 60 because i found it to have no issues
variables were picked to make cargo shuttle behave about the same as it did
read CL for how this affects the game
adds extra behaviors to fix oversights i've observed
tested ingame, works
**Changelog**
:cl:
- add: Abductor walls can now be destroyed.
- add: Large grids can now deal impact damage at lower velocities. Enjoy your colony drops.
- tweak: Walls should now matter more for impact damage.
- tweak: Shuttle speed further raised to 60.
- tweak: Impact damage to non-structures reduced, and to structures increased.
- fix: Impact damage can no longer destroy tiles under things without destroying them first.
> shuttle impact tweaks

- Content.Packaging/ClientPackaging.cs
- Content.Packaging/ModuleDiscovery.cs
- Content.Packaging/ServerPackaging.cs
> Make Sure ModuleManager is Packaged Last GOIDAMERGE (safe publish after)

- Content.ModuleManager/Content.ModuleManager.csproj
- Content.Packaging/Content.Packaging.csproj
- Directory.Packages.props
Dosent matter as ASMResolver isnt getting called in sandbox but still looks better this way
> Proper Project References 

- Content.Goobstation.Server/Shuttle/ShuttleImpactSystem.cs
i decided to test it some more and discovered velocity just randomly NaN-ing in localhost
this fixes it
> shuttle impacts hotfix

- Resources/Locale/en-US/_white/examine/examine.ftl
i forgor one ftl file :skvll:
smartest goob coder
no cl no fun
> Fixes small whoopsie in FTL with the lifeweb inspects lmao

- Content.Shared/_Shitcode/Heretic/Systems/SharedMansusGraspSystem.cs
Shadow cloak no longer dies instantly to rust mansus grasp.
bug.
1 line diff.
**Changelog**
:cl: Aviu
- fix: Fix shadow cloaked heretic dying instantly to rust mansus grasp.
> Shadow cloak fix

- Content.Goobstation.Client/Waddle/WaddleAnimationSystem.cs
- Content.Goobstation.Server/Waddle/WaddleAnimationSystem.cs
- Content.Goobstation.Shared/Waddle/SharedWaddleAnimationSystem.cs
- Content.Goobstation.Shared/Waddle/WaddleAnimationComponent.cs
- Content.Goobstation.Shared/Waddle/WaddleClothingSystem.cs
- Content.Goobstation.Shared/Waddle/WaddleWhenWornComponent.cs
- Resources/Prototypes/Entities/Clothing/Shoes/misc.yml
- Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
added my non-goidacode rewrite of waddling
probably fucked with flips emote but whatever
**Changelog**
:cl:
- add: Added waddling.
> add waddling

- Content.Goobstation.Shared/Content.Goobstation.Shared.csproj
- Content.Goobstation.Shared/MisandryBox/Helpers/ColorExt.cs
- Content.Goobstation.Shared/MisandryBox/Saturation/SaturationRequirement.cs
- Resources/Locale/en-US/_Goobstation/MisandryBox/HairSaturation.ftl
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
LICENSE: MPL
SaturationRequirement job requirement which allows or denies a role based on the character's hair color saturation (not hue or brightness). Inverted to require neon hair.
Dress code violation
`Color` has an extension method to convert to HSV, available to types that see Goobstation.Shared.
**Changelog**
> Hair saturation job requirement

- Resources/Prototypes/_Goobstation/Damage/modifier_sets.yml
I have halved Ion damage to mechs
because as of current a single individual with an ion rifle can kill a dark Gygax in 8 shots, this turns it into 15 shots meaning that it is still a viable counter without fully killing the idea of mechs.
yaml maxxed and just halved a number
**Changelog**
:cl:
- tweak: Made mechs viable again
> Lets make mechs great again

- Resources/Prototypes/Body/Organs/diona.yml
- Resources/Prototypes/Body/Organs/human.yml
- Resources/Prototypes/Body/Organs/slime.yml
Added Just enough cognizine to Sentient brains
It gives a use to catatonic brains. Instead of lying on the floor of medbay, it can be used to create ghost roles instead.
Added 5u of Cognizine to Human, Diona, and slime brains in the organ and food solution manager. 
https://github.com/user-attachments/assets/844174fa-62b1-46ba-a88c-2c21d96c094a
**Changelog**
:cl: - tweak: Added Cognizine to sentient brains
> Added Cognizine to sentient brains

- Resources/Prototypes/_Goobstation/Maps/atlas.yml
Title. It DID have spawnpoint but no slot. Chose to add only one cuz it's cramped asf.
https://github.com/Goob-Station/Goob-Station/issues/2530
No
No
No
:cl:
- fix: Atlas finally has lawyer slot.
> Add lawyer jobslot to atlas

- Resources/Prototypes/Recipes/Reactions/fun.yml
5 oil 3 ash 2 sulfacid now produces 5 plastic instead of 1.
chemistry was always supposed to be the main plastic source (that's why it's not mineable in the first place), yet when chems became limited chemistry can't make any reasonable amount of plastic anymore, neither we have other ways of obtaining plastic, besides cargo, which is supposed to be always reliable but ineffective source and not the main one.
**Changelog**
:cl:
- tweak: Cooking plastic in chemistry now yields five times more sheets.
> make chemistry able to reasonably produce plastic

- Resources/Locale/en-US/_Goobstation/station-laws/laws.ftl
- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/_Goobstation/silicon-laws.yml
- Resources/Prototypes/silicon-laws.yml
Added a new lawset, chudimov.
Nothing ever happens.
law-chudimov-1 = You are a chud. You are to ensure nothing ever happens.
law-chudimov-2 = Prevent anything from happening
law-chudimov-3 = Prevent anyone from causing anything to happen.
law-chudimov-4 = Nothing ever happens.
N/A
N/A
**Changelog**
:cl:
- add: Added a new lawset for AI. Purchasable by assistant and clown syndicates.
> Chudimov Lawset

- Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
Fixed a typo with bloodpacks where they took blood instead of fixing it.
Bug fix
added a -
I didn't test this.
It's ALL broken.
**Changelog**
:cl:
- fix: Bloodpacks are no longer vampiric. (This means they actually restore blood.)
> Bloodpack Fix

- Resources/Prototypes/Entities/Objects/Fun/Instruments/base_instruments.yml
now don't have to be in active hand or in hands at all
good
**Changelog**
:cl:
- tweak: Music instruments no longer need to be in your active hand.
> make instruments less annoying

- Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Borgs now have access to a hammer in their tools module.
I saw it in the bad ideas thread and thought "Yeah, that's kinda funny."
Malf AI needs their malf borgs to have better weapons. This dethrones surgical module mediborg as the best combat borg and gives every other chassis a competent melee weapon.
Plus, borgs beating shit with hammers is funny as fuck.
One line YAML change.
N/A
N/A
**Changelog**
:cl:
- add: Cyborgs now get hammers in their tool modules. Go crazy.
> It's hammer time.

- Content.Shared/Body/Components/BodyComponent.cs
- Content.Shared/_Shitmed/Surgery/Wounds/Components/WoundableComponent.cs
- Content.Shared/_Shitmed/Surgery/Wounds/Systems/WoundSystem.Wounding.cs
- Content.Shared/_Shitmed/Surgery/Wounds/Systems/WoundSystem.cs
- Resources/Changelog/GoobChangelog.yml
gus request
**Changelog**
:cl:
- fix: Woundmed shouldn't passively lag out the server anymore.
> delaggening

- Content.Goobstation.Shared/Skinnable/SkinnableComponent.cs
armok, with due respect, DO NOT FUCKING TOUCH C#
> fix the game

- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
It goes faster now cause there are a billion footprints
:cl: Armok
- tweak: Mop is faster
> buff Janitor mop

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
bug fix
Made it so that kobolds are no longer skinnable
Moved skinnable component from base genetic ancestor into the monkey prototype
**Changelog**
:cl:
- fix: kobolds are no longer skinnable
> fixed skinnable kobolds

- Content.Server/GameTicking/GameTicker.StatusShell.cs
gonna add queue display to the discord bot
> Add queue to /status endpoint

- Content.Goobstation.Shared/MisandryBox/Hair/MarkingManagerExt.cs
- Content.Goobstation.Shared/MisandryBox/Hair/SaturationRequirement.cs
- Content.Goobstation.Shared/MisandryBox/Hair/StyleRequirement.cs
- Resources/Changelog/GoobChangelog.yml
- Resources/Locale/en-US/_Goobstation/MisandryBox/HairStyle.ftl
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> Hairstyle job requirement, tear floorlengths away from hos

- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/energyball.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/generator.yml
Teslas once again eat other teslas and tesla generators
I hate fun
Engineering is incompetent leading to 4 teslas eating the station 20 minutes in
**Changelog**
:cl:
- remove: Removed tesla ballpits
> Remove tesla ballpit

- Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
I dont know who made it giga aids but it sucks ass
:cl: Armok
- tweak: SM grenade doesnt push as erratically anymore
> Unchudify the SM grenade

- Content.Goobstation.Server/Footprints/FootprintSystem.cs
- Content.Server/Fluids/EntitySystems/PuddleSystem.cs
- Content.Shared/Chemistry/Reagent/ReagentPrototype.cs
- Resources/Prototypes/Reagents/cleaning.yml
- can't crawl-walk to avoid slippage anymore
- now doesn't stick to skin:
- no footsteps
- not consumed by getting onto skin on slip
good
tested, works
also tested mixing it with other stuff, still works
**Changelog**
:cl:
- tweak: You can't mop lube by slipping on it anymore.
- fix: You can't avoid slippage by crawl-walking over it either.
> lube tweaks

- Content.Goobstation.Common/CCVar/CCVars.Goob.cs
- Content.Goobstation.Server/Shuttle/ShuttleImpactSystem.cs
significantly optimise shuttle impacts (2x+)
tested by impacting oasis with its perma
**Changelog**
:cl:
- fix: Shuttle collisions should now cause much less lag.
> shuttle impact optimisations

- Content.Goobstation.Server/Hostname/DynamicHostnameSystem.cs
tests are failing because of editing cvars while they are running so intead of making it in update we just call it on cvar change
**Changelog**
> remove shitcode

- Content.Shared/Inventory/InventorySystem.Equip.cs
- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
---------
all outer clothing has suit storage, not just winter coats/armor
>ultimate drip
>most guns have two-point straps + everyone can see the assault rifle on your back so good luck hiding it from sec, not to 
mention everyone spamming E on you to see what you are wearing
ports https://github.com/DeltaV-Station/Delta-v/pull/3265
**Changelog**
:cl:
- add: Enabled suit storage for all outer clothing.
> [Port] all outer clothing have all suit storage

- Content.Goobstation.Common/Weapons/Multishot/MultishotComponent.cs
- Content.Goobstation.Shared/Atmos/Components/FirefighterTankRefillableComponent.cs
- Content.Goobstation.Shared/Atmos/EntitySystems/FirefighterTankRefillableSystem.cs
- Content.Goobstation.Shared/Weapons/Multishot/SharedMultishotSystem.cs
> Remove static datafields

- Resources/Prototypes/_Lavaland/Actions/cursed_heart.yml
it was supposed to be like this
:cl: Armok
- tweak: Cursed heart works while crit
> Fix cursed heart

- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> the start of the brigmedic mapping

- Content.Goobstation.Client/DragDrop/GoobDragDropSystem.cs
- Content.Goobstation.Server/DragDrop/GoobDragDropSystem.cs
- Content.Goobstation.Shared/DragDrop/DragDropTargetableComponent.cs
- Content.Goobstation.Shared/DragDrop/SharedGoobDragDropSystem.cs
- Content.Server/Construction/ConstructionSystem.Initial.cs
- Resources/Prototypes/Entities/Objects/Specific/Mech/mech_construction.yml
fixes several issues including biomass reclaimer chudding and mice being able to build
tested, at least pretends it's working
**Changelog**
:cl:
- fix: Lack of 1984. (Mice can't build girders and windows anymore.)
- fix: Biomass reclaimer should work again. - Mocho Note: Keep in mind it still only works with catatonic entities, so behead anything you throw in there to defeat the point of it
- fix: Borgs can now properly build mechs.
> borg drag-drop hotfix

- Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/armour.yml
very slightly nerfed warden and hos winter coats so they're not a direct upgrade to non-winter ones
made bso armor vest 2x2 as armored jackets are already 2x2, the vest has no reason to be worse yet being more compact is not enough to neft the armor so i buffed the vest instead
**Changelog**
:cl:
- tweak: Warden's and head of security's armored winter coats now have very slightly less armor.
- tweak: Blueshield's armor vest is now 2x2.
> kill powercreep

- Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
Shadowkin can spawn with Survival Boxes.
Fixes #2907 
Someone forgot to.
ONE SINGLUAR LINE OF YAML.
Actually so unnecessary but I was bored
https://github.com/user-attachments/assets/73e57b49-ae24-4100-b750-c5b7481e154a
**Changelog**
:cl:
- fix: After a long legal battle, Nanotrasen has decided Shadowkin can have Survival Boxes.
> Shadowkin Box Fix

- Resources/Prototypes/_Goobstation/Entities/Structures/Machines/tcprinter.yml
One line of fucking yaml.
**Changelog**
:cl: Security Chuds
- fix: Telecrystal miner flatpacks are just as contraband as the machine it holds. Any cadet saying it's not is to be taken out back and ~~shot~~ fired.
> Funny moment

- Resources/Locale/en-US/_EinsteinEngines/power/batteryDrinker.ftl
> MAJOR SPELLING MISTAKE ALERT

- Resources/Maps/_Goobstation/marathon.yml
see https://github.com/Goob-Station/Goob-Station/pull/2823
> brigmed marathon

- Resources/Prototypes/_Goobstation/Recipes/Construction/Graphs/furniture/altars.yml
You can't anymore dupe filling of emergency toolboxes
Bug
YAML
**Changelog**
🆑 
- fix: You can't anymore dupe filling of emergency toolboxes
> [FIX] You can't anymore dupe filling of emergency toolboxes

- Resources/Prototypes/Entities/Structures/Power/Generation/solar.yml
- Resources/Prototypes/Recipes/Construction/Graphs/utilities/solarpanel.yml
- Resources/Prototypes/_Goobstation/Recipes/Construction/structures.yml
makes solar panels constructible with just materials and capacitors
good
gives them a niche as a power source and allows you to bootstrap power if needed
having to buy them from cargo is too clunky for how little they make so nobody does it ever
**Changelog**
:cl:
- add: You can now build solar panels directly.
> solar panel construction

- Resources/Prototypes/Entities/Structures/Specific/Anomaly/cores.yml
Actual names for anomaly cores
I want to use them in crafting so people will need a way to differentiate them. 
Also why they all ware called just "anomaly core" in the first place???
.yaml
text.txt
none
**Changelog**
:cl:
- add: Names for anomaly cores.
> anomaly core names

- Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
try 2
also not kidding i've seen far more tiders shitting after this, and now I can't even blame them since they have nothing else to do
**Changelog**
:cl:
- tweak: World has been saved, assistants have maints access once again.
> Revert 2892 cull the tide

- Resources/Prototypes/_Goobstation/Entities/Objects/Shields/shields.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/energy_speedloaders.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Lever/lever.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/blueshield_mace.yml
the mald... https://discord.com/channels/1202734573247795300/1380212020955189278
also free gc
tldr ~~gave shield half of its old self recharge back~~ but pretty much nerfed everything else
speedloaders plot (you cannot juggle them around at low charge anymore)
:cl:
- tweak: Energy speedloaders now need a delay before starting to self-recharge. Also their disabler bolts deal more ion damage.
- tweak: Chester firerate is reduced by 20%.
> [bounty] bso rebalance

- Content.Goobstation.Common/CCVar/CCVars.Goob.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Shared/CCVar/CCVars.Atmos.cs
reenables spacewind
also makes it push you and not throw at low velocities
good
magboots actually useful now
durk said it's fine lag-wise and was only disabled because piras wanted to
tested, works
**Changelog**
:cl:
- tweak: Spacewind has been reenabled (air flow can throw you).
> reenable goidawind

- Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
- Content.Server/StationEvents/Events/VentCrittersRule.cs
- Resources/Prototypes/DeltaV/GameRules/events.yml
- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/pests.yml
ports https://github.com/DeltaV-Station/Delta-v/pull/2517 and https://github.com/DeltaV-Station/Delta-v/pull/3495
also ports the mothroach and xeno vent spawn events
fix
tested, works
**Changelog**
:cl:
- add: Mothroach and xeno vent critter events.
- fix: Vent critter events now actually spawn several mobs.
> port delta-v vent critter fixes

- Content.Goobstation.Common/CCVar/CCVars.Goob.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Shared/CCVar/CCVars.Atmos.cs
Good job everyone we had it for like a day and everyone remembered how much it fucking sucks
> Revert "reenable goidawind"

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
Title
They asked
N/A
N/A
N/A
**Changelog**
I want them to still try, so no changelog.
> Brizby is no longer gibbed via carp plush.

- Content.Goobstation.Common/CCVar/CCVars.Goob.cs
- Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusComponent.cs
- Content.Goobstation.Server/StationEvents/SecretPlus/SecretPlusSystem.cs
- Content.IntegrationTests/Tests/_Goobstation/SecretPlus/SecretPlusTest.cs
- Content.Shared/GameTicking/Components/GameRuleComponent.cs
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_DV/CosmicCult/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/events.yml
- Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml
- Resources/Prototypes/_Goobstation/GameRules/secretplus.yml
- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/tags.yml
- zombies are now guaranteed to spawn alone
- fixed cosmic cult spawning too often and with too many other antags
- added test to check if all secret+-able gamerules have a chaos score assigned
- some code cleanup
- chaos'd chaos more, it's admeme anyway
needed
https://github.com/user-attachments/assets/d92e7845-508f-4cff-8518-afdd425fb37b
also might want to hike up playerRatio on the antag rules to have less antag spam since, as-is, antag spam will happen on normal secret too with current values (traitor+thief: 8 traitors + 4 latejoin traitors + thieves), and i'd guess we do still want multiantag
**Changelog**
:cl:
- tweak: Zombies are now guaranteed to spawn with no other antags.
- fix: Fixed cosmic cult being too common.
> batch of secret+ fixes

- Content.Goobstation.Common/Mech/MechEvents.cs
- Content.Goobstation.Shared/Mech/GoobMechSystem.cs
- Content.Server/NPC/Systems/NPCUtilitySystem.cs
- Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
- Resources/Prototypes/NPCs/utility_queries.yml
mechs now inherit faction of pilot
combat HTNs can now target inanimate objects with a faction
fix
**Changelog**
:cl:
- fix: Mechs no longer give you turret or NPC immunity.
> HTN+mech interaction fixes

- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rocket.yml
MAINT DIDNT MERGE MASTER BEFORE GOIDAMERGE AWARD
**Changelog**
no cl no fun
> (hot)fix massive yaml linter fail

- Content.Server/Atmos/Piping/Trinary/EntitySystems/GasFilterSystem.cs
- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/trinary.yml
closes #3161
also adds an exception for inline gas filters checking output pressure because they weren't even supposed to care about it, technically also a fix
**Changelog**
:cl:
- tweak: Inline gas filters now ignore input pipe pressure.
- fix: Fixed flipped gas filters being effectively flipped.
> fix flipped gas filter

- Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml
Check PR name
The little fella has no choice but to run into maints to survive. Poor little critter needs his glasses.
**Changelog**
:cl: OnsenCapy
- add: Added nightvision to headslugs.
> Adds nightvision to headslugs

- Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/kravmagagloves.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/base_contraband.yml
- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR15SpaceLaw.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
:cl: Armok
- tweak: Clarify how contraband works for sec / command in guidebook
- tweak: Restrict warden items to warden
> Fix a few contra things

- Resources/Prototypes/_Goobstation/Heretic/Entities/Mobs/NPC/eldritch_mobs.yml
fix
:cl: Armok
- tweak: Heretic summons now have AI, and walk at a normal speed. 
- tweak: Fleshstalkers immune to flashes.
> fix summons

- Resources/Prototypes/_Lavaland/Entities/Clothing/explorer_suit.yml
Why the fuck were slav armors stronger than nukie armors?!?
:cl: Armok
- tweak: Tone down insane salv armor values
> Who did this

- Resources/Changelog/GoobChangelog.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Fishing/fish.yml
Fished fish are now able to be butchered. They spawn fish meat, organs and liquids.
Fish have been added some time ago and it has been bothering me that players are not able to butcher them. Now they can!
I added "SimpleMobBase" as a parent to the fish to made it to behave more realistic fish. Well it dies super fast still to airloss, but it is supposed to. 
The base fish uses "water" as blood, but I added the clown fish to use "laughter" as blood. And the blood values are very low 20.
https://github.com/user-attachments/assets/abc94ba4-14bd-47c6-a174-6f2c2e7abc17
- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
I believe nothing breaks.
**Changelog**
:cl: …
> Butchering fished fish spawns fish meat and stuff

- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Structures/Machines/bombs.yml
nukie bomb 26->25 TC
timer 180s->60s
nobody uses it because it gets disarmed every time and doesn't really even do anything
this way you can at do real damage and disarming it is an actual risk since bombsuits might not be nearby so tider can try sacrifice self to disarm it
you presumably buy this one to actually deal damage and not as a distraction since for distraction there's 10 TC fakebomb
**Changelog**
:cl:
- tweak: Syndicate bomb timer is now 60s.
> syndicate bomb buff

- Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/xenoartifacts.yml
I reverted wizdens increase in sentient artifact activation time.
Sentient artifacts should be able to activate more than 5 times in a round, they still gotta deal with durability so it is probaly not a problem.
Yaml
**Changelog**
:cl:
- tweak: Sentient artifact activation cooldown (5 -> 1 minutes)
> undoing wizden nerf on sentient artifact artivation time

- Resources/Prototypes/_Goobstation/MisandryBox/JobObjectives.yml
Upstream changed the RSI location in of the folders from beaurocracy to folders.rsi, I fixed this so everyone stops getting linter fails.
> Misandry Fix

- Resources/ServerInfo/Guidebook/Mobs/Species.xml
Fixed a typo in the guidebook.
Employed Human Interface Devices to operationalize a Vulpkanin directive using the GitHub web editor. (swapped two letters in a file)
Justice to the Vulpkanin!
**Changelog**
> Save the furry species

- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml
I've added the Cosmic Cult Metashield to the metashield rules. This was made by Atrophus.
Metashield for the Cosmic Cult. ~~We want more reasons to ban you.~~
**Changelog**
:cl: CerberusWolfie, Atrophus
- add: Added Cosmic Cult Metashield. Check Roleplay Rules 4!
> Add Cosmic Cult Metashield

- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/Entities/Clothing/Hands/colored.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Devices/flatpack.yml
The circuitboards for the ordering computers that spawn in the lockers are replaced with a flatpack
Engineering is excluded, they should know how to assemble a computer
HoP gets a flatpack for the funding computer
Alternative solution for [PR #3204 ](https://github.com/Goob-Station/Goob-Station/pull/3204)
As long these computers are not mapped give a easy way to install, multitools always can be borrowed or found everywhere
**Changelog**
:cl:
- tweak: Flatpacks instead of boards for ordering computers and funding computer
> QoL improvements for cargo related computers

- Content.Goobstation.Server/Implants/Components/ImplantGrantCollectiveMindComponent.cs
- Content.Goobstation.Server/Implants/Systems/ImplantGrantCollectiveMindSystem.cs
- Resources/Locale/en-US/_Goobstation/set-selector/selectable-sets.ftl
- Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
- Resources/Prototypes/Entities/Objects/Misc/implanters.yml
- Resources/Prototypes/_Goobstation/Catalog/selectable_sets.yml
- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
- Resources/Prototypes/_Goobstation/Entities/Markers/Spawners/Random/evil.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Misc/implanters.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Misc/subdermal_implants.yml
Added implant that grants access to silicon hivemind to traitors, as a replacement to the key removed in https://github.com/Goob-Station/Goob-Station/pull/2479
remove bad
fix good
**Changelog**
:cl:
- add: Returned syndicate binary encryption key in the form of an implant.
- fix: Smoke implant can now be removed.
> binary decoder implant

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/Fills/Items/firstaidkits.yml
- Resources/Prototypes/Catalog/uplink_catalog.yml
stimkit now comes with 8 mini-stimpacks, cost adjusted
half-filled medkit looks ugly as fuck
**Changelog**
:cl:
- tweak: Hyperzine injector kit now costs 40 TC and comes with 8 injectors.
> Make stimkit less ugly

- Content.Server/Speech/EntitySystems/FrontalLispSystem.cs
Capitalized Lisp regex replacement no longer all caps. Snow -> Thnow instead of Snow -> THnow
Improves lisp readability for people
**Changelog**
:cl:
- tweak: Lisp accent slightly more comprehensible
> makes the lisp accent slightly more comprehensible

- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Species/shadowkin.yml
This PR fixes a cosmetic bug that causes the shadowkin groin to appear over clothing and to have black splotches on the sides. This partially fixes #2988.
It was unappeasing to the eyes.
The PR adds two lines to the shadowkin entity YML, so that it properly draws the groin layer on the shadowkin sprite.
**Changelog**
:cl:
- fix: The lower half of the shadowkin sprite now properly appears underneath clothing.
> Fix shadowkin groin sprite clipping over other parts and clothing

- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/Belt/belts.yml
Added ability to put cluster grenades in sec's belts
It's stupid that they can't
Yaml uhhh
**Changelog**
:cl:
- add: Added clustergrenades to secoff belt's whitelist!
> Added Flashbang ClusterBang to Secoff's belts whitelists

- Content.Shared/_Shitmed/Surgery/Steps/SurgeryStepComponent.cs
- Content.Shared/_Shitmed/Surgery/SurgeryComponent.cs
- Content.Shared/_Shitmed/Surgery/Wounds/Components/WoundComponent.cs
- Resources/Locale/en-US/_Shitmed/entity-categories.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/bone.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/scars.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgeries.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/wounds.yml
- Resources/Prototypes/_Shitmed/Entities/categories.yml
without the EE stuff because it was a conflict farm
> use entity categories for surgeries and wounds

- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
i put implant not implanter there bruh
> fix binary implanter uplink listing

- Content.Server/NPC/Components/NPCSteeringComponent.cs
- Content.Server/NPC/HTN/PrimitiveTasks/Operators/MoveToOperator.cs
- Content.Server/NPC/Systems/NPCSteeringSystem.Context.cs
- Content.Server/NPC/Systems/NPCSteeringSystem.cs
- Resources/Prototypes/NPCs/idle.yml
makes HTN attempt to brake on arrival
should fix space carp idle movement throwing themselves off wrecks and cases like shown in media
this should probably be upstreamed eventually
https://github.com/user-attachments/assets/b8a87f9c-e681-4988-ba9f-ee829de62048
**Changelog**
:cl:
- fix: NPCs should no longer fly off when trying to do anything in 0-gravity, or if idle near space.
> htn braking in nograv

- Content.Server/NPC/HTN/PrimitiveTasks/Operators/MoveToOperator.cs
- Content.Server/NPC/Systems/NPCSteeringSystem.Context.cs
- Resources/Prototypes/NPCs/Combat/melee.yml
- fixes idle NPCs spinning
- fixes/mitigates NPCs circling their destination
- should in general have better behavior
- makes the code more sane
tested in all the same cases as #3181 plus some extra ones
fish still fly off but they at least brake, and this should really be fixed in a separate PR
**Changelog**
:cl:
- fix: Idle NPCs should no longer spin.
- fix: NPCs in nograv should no longer sometimes circle around their destination.
> #3181 fixed edition

- Resources/Prototypes/Catalog/uplink_catalog.yml
Traitors / Nukies were unable to buy antimov. Simple yaml fix
When multiple uplinks have the same item listed for the same price (I.E. Traitors can buy the board for 50tc and nukies can buy it for 50tc) no one can buy it. Tested, works.
:cl:
- fix: Traitors and nukies are once again able to buy antimov!
> Antimov fix

- Resources/Prototypes/_Goobstation/Research/civilianservices.yml
- Resources/Prototypes/_Shitmed/Research/civilianservices.yml
title
yaml
**Changelog**
:cl: the biggest bruh
- tweak: Compact defibrillator is now in the Advanced Treatment tech (T2 surgical tools).
> moves compact defib to t2 surgical tools tech

- Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Zero reason to give him one it just encourages killing people, he can print one if he really wants
:cl:
- remove: Removed roundstart nailguns.
> take away CE roundstart nailgun

- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/mantis_blade.yml
Slightly moves damage values for the Mantis blades around
They stopped doing damage when you reached a "Destroyed" state fro a limb, so fixing that by bumping the slash damage over the 9 damage threshold, adn reducing pierce
Fixes https://github.com/Goob-Station/Goob-Station/issues/3424
**Changelog**
:cl:
- tweak: Mantis blades now cut more than stab, and do more slash than pierce
> Mantis Blade Delimb Fix

- Resources/Prototypes/_Shitmed/Body/Organs/cybernetic.yml
:cl: Armok
- fix: Cyber eyes work now
> cyber eye bugfix

- Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
fixes the thing
last contrib forgot to add it
yaml (hell)
**Changelog**
:cl:
- tweak: Fixed BSO's hardsuit not appearing in their locker
> BSO hardsuit selector fix

- Content.Server/Holopad/HolopadSystem.cs
**Changelog**
:cl: VMSolidus (EE port by Ilya246)
- fix: Made some performance improvements to the Holopad system.
> Holopad System Performance Tweaks (Port of EE #2470)

- Content.Server/Shuttles/Components/ShuttleComponent.cs
- Content.Shared/CCVar/CCVars.Physics.cs
cvar change tested and seems to work but sometimes when near a grid it may decide for you to have friction anyway
**Changelog**
:cl:
- fix: Shuttle max speed is now properly 60 again.
- fix: Space is now frictionless again.
> upstream merge fixes

- Resources/Prototypes/Reagents/cleaning.yml
fixes lube foam not creating lube.
bug fix.
added 1 line of forgotten yaml.
**Changelog**
:cl:
- fix: Lube foam now creates lube.
> Lube bug fix (bounty)

- Content.Server/Polymorph/Systems/PolymorphSystem.cs
- Content.Shared/_DV/Carrying/CarryingSystem.cs
- Content.Shared/_DV/Containers/ContentContainerSystem.cs
- Content.Shared/_DV/Polymorph/PolymorphEvent.cs
Ports https://github.com/DeltaV-Station/Delta-v/pull/3505
See original PR.
See diff
N/A
N/A
**Changelog**
:cl: SolsticeOfTheWinter, SolStar2
- fix: You can no longer send people to the shadow realm via polymorph shitcode.
> [PORT] Fix sending people to the shadow realm.

- Resources/Locale/en-US/_Goobstation/ghost/ghost-role-component.ftl
- Resources/Locale/en-US/_Goobstation/objectives/conditions/steal-target-groups.ftl
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/justice.yml
- Resources/Prototypes/_Goobstation/Objectives/stealTargetGroups.yml
- Resources/Prototypes/_Goobstation/Objectives/traitor.yml
Gave Justice (HOS' sword) a ghost role. All it can do is talk like a Pai, albeit without the binary/radio capabilities of the Pai to rat on people. Intent is to have it screaming at people while HOS beats the shit out of them.
Added Justice as a thief objective, albeit with a high difficulty due to inability to bag/pocket it and new persona.
Jack asked plus funni
Yamlmaxxed
https://github.com/user-attachments/assets/dafdd82e-d907-4bd4-9e45-4d05e7964967
https://github.com/user-attachments/assets/cc87c383-d5a3-411a-b4e6-0a8f2d58f5ae
**Changelog**
:cl:
- add: Nanotrasen has added a Persona module to Justice. HOS' sword can now yell obscenities at criminals while they're being beat up.
- tweak: The Syndicate are now interested in stealing your fancy talking sword.
> [Bounty (kinda)] Persona Justice + Steal Objective

- Resources/Locale/en-US/_Goobstation/accent/accents.ftl
- Resources/Prototypes/Entities/Mobs/Species/human.yml
- Resources/Prototypes/_Goobstation/Accents/word_replacements.yml
Minor backend for humans
Goida
Really simpl
Humans = mald
> Totally normal PR

- Content.Shared/_DV/Containers/ContentContainerSystem.cs
Resolves #3525 
Resolves #3524 
**Changelog**
:cl:
- fix: Fixed polymorphs teleporting your brain.
> [HOTFIX] Fix polymorphs just fucking killin you.

- Resources/Maps/_Goobstation/Nonstations/nukieplanet.yml
nukies now get magic mirror
suggested by mocho
can un-resomi yourself as resomi or whatever nukie
can name yourself so no more "omg guys it's Operator November i saw him on tv!!!!"
don't need dna scrambler anymore but that's fine
if crew gets to nukie base they can use it but if crew gets to nukie base 1) round is probably over 2) what's the worst that could happen even if they got to the mirror
tested, works
**Changelog**
:cl:
- add: The nukie base now gets a magic mirror.
> nukie magic mirror

- Content.Goobstation.Server/Speech/CheeseAccentComponent.cs
- Content.Goobstation.Server/Speech/CheeseAccentSystem.cs
> Cheese Accent Goobmod

- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
Reverts Goob-Station/Goob-Station#3579
Imagine being Goob right now.
> Revert "[BOUNTY] Dragging no longer takes up your hand."

- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
Water Bottle can be inserted inside survival box once again.
Added DrinkBottle tag to water bottle prototype
**Changelog**
:cl:
- fix: Bottle can be inserted inside survival box once again.
> [Fix] Survival box bottle slot

- Content.Goobstation.Server/CloneProjector/CloneProjectorSystem.cs
- Resources/Prototypes/_Goobstation/Entities/Clothing/Belt/cloneprojector.yml
Gemini cannot be injected with holoparasite anymore.
Added CanHostGuardian to removedComponent in RemovedComponent of Gemini prototype.
Also changed some Dirty in SharedCloneProjectorSystem that used wrong component owners.
**Changelog**
:cl:
- fix: Gemini cannot be injected with holoparasite anymore.
> [Fix] Gemini Holoparasite interaction

- Content.Client/_Starlight/Chat/CollectiveMindSystem.cs
- Content.Goobstation.Server/Blob/NPC/BlobPod/BlobPodSystem.cs
- Content.Server/Chat/Systems/ChatSystem.cs
Fixes collective's mind repeat message to source
Check if clients is same uid as source
Before:
After:
**Changelog**
:cl:
- fix: Fixed collective mind message repeat for message source
> [Fix] Collective mind message repeat to source

- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Removed medigun from the uplink and blacklists the anaconda from nukies
Greed
**Changelog**
:cl:
- remove: Removed Mediguns pending rework™
- remove: Removed Anacondas from nukie uplinks
> (admeme bounty) Anaconda and medigun removal

- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Added 50 hours as bartender req for pun pun
**Changelog**
:cl: Aineias
- tweak: Taking over Pun Pun ghostrole now requires knowing how to be a bartender.
> [TWEAK] Kill shitters taking over pun pun

- Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
- Resources/Prototypes/Entities/Objects/Tools/lighters.yml
- Resources/Prototypes/tags.yml
Added a whitelist to cigarette packs. 
Added a tag for lighters, applied only to base (not too flippers, flipper lighter in a pack of cigs is just wrong)
Fuck um that's why.
Storage stacking is cringe, thus whitelist limits its abilities.
**Changelog**
:cl:
- tweak: Cigarette packs can now only store cigarettes and small lighters.
> Cigarette packs whitelisted storage

- Content.Shared/Species/Systems/ReformSystem.cs
> Fix Diona having a schrodinger's existential crisis

- Content.Goobstation.Server/HisGrace/HisGraceSystem.cs
- Content.Shared/Interaction/Components/UnremoveableComponent.cs
- Content.Shared/Interaction/SharedInteractionSystem.cs
- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Syndicate/his_grace.yml
His Grace no longer deletes on dropped.
**This pull request does NOT contain a hidden nerf for His Grace that is not in the changelog. I would do no such thing.**
It isnt supposed to.
Woundmed broke the unremovable component. I fixed it. (Bandaid, but it works :P)
N/A
N/A
**Changelog**
:cl: His Grace
- fix: Fixed His Grace deleting itself. (Okay, but for real this time. :3)
> [HOTFIX] His Grace round-remove bugfix.

- Content.Client/_Starlight/Chat/CollectiveMindSystem.cs
- Content.Goobstation.Server/Blob/NPC/BlobPod/BlobPodSystem.cs
- Content.Server/Chat/Systems/ChatSystem.cs
- Resources/Locale/en-US/_Starlight/collective-mind/collective-mind.ftl
> Revert "[Fix] Collective mind message repeat to source" & Better admin message wrap

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Dignitary/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Dignitary/nanotrasen_representative.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Security/brigmedic.yml
Despite being less than 3% of the workforce, harpy mains account for 80% of the shitpost PRs.
Anyway HOLY FUCK FREE GC.
https://github.com/user-attachments/assets/b9ff7e5a-cfe5-4040-8e25-a86677dddb97
**Changelog**
:cl:
- tweak: Nanotrasen HR has started enforcing stricter hiring policies for command and security.
> (Bounty) Fixes 65% of issues with command & security.

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Dignitary/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Dignitary/nanotrasen_representative.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Security/brigmedic.yml
Reverts Goob-Station/Goob-Station#3838
> Revert "(Bounty) Fixes 65% of issues with command & security."

- Resources/Prototypes/_Goobstation/Catalog/Cargo/cargo_livestock.yml
- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
**Changelog**
:cl:
- tweak: Lootbugs now sell for 500.
> (fix) fixes one of the test fail reasons

- Resources/Prototypes/Actions/types.yml
Early upstream port of:
- space-wizards/space-station-14#38454
- space-wizards/space-station-14#38573
General action fixes with the action refactor from upstream. Since it may be a bit before the next upstream merge that doesn't break the repository and require immediate reverting.
> [Upstream Port] Combat Mode and Tail Wagging Action Fixes

- Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
Added thirst to the Rodentia
Fixes https://discord.com/channels/1323488536501944350/1408244095398318162 (Goob MRP)
They lacked thirst.
Added thirst to their yml.
**Changelog**
:cl: Richard Blonski
- fix: Rodentia now get thirsty.
> Fixes - Rodentia thirst

- Resources/Prototypes/_Goobstation/Maps/cluster.yml
mald pr
1 line to save cluster from death by no power
cluster solely relies on salv doing their job to have power, so this removes the limit on salvs
more salv -> more power
> fix cluster

- Content.Server/_Shitcode/Heretic/Ritual/CustomBehavior.Sacrifice.cs
lets heretics sacrifice other heretics
gives 3 point
antag infighting goo
tested, works
tested that can't sac normal people
**Changelog**
:cl:
- add: Heretics may now always sacrifice other heretics for 3 knowledge points.
> heretic heretic sacrifice

- Resources/Prototypes/Entities/Objects/Power/powercells.yml
Potato Batteries can now be anchored and used to power LV circuits
fun
they provide 30 watts of power, barely more than enough to power a single light
**Changelog**
:cl:
- add: Potato Batteries can now be used to generate a small amount of power by wrenching them onto an LV cable! Botanist engineering time!
> [BOUNTY] Potato Power

- Content.Server/_White/Xenomorphs/FaceHugger/FaceHuggerSystem.cs
The facehugger can now be removed from the pocket.
> fix facehuggers

- Resources/Locale/en-US/_Goobstation/clothing/shoes.ftl
- Resources/Prototypes/Entities/Clothing/Shoes/misc.yml
- Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
weh ducky and banana slippers have sounds again
why: sovlllll
> bring back slipper footstep sounds

- Resources/Prototypes/_Goobstation/Objects/Devices/translator_implants.yml
Added Schechi and Ka'rakk to the librarian implant.
Some goober forgot to add it to the implant when adding the new languages.
Added 2 new lines to translator_implants.yml, and some comments!
**Changelog**
:cl:
- add: Added Schechi and Ka'rakk to the librarian language implant.
> Add the 2 new species specific languages to the librarian implant.

- Resources/Prototypes/_Goobstation/Loadouts/Jobs/Civilian/botanist.yml
fix #3974 
**Changelog**
:cl:
- fix: You can wear Botany Berets again
> fix botany beret

- Resources/Locale/en-US/_white/ghost/roles/ghost-role-component.ftl
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/maid.yml
16+ server btw
16+ server btw
16+ server btw
16+ server btw
**Changelog**
:cl:
- tweak: Xenomorph maids are no longer walking ban bait. Still kinda cute though.
> Remove ERP ban bait, holy fuck.

- Resources/Prototypes/_Goobstation/GameRules/bingleEvent.yml
> no more bingle spam

- Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
- Resources/Prototypes/_Goobstation/Recipes/Lathes/security.yml
1 more nerf and someone will make single use fillable medipens.
Airloss cart was ignored becuase its nothing :tm:
tested, works. its fuckin yaml brody.
**Changelog**
:cl:
- tweak: Reduced the amount of autoinjector gear available shiftstart.
- tweak: Most autoinjector cartidges now require plasma to fabricate.
> AutoInjector stock and price adjustment

- Resources/Prototypes/_White/GameRules/events.yml
tweaked xenomorph chaos score
xenomorphs are super rare for no reason, like you see them once every 6-7 shifts now
(edit: it has now been over 11 shifts without any xenomorphs)
700 -> 400
**Changelog**
> tweaked xeno chaos score

- Content.Client/_Shitmed/Medical/Surgery/SurgeryBui.cs
- Content.Server/_Shitmed/Medical/Surgery/SurgerySystem.cs
- Content.Shared/_Shitmed/CCVar/SurgeryCVars.cs
- Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Start.cs
- Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Steps.cs
- Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.cs
literally no reason for the verb to have been in server, crime against humanity
it was also very easy to just predict the buttons
(sounds are predicted in LV stitches pr)
:cl: mocho is a chud
- fix: Fixed surgery not being predicted.
> fucking predict surgery

- Resources/Prototypes/game_presets.yml
20-30 antags per shift, stop enabling this shit
> Stop letting chuds enable this game mode, it does not work

- Content.Server/Cloning/CloningSystem.cs
- Resources/Prototypes/Entities/Mobs/Player/clone.yml
This PR fixes: #4109 
Fixes: #4109 
- Edited `clone.yml` to include `EncryptionKeyHolder`
- Edited `CloningSystem.cs` to check for `EncryptionKeyComponent` and copy all keys.
- Tested that this does not give errors or affect normal paradox clones.
**Changelog**
:cl: Richard Blonski
- fix: Paradox Clone IPC's spawning without the proper encryption keys.
> Fixes #4109  IPC Clone doesn't spawn with the encryption key

- Resources/Prototypes/Entities/Structures/conveyor.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Devices/Electronics/misc_signallers.yml
fix a few niche trap things to work better
:cl: Armok
- tweak: Conveyors cannot be rotated while wrenched down
- tweak: Proximity signallers trigger unless youre moving very slow (crawl speed)
> Buff Armok

- Content.Shared/Body/Systems/SharedBodySystem.Organs.cs
- Content.Shared/Construction/Steps/TagConstructionGraphStep.cs
- Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Steps.cs
- Resources/Prototypes/Entities/Objects/Devices/flatpack.yml
- Resources/Prototypes/_Goobstation/tags.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgeries.yml
augments being deleted when reinstalled was caused directly by mocho chud shit of organs healing when replaced, so removed that shit it was hijacking the Used bool
construction steps use protoid because fuck you
:cl:
- fix: Fixed augments being deleted if you reinstalled them.
> fix stupid chud shit

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
- Resources/Prototypes/_Goobstation/Heretic/Heretic/heretic_rituals.yml
- Resources/Prototypes/_Goobstation/tags.yml
- Resources/Prototypes/tags.yml
Made rust walkers slightly more difficult to mass produce
:cl: Armok
- tweak: Rust walkers slightly harder to mass produce
> Rustwalker change

- Resources/Maps/centcomm.yml
…just the MV wire
Guess what WIRES I HATE WIRES
missing wires
mapping
Imagine a angry LV wire here
**Changelog**
> Hotfix 2 for CC

- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR6Antag.xml
> typo fix because fen merged when there was review changes

- Content.Goobstation.Shared/MartialArts/SharedMartialArtsSystem.SleepingCarp.cs
- Content.Shared/Weapons/Reflect/ReflectComponent.cs
it was never networked :trollface:
fixes #4189
> fix scarp troll

- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/trevor.yml
spawned trevor wasn't getting proper accesses, but manually spawned ones did so i um fixed it
oh yeah fixes #4091 
idk what loltart was cooking but that tag wasn't it
**Changelog**
:cl:
- fix: Trevor can now access Sec, Brig and Maints again
> Fix Trevor Access

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
- Resources/Prototypes/Entities/Objects/base_contraband.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/base_contraband.yml
Zookeepers are now allowed to have tranquilizer shotgun shells.
Tranq shells are part of the zookeepers standard equipment.
Added a new BaseSecurityZookeeperContraband ID
**Changelog**
:cl:
- fix: Tranquilizer shotgun shells are no longer contraband for Zookeepers.
> Tranq shells are no longer contra to Zookeepers

- Resources/Maps/centcomm.yml
fixes more wires but also adds new plush
well hotfix and plushies
mapping, truly we need a way to indicated wires above EVERY other texture in the game to make mapping them easier.
Imagine a plushie next to a LV wire here
**Changelog**
> The CC hotfixes never end, but also plushies

- Content.Goobstation.Shared/Factory/SharedInteractorSystem.cs
> fix interactor direction

- Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
if big ass xenos can do it (massively oversized) and mice (no hands), why not fishe
:cl:
- tweak: Carp can now ventcrawl. :fish:
> let fish vent crawl

- Resources/Locale/en-US/_Goobstation/job/job-names.ftl
- Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
Some descriptions were missing, or incorrect.
Also ammo exam text stated the wrong capacity.
I LOVE BUYING uplink-estoc-ammo-name WITH DESCRIPTION uplink-estoc-ammo-desc
**Changelog**
:cl:
- fix: Added missing name and description for the Estoc ammo.
- fix: Pistol magazine now show the correct maximum capacity.
> Fixed missing/incorrect names and descriptions.

- Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR6Antag.xml
Copy + Paste strikes again. Reiteration for CL.
**Changelog**
:cl:
- fix: Roleplay rule 6 having incorrect referenced precedent - Roleplay and repetition applies to antags.
> Roleplay rule 6 fix.

- Content.Server/Zombies/ZombieSystem.cs
fixes #4068
https://github.com/user-attachments/assets/58c3e89f-d05f-4b58-a623-e02f883de72d
**Changelog**
:cl: eggywazzy
- fix: Zombies can no longer infect through raised shields.
> raised shield infection fix

- Content.Goobstation.Common/Cloning/TransferredToCloneEvent.cs
- Content.Goobstation.Server/Changeling/ChangelingSystem.Abilities.cs
- Content.Goobstation.Server/Changeling/ChangelingSystem.cs
- Content.Goobstation.Shared/Changeling/Systems/SharedChangelingSystem.cs
- Content.Goobstation.Shared/Heretic/HereticCloningSystem.cs
- Content.Server/Cloning/CloningPodSystem.cs
- Content.Server/Cloning/Components/BeingClonedComponent.cs
- Resources/Prototypes/Entities/Mobs/Player/clone.yml
fixed lings not having any abilities (ChangelingComponent was fucking fake, real component is ChangelingIdentity thanks obama) and normal blood etc
when a mind is added to the cloned body of either antag, the original loses its powers
this is either when you click yes in the cloning EUI, or if someone brain transplants/mindswaps into the clone
lings will also gib to make it extra obvious that med is being stupid, and it makes sense
> make ling + heretic cloning better

- Resources/Locale/en-US/_Goobstation/station-laws/laws.ftl
- Resources/Prototypes/_DV/siliconlaws.yml
- Resources/Prototypes/borg_types.yml
Half the borg lawsets just let you kill people if you feel like it lmao
:cl: Armok
- tweak: Fix borg lawsets
> Dechuddify borg laws

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Basic/plasma_cutter.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/magfed_lasers.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Pistols/pistol.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/dart_gun.yml
Until now multishot was just a free double DPS multiplier, now you will actually miss unless close range
:cl: Armok
- tweak: Heavy multifire nerf, use one gun to aim, use two to mow down crowds
> Nerf multishot

- Resources/Locale/en-US/chat/highlights.ftl
NTR and BSO now have default highlights.
they didnt have one before.
it was shockingly easy.
**Changelog**
:cl:
- add: NTR and BSO now have default highlights.
> NTR and BSO highlighting

- Resources/Prototypes/Catalog/Fills/Crates/cargo.yml
- Resources/Prototypes/_DV/Catalog/VendingMachines/Inventories/salvage_points.yml
- Resources/Prototypes/_Lavaland/Catalog/Fills/Crates/cargo.yml
moved CrateCargoClarkeAssembly to _Lavaland and removed something i accidentally left in (oops)
**Changelog**
:cl:
- remove: Removed two instances of high energy power cells in salv vendor
> yaml "bug" fix

- Resources/Prototypes/_Imp/_Drone/Mobs_Player_silicon.yml
they can be flashed, even if they wear welding mask it won't protect
shitters pick drones too much
:cl:
- tweak: Drones can now be flashed.
> kill shitter drones

- Content.Server/_Shitcode/Heretic/EntitySystems/HereticKnowledgeSystem.cs
- Content.Server/_Shitcode/Heretic/EntitySystems/HereticSystem.cs
- Content.Shared/_Shitcode/Heretic/Components/HereticComponent.cs
dogshit shitcode never removed actions on shutdown so they just lingered while doing nothing
also you cant see rifts anymore
> lose useless heretics actions after HereticComponent is removed

- Resources/Locale/en-US/_Goobstation/ghost/ghost-role-component.ftl
- Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
- Resources/Prototypes/_White/Entities/Markers/Spawners/ghost_roles.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/drone.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/hunter.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/larva.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/praetorian.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/queen.yml
- Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/sentinel.yml
Fixes #4246 
I created a rule's string for Xenomorphs. **Now please be aware I'm not much of a writer so if someone wants to cook up something better and more expansive then now's your moment.**
**Changelog**
:cl:
- add: Xenomorph Rules String for ghostrole raffle has been added
> Xenomorph Ghostrole Rule String

- Resources/Prototypes/_DV/Catalog/VendingMachines/Inventories/salvage_points.yml
added jump boots to salv vend
it should be added to the vendomat ss13 parity
1 yaml line
not needed
none
**Changelog**
:cl: Androidonator
- add: Jump boots to salvage points vendor
> Added jump boots to salvage points vendomat

- Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Reverts Goob-Station/Goob-Station#4304
> Revert "fix shitsalv"

- Resources/Prototypes/Catalog/VendingMachines/Inventories/nutri.yml
title
:cl: Armok
- add: Chainsaw added to hacked botany vendor
> Bounty - Add chainsaw to hacked botany vendor

- Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
Add raw tag to meat, fixing a bug where sheet meister could not use it
:cl: Armok
- fix: Sheet Meister can use meat now
> meat bugfix

- Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
he can eat things now yay
:cl: Armok
- fix: Lootbug can now properly eat things
> fix lootbug devour

- Resources/Prototypes/_Imp/_Drone/Mobs_Player_silicon.yml
Fix for https://github.com/Goob-Station/Goob-Station/issues/4206. Drones no longer flash themselves when turning on their flashlight. No longer makes flashing noise.
https://github.com/user-attachments/assets/d323aef6-0793-4ab2-b661-9113ea0228ef
**Changelog**
:cl:
- fix: Drones will no longer flash themselves when turning on their flashlight.
> Removed drones ability to flash
